### ISSUE TITLE
JJR PP than PP

### ISSUE THREAD

**Issue by amir-zeldes** [UniversalDependencies/UD_English-EWT#101]
EWT has three analyses for "JJR PP than PP", e.g. "safer in that one room **than in a huge unknown house**":

http://match.grew.fr/?corpus=UD_English-EWT@2.6&custom=5f9c2a8ed4c5a&eud=yes

1. `advcl` from the comparative into the second head noun, with dependents `case` (for the preposition), `mark` for "than"
2. `obl` from the comparative into the second head noun, with the preposition AND "than" both as `case`
3. `obl` or `nmod` coming out of a modifier of the JJR (e.g. "achieve" in "simpler ... to achieve in production ... than in industrial processing..."), so that the dependent ("achieve") governs the "than" phrase, again with double case

GUM has analyses 1 and 2. I like 1. better, since I don't think "than" is really `case` to the PP head - I think it's the `mark` of an elliptical clause ("safer in that room, than [it is safe] in a huge house"), governed by the comparative, which triggers the reduced 'than' clause. @nschneid @sebschu would everyone be OK with consolidating to option 1?

**Comment by nschneid** [comment]
I think [de Marneffe et al. (2013)](http://www.aclweb.org/anthology/W13-3721) argues the than-PP should be licensed by the comparative item.

**Comment by amir-zeldes** [comment]
Yes, exactly, we're in agreement on that (advcl from the comparative, in 1. above, which @mcdm has as well). The only caveat I would have there is that I would interpret an analytic comparative as headed by the lexical adjective, not the word "more" (so the edge would come out of "beautiful", in "more beautiful")

**Comment by nschneid** [comment]
On that point I suppose the choice is between

- a nonprojective analysis that pinpoints the word contributing the comparative morphology as licensing the than-PP
- a projective analysis in which the word "more" is taken to be a special function word that marks the adjective (or adverb) *phrase* as comparative, licensing the than-PP; on this interpretation attaching to the head of the adjective/adverb phrase makes sense

I could live with either of these. Note that even the projective-adjective-phrase option would lead to nonprojectivity in attributive position ("A wiser man than me said...").

**Comment by amir-zeldes** [comment]
That's fine by me. I think "wiser" just has the heavy constituent modifier extraposed to later, but is really the same as:

"a man wiser than me said"

Which is projective, and makes the analysis using the comparative as governor look plausible to me. I just fixed GUM, not sure I'll manage EWT before UD freeze (any volunteers?)

**Comment by dan-zeman** [comment]
Comparative constructions are discussed extensively in the guidelines, e.g. [here](https://universaldependencies.org/workgroups/comparatives.html). In short: in _X is more intelligent than Y_, Y is attached as `obl` to _intelligent_, not to _more_.

**Comment by amir-zeldes** [comment]
Exactly - it sounds like we are all in agreement, so is there anything speaking against consolidating EWT using option 1.? I've already done this in GUM.

BTW there is an example on the page @dan-zeman linked to which effectively has analysis 1.:

"He plays better drunk than sober"

with "sober" as advcl and "than" as mark, so I'd say 1. is canonical (although I disagree with that analysis making `he ->acl drunk`; I think it's advcl to plays, like "while drunk", but that has nothing to do with the current issue)

**Comment by nschneid** [comment]
Putting this under #299. It's not just than+PP—there are other issues with comparatives in EWT.

To @amir-zeldes's concern about `acl`, it is documented [here](https://universaldependencies.org/u/dep/acl.html) as the solution for optional depictives.

**Comment by nschneid** [comment]
> (although I disagree with that analysis making `he ->acl drunk`; I think it's advcl to plays, like "while drunk", but that has nothing to do with the current issue)

noting that this is now `advcl` per the amendment on optional depictives UniversalDependencies/docs#855
