### ISSUE TITLE
What a NOUN!

### ISSUE THREAD

**Issue by amir-zeldes** [UniversalDependencies/UD_English-EWT#103]
For exclamative "what a NOUN", EWT has either `det` or `det:predet` for the "what" (it seems to vary across genre subcorpora?). For GUM we're using `det:predet`. Should that be consolidated in EWT as well?

http://match.grew.fr/?corpus=UD_English-EWT@2.6&custom=5fad78d3c256c&eud=yes

**Comment by nschneid** [comment]
"It was incredible what a good player Alena was."—is this a free relative clause?

**Comment by nschneid** [comment]
cf. I know what a problem this is
I know how much of a problem this is

**Comment by nschneid** [comment]
(related to UniversalDependencies/docs#454)

**Comment by amir-zeldes** [comment]
I see what you mean, but I think the Alena example is a little different. For the NP-style analysis I think the reasoning works by analogy to "such" in:

  * what a great player
  * such a great player

The Alena example does not allow substitution with "such":

  * It was incredible what/*such a good player Alena was

As for that sentence, I think it's an extraposed subject clause:

  * Extraposed: It/expl was incredible [[what a good player] [Alena] was]
  * Unextraposed (hypothetical): [[What a good player] [Alena] was] was incredible

For a free relative analysis it would be nice for it to be possible to insert a demonstrative correlate pronoun:

  * I like what I see (double function for "what")
  * I like that which I see (separates the double function)
  * What a good player was Elena
  * ??That what a good player was Elena

So I'm not sure it's a free relative, but that's not necessarily decisive either way, if you accept the argument by analogy to "such".

**Comment by nschneid** [comment]
OK the "such" test sounds good to me.

**Comment by ethanachi** [comment]
Fixed the following:

- email/enronsent_10_01-0094
- email/enronsent_26_01-0003
- reviews/061721-0001
- reviews/171225-0001
- reviews/252791-0003

Thanks @nschneid for pointing these out.
