### ISSUE TITLE
so ADJ that ADVCL

### ISSUE THREAD

**Issue by amir-zeldes** [UniversalDependencies/UD_English-EWT#106]
There is only one case of "so ADJ that ADVCL" annotated as such in the corpus:

  * seeing you so relaxed that you are sleeping/`advcl` will send the message that everything is OK

http://match.grew.fr/?corpus=UD_English-EWT@2.7&custom=5fb5361c6ef6b&eud=yes

But there are a few more which I think are incorrectly annotated as `ccomp`:

Some of these are false positives (adjectives introducing direct speech etc.), but a few have the same structure as the case above, for example:

  * Everyone was so helpful that I cannot wait/`ccomp` to go back ..... (should be be `advcl`?)

http://match.grew.fr/?corpus=UD_English-EWT@2.7&custom=5fb5353b66cc8&eud=yes

**Comment by nschneid** [comment]
Agreed, `advcl` seems sensible for clauses licensed by "so" (the degree-consequence construction).

"that" isn't actually required, so here's a broader query:

http://match.grew.fr/?corpus=UD_English-EWT@2.7&custom=5fb537e7b3d81&eud=yes

e.g. _these demons are so GREEDY, they want as much of their "product" as they can get_

I didn't find any "enough" + ccomp examples.

**Comment by amir-zeldes** [comment]
Good point, just ran that search on GUM and corrected cases without "that" (see amir-zeldes/gum@81ee754 )

**Comment by manning** [comment]
I agree that `ccomp` is wrong and `advcl` would be right!

**Comment by nschneid** [comment]
Updated queries:
- [EWT "so" + ccomp](https://universal.grew.fr/?custom=650e4b4209174): changing some of these to advcl
- [EWT "so" + advcl](https://universal.grew.fr/?custom=650e4f4846052)

**Comment by nschneid** [comment]
- [EWT "so" taking an advcl dependent](https://universal.grew.fr/?custom=650e523730301): the subordinate clause should attach to the degree-qualified adjective or adverb, not "so"
