### ISSUE TITLE
Inconsistency in the labeling of "fries"

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_English-EWT#109]
At the behest of a user who noticed some errors in the way our automatic lemmatization tool detected "fries", I went through the EWT data and found that there are a few inconsistencies in the way it is labeled.  In some cases, "fries" is treated as a single object which can be purchased from a restaurant (eg a "large fries") with the lemma "fries", and in other cases it is treated as a collection of things which are individually each a "fry".  I believe there is some inconsistency here.

Furthermore, if there is any chance of adding one or more sentences to the data with "fries" as a verb, that would greatly aid tools such as ours process fry as a verb.

Thanks!

https://github.com/stanfordnlp/stanza/issues/542

```
# sent_id = answers-20111019100027AAdxgXV_ans-0008
# text = Because Large Fries give you FOUR PIECES!
3       Fries   fries   NOUN    NNS     Number=Plur     4       nsubj   4:nsubj _

# sent_id = answers-20111019100027AAdxgXV_ans-0019
# text = - Large fries
3       fries   fries   NOUN    NNS     Number=Plur     0       root    0:root  _

# sent_id = answers-20111031103114AA61BW3_ans-0014
# newpar id = answers-20111031103114AA61BW3_ans-p0004
# text = If you're looking for a good burger, some great fries (they are too die for!), and good drinks, go to Chickie & Pete's!
12      fries   fries   NOUN    NNS     Number=Plur     8       conj    4:obl:for|8:conj:and    _

# sent_id = answers-20111031103114AA61BW3_ans-0016
# text = If you go, make sure you order the crab fries, you won't regret it :)
11      fries   fries   NOUN    NNS     Number=Plur     8       obj     8:obj   SpaceAfter=No

# sent_id = reviews-154658-0004
# text = (other items: chicken fingers, wings, asian pizza, and yam and regular fries)
17      fries   fry     NOUN    NNS     Number=Plur     6       conj    3:appos|6:conj:and      SpaceAfter=No

# sent_id = reviews-196219-0003
# text = SO, IF YOU WANT A BURGER AND FRIES, WELL, IT IS OK.
9       FRIES   fry     NOUN    NNS     Number=Plur     7       conj    5:obj|7:conj:and        SpaceAfter=No

# sent_id = reviews-068436-0006
# text = Disgusting french fries is very best menu.
3       fries   fry     NOUN    NNS     Number=Plur     7       nsubj   7:nsubj _
```

**Comment by nschneid** [comment]
Good catch. In my view the lemma should be "fry" across the board.

**Comment by AngledLuffa** [comment]
Probably.  Thanks!  Something for version 2.8?  Need a hand?

Is there a possibility to add at least one "to fry" -> "Mary fries" sentences?  Or is that against the general guidelines of the treebank?

**Comment by nschneid** [comment]
Thanks for fixing in #112. To your question, the EWT corpus is not accepting new sentences, but there are other UD English corpora that might have that sense.

**Comment by AngledLuffa** [comment]
LinES has each of potatoes, tomatoes, and busy/buys in the right context, but no one acknowledges the existence of "fries" as a verb.
