### ISSUE TITLE
Potatos & tomatos

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_English-EWT#110]
The words "potatos" and "tomatos" in EWT are misspellings.  They should be "potatoes" and "tomatoes".  Is this kind of error fixable or is that considered English text in its natural form, so not worth fixing?

**Comment by nschneid** [comment]
They should be marked with `Typo=Yes`, and the `CorrectForm` can be provided as well: https://universaldependencies.org/u/overview/typos.html

**Comment by ethanachi** [comment]
Adding to Nathan's comment, we don't usually fix typos in the wild (EWT has a particularly high number of those), but annotate the correct lemma / provide the `CorrectForm`.

**Comment by AngledLuffa** [comment]
I don't see CorrectForm marked on the training data in 2.7, although I do see some typos labeled
