### ISSUE TITLE
get home

### ISSUE THREAD

**Issue by amir-zeldes** [UniversalDependencies/UD_English-EWT#115]
"home" is currently tagged as an adverb when used as a destination in expressions like "go home", which I think is right: it's like "go homeward". However it has the same analysis for "get home" ([two cases](http://match.grew.fr/?corpus=UD_English-EWT@2.7&custom=5fec982c11094)).

Should this maybe be `xcomp`? For me it's a little different from "go home", since in this case, "home" doesn't describe how or where you do something, it's saying you will "get to the state of being home", so "get" might actually be the "become"-get here, which takes `xcomp`.

**Comment by nschneid** [comment]
"go/get home" is like "go/get to school" or "go/get out", right? The spatial use seems separate from e.g. "get ready".

CGEL classifies such uses of "home" as intransitive prepositions because they alternate with PPs. In UD terms I suppose it would be `ADV`.

**Comment by amir-zeldes** [comment]
Yes, I definitely agree it's upos=ADV, my question is whether it's advmod or xcomp? Go home is directional, while "get home" could be decomposed into something like "I become -> I am home" (i.e. get as a "become"-verb). I guess that doesn't hold for "get to school" (I become -> *I am to school)

**Comment by nschneid** [comment]
Would `xcomp` be used for "get out" (depart) or "get out of the way"?

**Comment by amir-zeldes** [comment]
Ooh, now I'm doubting this whole thing actually... Because there's no big difference to "move out of the way", which is definitely not a 'become' verb. OK, this is too slippery a slope for me, I'm fine with closing this if no one objects.
