### ISSUE TITLE
"as soon as" has two analyses in EWT

### ISSUE THREAD

**Issue by amir-zeldes** [UniversalDependencies/UD_English-EWT#118]
Currently there are two patterns; in both cases, "soon" governs "as"1 as `advmod`, but the difference is in how the subordinate clause predicate is governed:

1. as1 --advcl-> PRED --mark-> as2 ([9 hits](http://match.grew.fr/?corpus=UD_English-EWT@2.7&custom=5fece9f9e8b61&eud=yes))
2. soon --advcl-> PRED --mark-> as2 ([11 hits](http://match.grew.fr/?corpus=UD_English-EWT@2.7&custom=5fece9159d66b&eud=yes))

I think I like 2 better, which keeps the "phrase head as local head" dynamic, and it has the majority, so I'll consolidate GUM to that unless I hear otherwise (we also had a third variant with `fixed`, but I think treating it compositionally should work fine).

**Comment by nschneid** [comment]
https://universaldependencies.org/workgroups/comparatives.html discusses the as-as comparative construction—does that answer your question?

**Comment by amir-zeldes** [comment]
Yes, thank you - that page also conforms with analysis 2. I just unified the 6 cases we had in GUM (will propagate to UD on release) - leaving this open for EWT.

**Comment by nschneid** [comment]
Fixed for EWT via #281
