### ISSUE TITLE
Enhanced dependencies sometimes repeating normal dependencies

### ISSUE THREAD

**Issue by amir-zeldes** [UniversalDependencies/UD_English-EWT#125]
When edeps differ from the normal ones, there seem to be two practices in EWT. For example relative clauses have enhanced functions like `ref` etc. *instead* of repeating the normal relation and head:

```
# sent_id = weblog-juancole.com_juancole_20040324065800_ENG_20040324_065800-0004
# text = US troops there clashed with guerrillas in a fight that left one Iraqi dead.
...
10	that	that	PRON	WDT	PronType=Rel	11	nsubj	**9:ref**	_
11	left	leave	VERB	VBD	Mood=Ind|Tense=Past|VerbForm=Fin	9	acl:relcl	9:acl:relcl	_
```

But external subjects *add* the enhanced dependency on top of the regular one, separated by a pipe:

```
# sent_id = weblog-juancole.com_juancole_20041120060600_ENG_20041120_060600-0008
# text = Even if local Palestinian leaders remain strong enough to keep al-Qaida out, the festering Israeli-Palestinian struggle remains among the best recruiting posters for al-Qaida with young Muslim men.
...
5	leaders	leader	NOUN	NNS	Number=Plur	6	nsubj	**6:nsubj|8:nsubj:xsubj**	_
6	remain	remain	VERB	VBP	Mood=Ind|Tense=Pres|VerbForm=Fin	22	advcl	22:advcl:if	_
7	strong	strong	ADJ	JJ	Degree=Pos	8	amod	8:amod	_
8	enough	enough	ADJ	JJ	Degree=Pos	6	xcomp	6:xcomp	_
9	to	to	PART	TO	_	10	mark	10:mark	_
10	keep	keep	VERB	VB	VerbForm=Inf	7	advcl	7:advcl:to
```

Is this difference intentional? If not, which way is considered correct?

**Comment by amir-zeldes** [comment]
The documentation sounds to me like the ref example is wrong and everything should be repeated:

https://universaldependencies.org/format.html

**Comment by dan-zeman** [comment]
The documentation of [enhanced dependencies is here](https://universaldependencies.org/u/overview/enhanced-syntax.html) and I think this approach adheres to it. (And historically, to the proposal by Schuster and Manning, 2016.)

Whether or not it is a good idea, that is another question. I also found myself recently pondering about this asymmetry. Maybe it would be worth discussing for possible future refinement of the enhanced guidelines... but then it definitely should be an issue at the main docs repo, not here.

**Comment by amir-zeldes** [comment]
I see, so that means that the fact that the relative pronoun is a subject of the relative clause verb is not meant to be represented in the enhanced graph at all, right? OK, in that case I think I understand the idea, so I'll close this issue.
