### ISSUE TITLE
Annotation Error on SCONJ

### ISSUE THREAD

**Issue by janetlauyeung** [UniversalDependencies/UD_English-EWT#129]
According to the annotation guidelines on [SCONJ](https://universaldependencies.org/u/pos/SCONJ.html), adverbial clause introducers such as "when" should be tagged as **SCONJ**; however, this is currently annotated as _ADV_.

e.g. Never had a problem with the staff and found them very helpful **when** something went wrong.

**Comment by nschneid** [comment]
Quote from the `SCONJ` guidelines:

> Adverbial clause introducers, like [en] when, since, or before (when introducing a clause not a nominal)

Is this correct per #88?

**Comment by nschneid** [comment]
Also note that "where" and "when" are *always* `ADV` in EWT, even when attaching as `mark`. In GUM it seems that `mark` always corresponds to `SCONJ`.

**Comment by amir-zeldes** [comment]
Yes, in GUM that happens here:

https://github.com/amir-zeldes/gum/blob/master/_build/utils/upos.ini#L19

If someone thinks this should look different, just let me know

**Comment by nschneid** [comment]
Asked a clarification question in amir-zeldes/gum/issues/67

**Comment by amir-zeldes** [comment]
Repeating here for convenience: "when" can be `advmod` in a question. Here are the different constructions as I understand them (and as they should be annotated in GUM, AFAIK):

  * When/ADV/advmod did you arrive/VERB/root? (question)
  * Call me when/SCONJ/mark you arrive/VERB/advcl. (subordinate advcl)
  * Tell me when/SCONJ/obj you arrived/VERB/acl:relcl. (free relative)

**Comment by nschneid** [comment]
Great, I think this is simpler/more intuitive than what you suggested at the end of #88

**Comment by nschneid** [comment]
Turns out we were looking at an out-of-date version of the UD trees. The fixes were implemented in UniversalDependencies/UD_English-EWT#90.
