### ISSUE TITLE
UPOS inconsistency: indefinite pronouns/pro-adverbs

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#132]
* 2 misspelled indefinite pronouns should be tagged as `PRON`: http://match.grew.fr/?corpus=UD_English-EWT@2.7&custom=603ad285dd480&eud=yes
* {some,any,every,no}where is sometimes `ADV`, sometimes `NOUN`. What is the criterion? http://match.grew.fr/?corpus=UD_English-EWT@2.7&custom=603ad208684df&clustering=N1.upos

**Comment by amir-zeldes** [comment]
Looks like the latter comes from xpos=NN, which seems to happen sporadically when it's an object ("I want somewhere...") or a PP ("from somewhere"). In PTB these are consistently RB, incl. "out of nowhere" etc., so I think morphosyntactically they should be RB+ADV here as well, even though they are 'wrapped' in an NP.

**Comment by nschneid** [comment]
In another corpus I encountered "nowhere but X", where "but X" should be a PP modifying "nowhere". But this is awkward if "nowhere" is an ADV attaching as advmod.

"Nowhere" also licenses "else", like the other indefinite pronouns.

So I'm not sure I see the motivation to call "nowhere" ADV if "nobody" is PRON. Is "nowhere" just a pronoun that often heads an adverbial NP?

**Comment by amir-zeldes** [comment]
No, I think it's still an adverb, it's not so unusual for an adverb to take modifiers IMO. I mean, it's interchangeable with "here" and "there", so it seems pretty canonical to consider it an adverb.

**Comment by nschneid** [comment]
And its distribution is even more like "where", which also licenses "else". I suppose it would be surprising to call "where" a pronoun, so ADV with `PronType=Ind` would work I guess.

Here are some borderline nominal cases:

- "somewhere else": advmod(somewhere/ADV, else/ADV)?
- head of PP: "anywhere in the world" (I guess not a problem to call this `obl`)
- head of postpositive adjective: "somewhere nice"
  * This creates a weird situation where a word attaching as `advmod` has an `amod` dependent. But there are a few of these already in GUM so I guess the validator allows it.
  * For "live somewhere rural", EWT has `advcl` instead of `advmod` (not sure why).
- object of a preposition: "compare it **to** somewhere like Central Otago" (EWT), "set it to anywhere between 78-82" (EWT), "the middle of nowhere" (GUM)
- relative clause head: "anywhere you like" (GUM)

I think you're arguing these should all be `ADV`. Are you OK with an ADV having an `amod`?

**Comment by amir-zeldes** [comment]
Basically I think this is another flavor of the same issue we talked about today RE: nsubj: it's like a unary derivation where you wrap an ADV in something to allow it to work as an argument etc.. But the underlying POS category is still ADV, otherwise you'd get the same issue with core adverbs like "here" and "there" ("in there", "the good old here and now") - in context these things can get case, amod, and other functions because they function like NPs, but morphologically I'd say they are still adverbs, and I expect PTB tagging follows the same behavior for xpos.

**Comment by nschneid** [comment]
PPs yes, but there are other PPs with non-nominal complements (e.g. "for free"). "The here and now" is an idiom (*the now and here). "Here" and "there" don't really lend themselves to adjective dependents in the way that "somewhere" does.

**Comment by nschneid** [comment]
While implementing UniversalDependencies/docs#517, rediscovering this issue of indefinite pro-forms occurring sometimes in noun-like contexts, for which EWT is not consistent about tagging:

- compare it to **somewhere** like Central Otago
- she has **nowhere** to go

It seems that PTB (and GUM) policy is to tag these as adverbs. My question is then what the external deprel should be—if there is a free relative, does that make it more nominal-like, triggering `obl:unmarked` (formerly `:npmod`), or should it be `advmod`?

- I recommend buying a single unlimited Europass and travelling **anywhere** in the EU your heart desires.

I suppose defaulting to `advmod` for all unmarked non-core uses would be a simple enough policy, but it seems kind of arbitrary to distinguish "anywhere/ADV/advmod your heart desires" and "anyplace/ADV/advmod your heart desires" from "any place/NOUN/obl:unmarked your heart desires". I guess this is another flavor of the UD-lacking-a-proper-adverbial-relation problem....

**Comment by nschneid** [comment]
Also there's a GUM token that is NOUN https://universal.grew.fr/?custom=6688bce47f934

**Comment by amir-zeldes** [comment]
Fixed GUM token. Generally I think distinguishing "any place" from "anywhere" on the POS level is fine, since the fused orthography corresponds to the lexicalization which justifies the re-analyzed/non-compositional morphosyntactic analysis.
