### ISSUE TITLE
nested dependents in a flat structure

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#133]
In principle `flat` structures are not supposed to have internal modifiers.

This query matches some clear annotation issues:
http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=6042d5a6a386b

**Comment by nschneid** [comment]
I think an exception is necessary to allow words that are not first in a flat structure to have `punct` or `cc` dependents, as in:

- Winton "Red" Blount
- Francis & Anthony Bacon

**Comment by dan-zeman** [comment]
> In principle flat structures are not supposed to have internal modifiers.

I don't think so. Flat structures do not have a clear head. But a nominal member of a nominal flat structure can have its own adjectival modifier, why not? The only thing that really does not make sense (and I think the validator will not allow it, although I'm not sure) is if the dependent of a non-first member of a flat structure is again attached as `flat`. In that case it should have been attached directly to the first member.

This has been previously discussed in https://github.com/UniversalDependencies/docs/issues/543#issuecomment-381309398.

**Comment by jnivre** [comment]
I agree with Dan, and I think the previous discussion settles it. @nschneid Sorry that I did not remember this when we discussed the issue yesterday.

**Comment by nschneid** [comment]
Oh great. Thanks to @arademaker we have a Portuguese example in UniversalDependencies/docs#757. I'll take a crack at updating the guidelines and post in UniversalDependencies/docs#543.

**Comment by sylvainkahane** [comment]
@dan-zeman said " The only thing that really does not make sense (and I think the validator will not allow it, although I'm not sure) is if the dependent of a non-first member of a flat structure is again attached as flat."

i don't think so. Cf. discussion about Ludwig van Beethoven in #757. It is possible that a sequence A B C has an internal structure (A) (B C) and that both relations are flat.

**Comment by nschneid** [comment]
`flat` guidelines are now updated. (I don't agree with ALL the policies there but at least this issue of internal modifiers is resolved.)

Narrowing the above query down to examples with errors:

- http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=6044ec0fbe55c
