### ISSUE TITLE
Lemma consistency between EWT and GUM

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_English-EWT#137]
Is there any room to make the lemmas of JJR and RBS more consistent?  In EWT, for example, you get best -> best, cooler -> cooler, hotter -> hotter, whereas in GUM there is best -> good/well, hottest -> hot, etc.

**Comment by nschneid** [comment]
This is #119—thanks for the reminder. I think the GUM policy makes more sense. If anybody is willing to work on this and submit a pull request to the dev branch I can review it.

**Comment by AngledLuffa** [comment]
Oh, well, that's what I get for searching for JJR and/or RBS and glazing right past the same issue already posted.  Thanks for the update.
