### ISSUE TITLE
"I" has a lemma of "I" when used capitalized but "i" when it appeared lowercase

### ISSUE THREAD

**Issue by manning** [UniversalDependencies/UD_English-EWT#140]
At present "I" gets a lemma that depends on the case in which it appeared:

$ cut -f 3-4 en_ewt-ud-*.conllu | grep '^[Ii]\tPRON$' | sort | uniq -c
4611 I	PRON
 437 i	PRON

We should fix that!

**Comment by nschneid** [comment]
Yep, I agree it would be better to capitalize all of them. (Also noted in #131)

**Comment by nschneid** [comment]
fixed by #142
