### ISSUE TITLE
Missing MWT "Gotta"

### ISSUE THREAD

**Issue by kanayamah** [UniversalDependencies/UD_English-EWT#145]
"Gotta" should be represented as MWT as well as other appearances.

Current:
```
# sent_id = email-enronsent15_01-0038
# newpar id = email-enronsent15_01-p0009
# text = Gotta go for now.
1	Got	get	VERB	VBN	Tense=Past|VerbForm=Part	0	root	0:root	SpaceAfter=No
2	ta	to	PART	TO	Abbr=Yes	3	mark	3:mark	_
```

To be:
```
1-2	Gotta	_	_	_	_	_	_	_	_
1	Got	get	VERB	VBN	Tense=Past|VerbForm=Part	0	root	0:root	SpaceAfter=No
2	ta	to	PART	TO	Abbr=Yes	3	mark	3:mark	_
```

**Comment by amir-zeldes** [comment]
I should point out that currently only EWT (I think?) uses MWTs for English, and it does so in a rather different way than other datasets. I don't know anymore in what issue this was discussed, but essentially English MWTs only replicate the information in `SpaceAfter=No`, whereas I think the intended use of MWTs is to provide alternative or underlying forms of words. 

For example, this is what "won't" looks like in EWT:
```CoNLL-U
14-15	won't	_	_	_	_	_	_	_	_
14	wo	will	AUX	MD	VerbForm=Fin	16	aux	16:aux	_
15	n't	not	PART	RB	_	16	advmod	16:advmod	_
```

(Note that `SpaceAfter=No` is not used inside the MWT). I think the intended use of MWTs is to not have a word like "wo", which is not really English, and instead something like this could be done:

```CoNLL-U
14-15	won't	_	_	_	_	_	_	_	_
14	will	will	AUX	MD	VerbForm=Fin	16	aux	16:aux	_
15	not	not	PART	RB	_	16	advmod	16:advmod	_
```

And similarly we could have "ta" in "gotta" become "to" inside the MWT. But again, this is not the current state, and I wonder if it's worth the trouble: MWTs complicate things in various ways, and English corpora have lived with tokens like "wo" for a long time with few if any complaints. 

Unlike Romance languages where forms like French "au" (a + le) are not easily analyzable without MWTs, English trees gain little from doing this, but bring substantial overhead to processing scripts, evaluations and tools. 

So the questions I think are:
1. Do we want to do this to the English TBs?
2. If so, do we want to do `wo -> will` etc. etc.?
3. If we want to do any of this, can we make sure ALL English TBs do it? How?

Given the complications this brings, I am not super sure I want to say yes to 1...

**Comment by nschneid** [comment]
From the [guidelines](https://universaldependencies.org/u/overview/tokenization.html):

> However, it is important to note that the basic units of annotation are syntactic words (not phonological or orthographic words), which means that we systematically want to split off clitics, as in Spanish dámelo = da me lo, and undo contractions, as in French au = à le.

Basically I think the idea is that an orthographic word should have a unit in the annotation, and multiword tokens accomplish this when there are clitics. SpaceAfter=No then becomes specific to punctuation.

The advantage of implementing this for clitics/contractions in English is that it is then consistent with clitics/contractions in other languages.

The FORM field of the syntactic words then becomes subject to debate ("wo" vs. "will"). I think the UD standard only requires that the multiword token form match the word in the sentence, and doesn't specify how the individual FORMs should be decided. Maybe we should defer to language-specific tokenizer conventions, in which case keeping "wo" is sensible, provided it is properly lemmatized as "will".

Are there scripts that Stanford used to implement the MWTs for EWT, that other treebanks could use?

**Comment by dan-zeman** [comment]
Agreed that the universal guidelines do not prescribe what you should do in the FORM field of a node that is part of a MWT. But the German, French and Spanish examples that were repeated since MWTs were introduced in UD v1 at least suggest that the intention was to show the form that the syntactic word would take if it occurred in an orthographically independent position. In some situations in some languages, one cannot learn that just from the lemma.

**Comment by kanayamah** [comment]
I know there are a lot of discussion points in the MWT representation, but what I'm pointing out in this issue is just "Gotta" in the specific instance does not have the parent token, while all of the other appearance of "gotta" and "wanna" have.
I guess that it was overlooked in v2.7 update just because this "Gotta" was capitalized -- please make it consistent in v2.8!
