### ISSUE TITLE
Hyphen as SYM/SYM or PUNCT/:?

### ISSUE THREAD

**Issue by amir-zeldes** [UniversalDependencies/UD_English-EWT#146]
There are cases of hyphens tagged as xpos/upos SYM/SYM but also :/PUNCT as in:

http://match.grew.fr/?corpus=UD_English-EWT@2.7&custom=6078a0adc6d64
http://match.grew.fr/?corpus=UD_English-EWT@2.7&custom=6078a0bd4ba90

The latter type is the majority. I have no strong preference, but should we unify these somehow?

**Comment by amir-zeldes** [comment]
On second thought, if we want only one tag, then maybe SYM is better, since some hyphens are deprel=case, and we don't want udapi's FixPunct or something similar to mess with them or subject them to validation as punctuation, right?

**Comment by nschneid** [comment]
This seems to be a legitimate ambiguity: 

- where it acts as a punctuation dash, e.g. setting off a byline or parenthetical, I think PUNCT is correct
- where it acts as a range separator (which we currently parse as if it were *to*), I think SYM is reasonable though it's perhaps debatable
- where it acts as a minus sign, I think SYM is correct

**Comment by amir-zeldes** [comment]
OK, I can ensure that GUM will conform to that in 2.8
