### ISSUE TITLE
nominalized adjectival gerund

### ISSUE THREAD

**Issue by amir-zeldes** [UniversalDependencies/UD_English-EWT#150]
The construction "the following" (without a noun) has two analyses:

 1. "the" is the head, amod(the,following)
 2. "following" is the head, det(following, the)
 
http://match.grew.fr/?corpus=UD_English-EWT@2.7&custom=607c83928823e
http://match.grew.fr/?corpus=UD_English-EWT@2.7&custom=607c848d3825e
http://match.grew.fr/?corpus=UD_English-EWT@2.7&custom=607c84a4c517a

I prefer option 2, since I consider these to be nominalized adjectives (notwithstanding the gerundival origin), like "the poor", and this is also what GUM has. EWT follows the same practice here, e.g. "the Irish", "the bad":

http://match.grew.fr/?corpus=UD_English-EWT@2.7&custom=607c84499946d

**Comment by nschneid** [comment]
Option 1 is just bizarre.

I assume if there is a noun then "following" becomes amod? ("The following items")

**Comment by amir-zeldes** [comment]
yes - ok, so I will happily stick to 2 unless someone wants to fight for 1

**Comment by dan-zeman** [comment]
Option 2 conforms to [the guidelines](https://universaldependencies.org/u/overview/specific-syntax.html#ellipsis-in-nominals), which say that if the noun is elided and only `det` and `amod` remain, it is the `amod` what should be promoted.

**Comment by amir-zeldes** [comment]
Great, leaving this open as a reminder to fix it in EWT

**Comment by nschneid** [comment]
Queries on dev branch:

- [ ] http://universal.grew.fr/?custom=638e108f44323
- [ ] http://universal.grew.fr/?custom=638e10ac58df7
- [ ] http://universal.grew.fr/?custom=638e10c8e7259

8 tokens in all. Will fix.
