### ISSUE TITLE
Missing MWT for clitics

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#156]
It seems that the process for adding multiword tokens for clitics/contracted forms missed some cases, e.g. where the multiword form was not space-separated on both sides (due to punctuation or typos). These can be found by inspecting remaining `SpaceAfter=No` tokens.

$ cat en_ewt-ud-*.conllu | fgrep -A 1 'SpaceAfter=No' > spaceafterno.txt

Python:

```py
inF = open('spaceafterno.txt')
data = inF.read()
parts = data.split('\n--\n')
for part in parts:
    lns = part.splitlines()
    for ln,ln2 in zip(lns[:-1], lns[1:]):
       if all(x not in ln+ln2 for x in ['\tPUNCT\t', '\tSYM\t', '\tNUM\t', 'goeswith', 'CopyOf=']):
         print(part)
         print()
```

Approximately 142 of these involve a `PART` (clitic) and 210 do not.

As described [here](https://universaldependencies.org/u/overview/typos.html), wrongly merged words should have `SpaceAfter=No|CorrectSpaceAfter=Yes`. Multiword tokens, on the other hand, should not specify `SpaceAfter=No` in its component words, but if the token as a whole is not followed by a space, then `SpaceAfter=No` should be marked at the multiword level.

**Comment by nschneid** [comment]
The current MWTs were added in #100. @ethanachi do you have a script that we could modify for the remaining ones?

**Comment by ethanachi** [comment]
Yeah, I do have a script if that's helpful. I can upload it here by tomorrow...

**Comment by nschneid** [comment]
Thanks, that would be great!

**Comment by amir-zeldes** [comment]
If the script always results in MWTs that are just a concatenation of the included tokens, then I can apply it to GUM as well; please post a link to the code if you can!

**Comment by ethanachi** [comment]
Hi @amir-zeldes and @nschneid,

Here's a link to the code I used: https://github.com/ethanachi/ud-fix-multiwords

That said, there is actually something systematic that needs changing (@manning took care of this the last time I ran this script): The words internal to an MWT shouldn’t have `SpaceAfter=No`, but if there is no space after the whole MWT, then the MWT line should have `SpaceAfter=No`.

**Comment by nschneid** [comment]
What should the policy be for expressions like "B&W" (standing for black-and-white)? Should it be an MWT? (Note that "&" is tagged as CCONJ.)

I am assuming that words not separated by spaces due to numbers or symbols, e.g. "7g", "7%", "US$", are neither MWTs nor spelling errors.

**Comment by nschneid** [comment]
And what about multiple initials with periods, e.g. "R.E. Glenn"? The words are "R." and "E.". I guess that's neither an MWT nor a spelling error?

**Comment by nschneid** [comment]
I think I'm done unless there are objections to the above. Would appreciate if someone could take a sanity check look at #159.

**Comment by amir-zeldes** [comment]
Excellent work, thanks! I will add the mwts to GUM as well, though I don't think I will manage a CorrectSpaceAfter review in time, so that might be something for a future release.
