### ISSUE TITLE
validation errors ?

### ISSUE THREAD

**Issue by lapalme** [UniversalDependencies/UD_English-EWT#161]
As a recent user of UDs, after modifying  the dev version of EWT-training on my machine, I ran the UD validation script that I found at
   https://universaldependencies.org/release_checklist.html#validation

It  identified 82 validation errors (not on lines that I had modified), should all these be fixed ? I was under the impression that published UD files would not have any validation errors.

UD_English-EWT % python3 ../UD-tools/validate.py --lang=en --max-err=0  en_ewt-ud-train.conllu
[Line 5028 Sent weblog-juancole.com_juancole_20040708181175_ENG_20040708_181175-0038 Node 3]: [L3 Syntax rel-upos-mark] 'mark' should not be 'VERB'
[Line 21464 Sent weblog-blogspot.com_rigorousintuition_20060511134300_ENG_20060511_134300-0026 Node 19]: [L3 Syntax rel-upos-mark] 'mark' should not be 'VERB'
[Line 22675 Sent weblog-blogspot.com_rigorousintuition_20060511134300_ENG_20060511_134300-0072 Node 1]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'INTJ'
[Line 22873 Sent weblog-blogspot.com_rigorousintuition_20060511134300_ENG_20060511_134300-0084 Node 12]: [L3 Syntax rel-upos-det] 'det' should be 'DET' or 'PRON' but it is 'NUM'
[Line 22891 Sent weblog-blogspot.com_rigorousintuition_20060511134300_ENG_20060511_134300-0085 Node 5]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 31358 Sent weblog-blogspot.com_alaindewitt_20060924104100_ENG_20060924_104100-0159]: [L4 Morpho feature-upos-not-permitted] Feature Tense is not permitted with UPOS ADV in language [en].

The following 45 feature values are currently permitted in language [en]:
Abbr=Yes, Case=Acc, Case=Nom, Definite=Def, Definite=Ind, Degree=Cmp, Degree=Pos, Degree=Sup, Foreign=Yes, Gender=Fem, Gender=Masc, Gender=Neut, Mood=Imp, Mood=Ind, Mood=Sub, NumForm=Digit, NumForm=Roman, NumForm=Word, NumType=Card, NumType=Mult, NumType=Ord, Number=Plur, Number=Sing, Person=1, Person=2, Person=3, Polarity=Neg, Poss=Yes, PronType=Art, PronType=Dem, PronType=Ind, PronType=Int, PronType=Neg, PronType=Prs, PronType=Rel, PronType=Tot, Reflex=Yes, Tense=Past, Tense=Pres, Typo=Yes, VerbForm=Fin, VerbForm=Ger, VerbForm=Inf, VerbForm=Part, Voice=Pass
If a language needs a feature that is not documented in the universal guidelines, the feature must
have a language-specific documentation page in a prescribed format.
See https://universaldependencies.org/contributing_language_specific.html for further guidelines.
All features including universal must be specifically turned on for each language in which they are used.
See https://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/langspec/specify_feature.pl for details.

[Line 31358 Sent weblog-blogspot.com_alaindewitt_20060924104100_ENG_20060924_104100-0159]: [L4 Morpho feature-upos-not-permitted] Feature VerbForm is not permitted with UPOS ADV in language [en].
[Line 45607 Sent email-enronsent26_01-0011 Node 25]: [L3 Syntax rel-upos-nummod] 'nummod' should be 'NUM' but it is 'ADV'
[Line 46353 Sent email-enronsent26_01-0054 Node 1]: [L3 Syntax rel-upos-mark] 'mark' should not be 'VERB'
[Line 52686 Sent email-enronsent17_01-0041 Node 7]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'PROPN'
[Line 54239 Sent email-enronsent36_02-0050 Node 3]: [L5 Syntax cop-lemma] '=' is not a copula in language [en]
[Line 54373 Sent email-enronsent36_02-0057 Node 3]: [L5 Syntax cop-lemma] '=' is not a copula in language [en]
[Line 56911 Sent email-enronsent22_01-0034 Node 6]: [L3 Syntax rel-upos-nummod] 'nummod' should be 'NUM' but it is 'ADV'
[Line 58520 Sent email-enronsent11_01-0052]: [L4 Morpho feature-upos-not-permitted] Feature VerbForm is not permitted with UPOS X in language [en].
[Line 62942 Sent email-enronsent34_01-0028 Node 25]: [L3 Syntax rel-upos-nummod] 'nummod' should be 'NUM' but it is 'ADJ'
[Line 63840 Sent email-enronsent34_01-0075 Node 21]: [L3 Syntax rel-upos-aux] 'aux' should be 'AUX' but it is 'ADV'
[Line 66988 Sent email-enronsent13_01-0102 Node 6]: [L3 Syntax goeswith-nospace] 'goeswith' cannot connect nodes that are not separated by whitespace
[Line 67001 Sent email-enronsent13_01-0102 Node 19]: [L3 Syntax goeswith-nospace] 'goeswith' cannot connect nodes that are not separated by whitespace
[Line 67013 Sent email-enronsent13_01-0103 Node 2]: [L3 Syntax goeswith-nospace] 'goeswith' cannot connect nodes that are not separated by whitespace
[Line 67024 Sent email-enronsent13_01-0104 Node 2]: [L3 Syntax goeswith-nospace] 'goeswith' cannot connect nodes that are not separated by whitespace
[Line 70609 Sent email-enronsent16_01-0020 Node 24]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'X'
[Line 72087 Sent email-enronsent02_01-0005]: [L4 Morpho feature-upos-not-permitted] Feature Degree is not permitted with UPOS X in language [en].
[Line 74315 Sent email-enronsent31_01-0035]: [L4 Morpho feature-upos-not-permitted] Feature PronType is not permitted with UPOS X in language [en].
[Line 74427 Sent email-enronsent31_01-0039 Node 10]: [L3 Syntax rel-upos-mark] 'mark' should not be 'VERB'
[Line 78854 Sent email-enronsent14_01-0024 Node 2]: [L3 Syntax goeswith-nospace] 'goeswith' cannot connect nodes that are not separated by whitespace
[Line 116741 Sent newsgroup-groups.google.com_alt.animals.cat_01ff709c4bf2c60c_ENG_20040418_040100-0026 Node 8]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NUM'
[Line 117089 Sent newsgroup-groups.google.com_alt.animals.cat_01ff709c4bf2c60c_ENG_20040418_040100-0040]: [L4 Morpho feature-upos-not-permitted] Feature VerbForm is not permitted with UPOS X in language [en].
[Line 119465 Sent newsgroup-groups.google.com_alt.animals_02c2d614bfbf6b20_ENG_20050223_232900-0018 Node 26]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'SCONJ'
[Line 121675 Sent newsgroup-groups.google.com_alt.animals_0e65f540816d780c_ENG_20041116_124800-0042 Node 2]: [L3 Syntax rel-upos-mark] 'mark' should not be 'AUX'
[Line 127198 Sent newsgroup-groups.google.com_humanities.lit.authors.shakespeare_0018a7697318f71f_ENG_20031006_163200-0040 Node 8]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NUM'
[Line 127200 Sent newsgroup-groups.google.com_humanities.lit.authors.shakespeare_0018a7697318f71f_ENG_20031006_163200-0040 Node 10]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NUM'
[Line 127515 Sent newsgroup-groups.google.com_humanities.lit.authors.shakespeare_0018a7697318f71f_ENG_20031006_163200-0052 Node 3]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NUM'
[Line 127692 Sent newsgroup-groups.google.com_humanities.lit.authors.shakespeare_0018a7697318f71f_ENG_20031006_163200-0066 Node 4]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NUM'
[Line 135624 Sent newsgroup-groups.google.com_alt.animals_0084bdc731bfc8d8_ENG_20040905_212000-0018 Node 2]: [L5 Syntax cop-lemma] '=' is not a copula in language [en]
[Line 138283 Sent newsgroup-groups.google.com_alt.animals_0084bdc731bfc8d8_ENG_20040905_212000-0129 Node 11]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NUM'
[Line 138411 Sent newsgroup-groups.google.com_alt.animals_0084bdc731bfc8d8_ENG_20040905_212000-0134 Node 14]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NUM'
[Line 138447 Sent newsgroup-groups.google.com_alt.animals_0084bdc731bfc8d8_ENG_20040905_212000-0135 Node 27]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NUM'
[Line 142371 Sent answers-20111108083309AAg9jwT_ans-0009]: [L4 Morpho feature-upos-not-permitted] Feature Mood is not permitted with UPOS X in language [en].
[Line 142371 Sent answers-20111108083309AAg9jwT_ans-0009]: [L4 Morpho feature-upos-not-permitted] Feature VerbForm is not permitted with UPOS X in language [en].
[Line 144981 Sent answers-20111108102621AA3hPqj_ans-0005 Node 6]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'ADP'
[Line 147173 Sent answers-20111108100523AA1i7no_ans-0011 Node 16]: [L3 Syntax rel-upos-nummod] 'nummod' should be 'NUM' but it is 'DET'
[Line 151336 Sent answers-20111108094831AAnOjgr_ans-0014 Node 7]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'PRON'
[Line 152690 Sent answers-20111108103211AA4XhnU_ans-0018 Node 13]: [L3 Syntax rel-upos-det] 'det' should be 'DET' or 'PRON' but it is 'NUM'
[Line 153302 Sent answers-20111108080049AAgT0iA_ans-0011 Node 10]: [L3 Syntax rel-upos-aux] 'aux' should be 'AUX' but it is 'VERB'
[Line 155118 Sent answers-20111108105919AAHXkZF_ans-0015 Node 15]: [L3 Syntax rel-upos-mark] 'mark' should not be 'VERB'
[Line 161463 Sent answers-20111108105029AARU1Lf_ans-0010 Node 23]: [L3 Syntax rel-upos-det] 'det' should be 'DET' or 'PRON' but it is 'ADP'
[Line 169710 Sent answers-20111108091938AAmE8Tv_ans-0008]: [L4 Morpho feature-upos-not-permitted] Feature PronType is not permitted with UPOS X in language [en].
[Line 173116 Sent answers-20111108092321AAK0Eqp_ans-0025 Node 7]: [L3 Syntax rel-upos-mark] 'mark' should not be 'VERB'
[Line 173221 Sent answers-20111108092321AAK0Eqp_ans-0029 Node 15]: [L3 Syntax rel-upos-mark] 'mark' should not be 'VERB'
[Line 176521 Sent answers-20111107094641AATmyb6_ans-0033 Node 33]: [L3 Syntax rel-upos-nummod] 'nummod' should be 'NUM' but it is 'ADJ'
[Line 176575 Sent answers-20111107094641AATmyb6_ans-0036]: [L4 Morpho feature-upos-not-permitted] Feature PronType is not permitted with UPOS X in language [en].
[Line 176573 Sent answers-20111107094641AATmyb6_ans-0036 Node 5]: [L3 Syntax goeswith-nospace] 'goeswith' cannot connect nodes that are not separated by whitespace
[Line 177800 Sent answers-20111108111312AAq4ETn_ans-0021 Node 14]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NUM'
[Line 179520 Sent answers-20111107211742AAHZaPe_ans-0028]: [L4 Morpho feature-upos-not-permitted] Feature Degree is not permitted with UPOS X in language [en].
[Line 180405 Sent answers-20111108105629AAiZUDY_ans-0016 Node 21]: [L3 Syntax rel-upos-nummod] 'nummod' should be 'NUM' but it is 'ADV'
[Line 180875 Sent answers-20111108105629AAiZUDY_ans-0040 Node 17]: [L3 Syntax rel-upos-aux] 'aux' should be 'AUX' but it is 'VERB'
[Line 183429 Sent answers-20111108110012AAK8Azy_ans-0019 Node 36]: [L3 Syntax rel-upos-mark] 'mark' should not be 'VERB'
[Line 184159 Sent answers-20111108092643AAXe4lD_ans-0011]: [L4 Morpho feature-upos-not-permitted] Feature Degree is not permitted with UPOS X in language [en].
[Line 184260 Sent answers-20111108092643AAXe4lD_ans-0018 Node 5]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'SCONJ'
[Line 191689 Sent answers-20111108104724AAuBUR7_ans-0032 Node 11]: [L3 Syntax goeswith-nospace] 'goeswith' cannot connect nodes that are not separated by whitespace
[Line 193402 Sent reviews-029218-0004]: [L4 Morpho feature-upos-not-permitted] Feature Degree is not permitted with UPOS X in language [en].
[Line 193759 Sent reviews-341397-0002 Node 10]: [L3 Syntax rel-upos-nummod] 'nummod' should be 'NUM' but it is 'DET'
[Line 194110 Sent reviews-325292-0005 Node 12]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'VERB'
[Line 196932 Sent reviews-348369-0007]: [L4 Morpho feature-upos-not-permitted] Feature Mood is not permitted with UPOS X in language [en].
[Line 196932 Sent reviews-348369-0007]: [L4 Morpho feature-upos-not-permitted] Feature VerbForm is not permitted with UPOS X in language [en].
[Line 200569 Sent reviews-029230-0005]: [L4 Morpho feature-upos-not-permitted] Feature PronType is not permitted with UPOS X in language [en].
[Line 201652 Sent reviews-388799-0001 Node 2]: [L3 Syntax rel-upos-det] 'det' should be 'DET' or 'PRON' but it is 'ADJ'
[Line 206398 Sent reviews-200957-0003 Node 15]: [L3 Syntax rel-upos-nummod] 'nummod' should be 'NUM' but it is 'ADJ'
[Line 210076 Sent reviews-042012-0006 Node 3]: [L3 Syntax goeswith-nospace] 'goeswith' cannot connect nodes that are not separated by whitespace
[Line 216861 Sent reviews-365154-0010 Node 12]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 218196 Sent reviews-317846-0004 Node 25]: [L3 Syntax rel-upos-nummod] 'nummod' should be 'NUM' but it is 'ADJ'
[Line 221443 Sent reviews-247226-0002]: [L4 Morpho feature-upos-not-permitted] Feature Degree is not permitted with UPOS X in language [en].
[Line 221516 Sent reviews-247226-0006]: [L4 Morpho feature-upos-not-permitted] Feature Degree is not permitted with UPOS X in language [en].
[Line 221543 Sent reviews-247226-0008]: [L4 Morpho feature-upos-not-permitted] Feature Degree is not permitted with UPOS X in language [en].
[Line 222201 Sent reviews-190256-0005 Node 8]: [L3 Syntax rel-upos-nummod] 'nummod' should be 'NUM' but it is 'DET'
[Line 226912 Sent reviews-055207-0004 Node 35]: [L3 Syntax rel-upos-nummod] 'nummod' should be 'NUM' but it is 'ADV'
[Line 229876 Sent reviews-283041-0003]: [L4 Morpho feature-upos-not-permitted] Feature VerbForm is not permitted with UPOS X in language [en].
[Line 231262 Sent reviews-361545-0004 Node 14]: [L3 Syntax rel-upos-nummod] 'nummod' should be 'NUM' but it is 'DET'
[Line 238766 Sent reviews-117115-0012 Node 16]: [L3 Syntax rel-upos-det] 'det' should be 'DET' or 'PRON' but it is 'ADJ'
[Line 238770 Sent reviews-117115-0012 Node 20]: [L3 Syntax rel-upos-det] 'det' should be 'DET' or 'PRON' but it is 'ADJ'
[Line 239810 Sent reviews-086839-0005 Node 15]: [L3 Syntax rel-upos-nummod] 'nummod' should be 'NUM' but it is 'DET'
[Line 245927 Sent reviews-053248-0010 Node 8]: [L3 Syntax punct-causes-nonproj] Punctuation must not cause non-projectivity of nodes [7]
Morpho errors: 20
Syntax errors: 62
*** FAILED *** with 82 errors

**Comment by jnivre** [comment]
It may seem strange that a released treebank may contain validation errors, so let me explain how this can happen. We are constantly working on the validation process by adding more and more tests, and treebank providers sometimes have a hard time to keep up with the changes. To prevent previously released treebanks from becoming unavailable in later releases, we therefore have a so-called legacy exception, which says that if a treebank was once released without validation errors then it can be included in later releases even if it contains errors that (only) result from new tests added to the validation script. (New treebanks, by contrast, have to be error-free before being released the first time.) English-EWT currently belongs to the legacy group, but the hope is that all these things will be fixed in future releases.

**Comment by nschneid** [comment]
We welcome suggestions on how to resolve these errors. :) Many are special cases that will require discussion.

**Comment by dan-zeman** [comment]
There is one error type (three instances) that needs to be resolved now because it was not there at the time of release 2.7 (that is, it must have been introduced during the recent updates), and it prevents the data from being released in 2.8:

<pre>[L5 Syntax cop-lemma] '=' is not a copula in language [en]</pre>

Despite the fact that _=_ obviously has the required equational meaning, the symbol is not treated as a copula in any UD language.

**Comment by nschneid** [comment]
E.g. https://github.com/UniversalDependencies/UD_English-EWT/commit/82150e5789e07c03c7d318007588e52f42fd9a9c#diff-1709178a5470dfff4b1141b2c662ebc9e514079d75a6fe01976487a60ce67807R665

This is in a mathematical equation. Would it be best to interpret it as notation for the verb "equals"? Or is there a convention for special notation that has structure but doesn't follow normal linguistic syntax?

**Comment by nschneid** [comment]
If I had to hastily propose a solution it would be `flat:notation`, to signal that words (including symbols) go together in some way that may have structure but lacks *linguistic* structure. `list` and `parataxis` don't seem right. I guess we could default to `dep` but I don't love that because it's not that the structure is unclear, it's that it's special.

**Comment by amir-zeldes** [comment]
I would suggest avoiding new and extremely rare deprels. We got the same warning about = as cop in GUM and just reanalyzed it as a case of "equals" (so with xcomp argument, but with POS SYM). GUM dev branch has been updated if you want to compare

**Comment by nschneid** [comment]
Fair enough. Fixed this particular issue in c617146.

**Comment by dan-zeman** [comment]
Great, thanks! EWT is now [back to LEGACY status](http://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/validation-report.pl), and with a bunch of legacy exceptions now made obsolete. Good job :-)
