### ISSUE TITLE
Three analyses for "half a"

### ISSUE THREAD

**Issue by amir-zeldes** [UniversalDependencies/UD_English-EWT#162]
http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=6089a32c79f60

Given the unanimous and precedented xpos tag PDT, I would go with deprel `det:predet`, but there is also `compound` and `nummod`. I'm making GUM follow `det:predet` unless I hear objections?

**Comment by amir-zeldes** [comment]
Exception: for "a half gallon" I am going with nummod(gallon, half) and det(half, a)

**Comment by nschneid** [comment]
Sounds reasonable. This is relevant to the validation error `[L3 Syntax rel-upos-nummod] 'nummod' should be 'NUM' but it is 'DET'`. We can tag "half" as `DET` when it's a predeterminer and as `NUM` in "half gallon" etc.
