### ISSUE TITLE
PROPN should be reserved for true nouns, even in names

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#164]
Per the discussion in UniversalDependencies/docs#777 and elsewhere, we want to leave legacy PTB `NNP` tags in the xpos column but change `PROPN` to `ADJ`, `VERB`, `ADV`, etc. And the deprel should be changed accordingly from `compound` to `amod` or `advmod`.

I've created wordlists based on heuristics gathered from non-names in the full corpus. (Also tweaked the lists based on @amir-zeldes's model output discussed at #153.) These will be used to revise PROPN-compound-modifiers-of-PROPNs.

Note that I am not modifying the head PROPN, though there may be occasional names headed by something other than a noun.

I will try to get this done in the next 9 hours before the data freeze. :)

**Comment by nschneid** [comment]
Under the current script, 1509 modifier types will remain PROPN. I skimmed through them and didn't see obvious non-nouns.

For now I am leaving bare cardinal directions ("North" etc.) as PROPN and only changing to ADJ those with derivational morphology ("Northern" etc.). But I am not sure they shouldn't all be considered ADJs.

Tokens to be modified:

## ADV

Just/R Autos/N
Just/R Family/N

## VERB

Applied/V Semantics/N
Breaking/V News/N
Deemed/V ISDA/N
Deemed/V ISDAs/N
Demented/V World/N
Flying/V Squirrels/N
Governing/V Council/N
Rolling/V Stone/N
Rolling/V Stones/N
baked/V snake/N

## Comparative ADJ

Greater/C Noida/N
Greater/C Orleans/N
Higher/C Education/N
greater/C noida/N

(I found one token of a superlative adjective, Best Buy, which I tagged manually.)

## Ordinal ADJ

10th/O Sts./N
14th/O street/N
21st/O St/N
55th/O Brigade/N
First/O Glass/N
First/O Union/N
Fourth/O Rail/N
Second/O Home/N
Third/O Reich/N
second/O war/N

## Regular ADJ (371 types)

ALTERNATIVE/A CURES/N
Advanced/A parts/N
Advisory/A Board/N
African/A Union/N
Alaskan/A Knight/N
American/A Association/N
American/A Conservative/N
American/A Express/N
American/A Pride/N
American/A Samoa/N
Arab/A league/N
Arabian/A peninsula/N
Arakan/A Army/N
Arctic/A Circle/N
Arctic/A Climate/N
Arctic/A Ocean/N
Aryan/A Nations/N
Asian/A Times/N
Associated/A Press/N
Atomic/A Energy/N
Atomic/A Radiation/N
BASIC/A ALLOWANCE/N
BIG/A BOWL/N
Ba'athists/A Wahhabis/N
Bad/A Wolf/N
Basic/A Allowance/N
Bella/A Italia/N
Big/A D/N
Big/A Mac/N
Big/A Wolf/N
Black/A Hawk/N
Blue/A Book/N
Blue/A Cross/N
Blue/A Planet/N
Blue/A Shield/N
Blue/A Water/N
Blue/A cross/N
Botanical/A Gardens/N
Bright/A Futures/N
Bright/A Star/N
British/A Columbia/N
British/A Museum/N
CRAZY/A HORSE/N
Canadian/A Conference/N
Canadian/A Immigration/N
Canadian/A Outback/N
Caribbean/A Mariner/N
Central/A Agency/N
Central/A Intelligence/N
Central/A Time/N
Cheap/A Hotel/N
Chemical/A Wire/N
Chinese/A Restaurant/N
Christian/A Identity/N
Christian/A Soldiers/N
Civic/A Center/N
Civil/A Defence/N
Clean/A Act/N
Clear/A Skies/N
Cognitive/A Science/N
Cold/A War/N
Communist/A party/N
Comprehensive/A Treaty/N
Contemporary/A Art/N
Creative/A Workshop/N
Criminal/A Court/N
Czech/A Republic/N
DAILY/A STAR/N
Daily/A E-mail/N
Daily/A Star/N
Dark/A Ages/N
Degenerate/A Art/N
Democratic/A Committee/N
Democratic/A Party/N
Dental/A Clinic/N
Dental/A Practice/N
Diagnostic/A Lab/N
Disposable/A Patriot/N
Dumb/A Friends/N
Eastern/A Time/N
Economic/A Cooperation/N
Egyptian/A Jihad/N
Egyptian/A al/N
Electoral/A Commission/N
Electronic/A Conference/N
Elite/A Flyers/N
Environmental/A Protection/N
European/A Union/N
Executive/A Director/N
Executive/A Order/N
Executive/A Theory/N
Expeditionary/A Force/N
Express/A Road/N
Extreme/A Surfs/N
Fair/A City/N
Fair/A Housing/N
Fancy/A Flowers/N
Far/A East/N
Federal/A Commission/N
Federal/A District/N
Federal/A Government/N
Federal/A Reporters/N
Federal/A Reserve/N
Ferrous/A International/N
Financial/A Group/N
Fine/A Art/N
Fine/A Arts/N
Finest/A Donair/N
Flat/A Top/N
Foreign/A Minister/N
Fresh/A Design/N
Fundamentalist/A Saints/N
GREEN/A BAY/N
Gay/A Village/N
General/A Assembly/N
General/A Barno/N
General/A Colin/N
General/A Fahim/N
General/A Fiasco/N
General/A Kofi/N
General/A Motors/N
General/A Nirmal/N
General/A Pervez/N
General/A Vo/N
Gentle/A Dentistry/N
German/A Peasant/N
Global/A Attitudes/N
Global/A Change/N
Global/A Climate/N
Global/A Counterparty/N
Global/A Operations/N
Good/A Friday/N
Grand/A Ayatollah/N
Grand/A Cayman/N
Grand/A Hotel/N
Grand/A Hyatt/N
Grand/A Turk/N
Gray/A St./N
Great/A Britain/N
Great/A Depression/N
Green/A Agreement/N
Green/A Buffet/N
Green/A Medicine/N
Hidden/A Nook/N
High/A Commission/N
High/A School/N
High/A Wycombe/N
Holy/A Land/N
Holy/A Spirit/N
Holy/A War/N
Hot/A Iron/N
Human/A Rights/N
INDUSTRIAL/A LTD./N
Independent/A Operator/N
Independent/A Producers/N
Indian/A Building/N
Indian/A Congress/N
Indian/A II/N
Indian/A Review/N
Industrial/A Engineering/N
Internal/A Service/N
International/A Agency/N
International/A Board/N
International/A Council/N
International/A Court/N
International/A Fund/N
International/A Network/N
International/A Station/N
International/A airport/N
Iranian/A Guards/N
Iraqi/A Alliance/N
Iraqi/A Coalition/N
Iraqi/A Congress/N
Iraqi/A Party/N
Iraqi/A party/N
Islamic/A Combatant/N
Islamic/A Group/N
Islamic/A Jihad/N
Islamic/A Liberation/N
Islamic/A Party/N
Islamic/A Revolution/N
Islamic/A party/N
Islamic/A republic/N
Israeli/A Forces/N
Italian/A Renaissance/N
Joint/A Chiefs/N
Last/A Supper/N
Latter/A Day/N
Legal/A Framework/N
Legit/A Gaming/N
Like/A Family/N
Little/A Brown/N
Little/A Farmer/N
Little/A Pigs/N
Lone/A Ranger/N
Lonely/A Japan/N
Lonely/A Planet/N
Long/A Beach/N
Long/A V/N
Looking/A Glass/N
Loose/A Change/N
Lovely/A Nails/N
Lucky/A Panda/N
Lunar/A Inc./N
Lunar/A Transporatation/N
MAIN/A STREET/N
Mathematical/A Intelligencer/N
Medical/A Brigade/N
Medical/A Center/N
Medical/A Lab/N
Medical/A Spa/N
Methodist/A System/N
Middle/A Ages/N
Middle/A East/N
Middle/A Nicobar/N
Middle/A Office/N
Military/A Road/N
Mini/A Cooper/N
Mobile/A Phone/N
Moral/A Obligation/N
Muslim/A N/N
Muslim/A Scholars/N
NEW/A DELHI/N
National/A Academy/N
National/A Administration/N
National/A Agency/N
National/A Alliance/N
National/A Assembly/N
National/A Bank/N
National/A Center/N
National/A Committee/N
National/A Congress/N
National/A Corporation/N
National/A Endowment/N
National/A Enquirer/N
National/A Furnishings/N
National/A Guard/N
National/A League/N
National/A Marketing/N
National/A Park/N
National/A Party/N
National/A Radio/N
National/A Review/N
National/A Security/N
National/A Socialists/N
Nationwide/A Ltd/N
Natural/A Disasters/N
Natural/A Gas/N
Naval/A College/N
Naval/A Command/N
Naval/A Intelligence/N
New/A China/N
New/A Delhi/N
New/A England/N
New/A Hampshire/N
New/A Haven/N
New/A Jersey/N
New/A Orleans/N
New/A Providence/N
New/A Scientist/N
New/A Year/N
New/A York/N
New/A Yorker/N
New/A Zealand/N
New/A Zealander/N
Noble/A school/N
Nordic/A power/N
Northern/A Alliance/N
Northern/A Ireland/N
ONLINE/A 2/N
Orange/A Order/N
Other/A Problem/N
Palestinian/A Authority/N
Palestinian/A territories/N
Personal/A Allowance/N
Poisonous/A Letter/N
Presidential/A Library/N
Presidential/A Palace/N
Prime/A Minister/N
Prime/A Rib/N
Professional/A School/N
Prominent/A Builders/N
Provisional/A Authority/N
Prudential/A Realty/N
Public/A Radio/N
Purple/A Goose/N
RELIGIOUS/A COALITION/N
Random/A House/N
Raw/A Story/N
Real/A Time/N
Red/A Blount/N
Red/A Cross/N
Red/A FM/N
Red/A Hood/N
Red/A River/N
Red/A Robin/N
Regulatory/A Commission/N
Religious/A Coalition/N
Renewable/A Energy/N
Republican/A Committee/N
Republican/A Guard/N
Republican/A Party/N
Republican/A Red/N
Republican/A Right/N
Revolutionary/A Guards/N
Revolutionary/A People/N
Rocky/A Lange/N
Rocky/A Mountains/N
Rough/A Guide/N
Royal/A Caribbean/N
Russian/A Federation/N
Sacred/A Space/N
Saudi/A Arabia/N
Scientific/A Committee/N
Select/A Energy/N
Senior/A Presentation/N
Short/A Pump/N
Silent/A Spinner/N
Skilled/A Worker/N
Social/A Insurance/N
Southern/A Cone/N
Southern/A Law/N
Stony/A Point/N
Super/A 8/N
Super/A Wheel/N
Superior/A Court/N
Supreme/A Council/N
Supreme/A Court/N
Tamil/A Alliance/N
Tamil/A Eelam/N
Tamil/A Nadu/N
Tamil/A Tigers/N
Top/A Grill/N
Transcendental/A Meditation/N
Transformational/A Space/N
Trivial/A Pursuit/N
UNITED/A PRESS/N
UNITED/A WAY/N
Unconfirmed/A Sources/N
Unitary/A Executive/N
United/A Alliance/N
United/A Cleaning/N
United/A Coalition/N
United/A Duct/N
United/A Guilds/N
United/A India/N
United/A Italy/N
United/A Kingdom/N
United/A Nations/N
United/A States/N
United/A Way/N
Upper/A Egypt/N
Urban/A Development/N
Veterinary/A Lab/N
WHITE/A CASTLE/N
Western/A Addition/N
Western/A World/N
White/A House/N
Whole/A Foods/N
Wild/A Card/N
Zionist/A Organization/N
big/A mac/N
crazy/A horse/N
english/A rushi/N
hot/A topic/N
prime/A ribs/N
red/A sox/N
royal/A caribbean/N
scrummy/A yummy/N
united/A states/N
white/A castle/N

**Comment by nschneid** [comment]
Fun case that I think is ambiguous: Orange/PROPN County vs. Orange/ADJ Order

**Comment by amir-zeldes** [comment]
What are you doing about the lemma for the adjective or verb cases? Upper case of the adj/verb or same as form?

**Comment by nschneid** [comment]
Oh right. As noted in #131 a lot of PROPNs remain uncapitalized. But probably the ideal thing would be to capitalize lemmas that are part of a name, so I think I'll do that for the words being retagged here.

And I have to remember to use the base form of VERBs.

**Comment by nschneid** [comment]
...and for consistency capitalize the head nouns whose modifier is retagged.

There could be an occasional PROPN that is legitimately all-lowercase, but I don't think that applies to any of the above items.

**Comment by amir-zeldes** [comment]
I'm a little torn about lemmatizing to verb form. Doing it creates inconsistency between corpora tagged and lemmatized in UD vs. corpora that only have xpos. Not doing it means having a VERB (with gerund/participle morphology?) lemmatized to an inflected form...

**Comment by amir-zeldes** [comment]
Plus a common sanity check is that unique form+POS combinations should have a single lemma. here we are creating a situation where that isn't true: some upper case VERB forms will have lower case lemma and some will have upper case lemma, when the only distinction is due to xpos. And since this is an open class, we can't even list all the form+POS combos that are expected to have multiple lemmas.

**Comment by nschneid** [comment]
Hmm. That sounds like an argument to use a lowercase lemma for pretty much everything that's not a PROPN or demonym. E.g. "new York" and "rolling Stone" (or "rolling stone"?).

I think we agree that inflectional morphology should be stripped for all VERBs.

**Comment by nschneid** [comment]
Re: verb lemmas, I think we have to respect the morphology of the UPOS (also for features). If we're not going to let XPOS dictate the UPOS it shouldn't dictate the morphology in the lemma/features.

**Comment by amir-zeldes** [comment]
New for New York is less problematic because NNP+New will always lemmatize to New. But for verbs, if United is the head, it's NNP PROPN United, but if it's a modifier it's NNP VERB Unite, and if it's not a proper noun, VBN VERB unite...

**Comment by amir-zeldes** [comment]
BTW I think stanza only uses form + upos to predict lemmas, not xpos

**Comment by nschneid** [comment]
I guess I don't see why xpos should be relevant to UD lemmatization.

In principle if "United" is the head of the name I think it ought to be VERB. E.g. "United Against Hate", with UPOS=VERB and ExtPos=PROPN. But I'm assuming those are rare and tricky cases to be dealt with later.

**Comment by nschneid** [comment]
You know what, lemma capitalization will be annoying and inconsistent anyway until we go through all PROPNs. If I always capitalize for just the two words at issue it'll result in things like "Second/ADJ world/PROPN War/PROPN".

I think for now I'll leave the lemmas alone except for removing suffixes from verbs and comparative adjectives.

**Comment by nschneid** [comment]
For posterity, the script is at https://github.com/nschneid/ud-fix-multiwords/blob/main/fix_name_poses.py

**Comment by amir-zeldes** [comment]
> I guess I don't see why xpos should be relevant to UD lemmatization.

Because it should be possible to lemmatize English corpora the same way as EWT, GUM & co. even in corpora that don't use UPOS.

**Comment by amir-zeldes** [comment]
> In principle if "United" is the head of the name I think it ought to be VERB, and lemmatized like a verb. E.g. "United Against Hate", with UPOS=VERB and ExtPos=PROPN

I agree these are rare, so it's not a big deal, but I would expect the head to be analyzed based on its external role, by the same criterion as free relatives. So it "United" is nsubj to some matrix verb, it should be NNP + PROPN + nsubj, and only its internal dependents will get tagged based on the (nominalized) subordinate clause's argument structure.

**Comment by amir-zeldes** [comment]
> I think for now I'll leave the lemmas alone except for removing suffixes from verbs and comparative adjectives.

OK, so we're saying lemmas for non-PROPN NNPs will remain uppercase, but if they are VERB/ADJ they get uppercase base form? I guess this is OK from my perspective because we still get unique lemmas for unique POS combos, so NNP+United would presumably result in "Unite" in 99% of cases (except for the odd ones where it is the head). I can apply this and report how many non-unique lemmas this generates in GUM, if any...

**Comment by nschneid** [comment]
Yep literally chopping off the suffixes:

https://github.com/nschneid/ud-fix-multiwords/blob/main/fix_name_poses.py#L153-L161

https://github.com/nschneid/ud-fix-multiwords/blob/main/fix_name_poses.py#L139-L141

**Comment by nschneid** [comment]
> Fun case that I think is ambiguous: Orange/PROPN County vs. Orange/ADJ Order

Another ambiguous case: General/PROPN (as in Secretary General) vs. General/ADJ (as in General Assembly)

**Comment by nschneid** [comment]
> > Fun case that I think is ambiguous: Orange/PROPN County vs. Orange/ADJ Order
> 
> Another ambiguous case: General/PROPN (as in Secretary General) vs. General/ADJ (as in General Assembly)

Aargh I realized it is pluralized as secretaries-general, so "General" is a postmodifying ADJ! Same as "attorney general" and "surgeon general".
