### ISSUE TITLE
nummod dependent should be NUM

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#169]
Many non-`NUM`s attach as `nummod`:
http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=608f0daf136ac&clustering=N.upos

Refer to the [NumType](https://universaldependencies.org/u/feat/NumType.html) feature values as well.

**Comment by nschneid** [comment]
Some of these are improperly handled coordinations like "for a dollar or less", "by 4:45 or so"—cf. UniversalDependencies/docs#785

**Comment by amir-zeldes** [comment]
These all look wrong to me. Regarding cases like "February 3rd" you know my opinion: it's not just the deprel that's wrong, the number is also not a modifier but rather the head...

**Comment by nschneid** [comment]
I know your opinion but will make those consistent with dates in the rest of EWT for now.

What do you think about letters standing as sequential labels, e.g. "clause (e)"? Does GUM have a policy for that?

**Comment by amir-zeldes** [comment]
Yes, we consistently attach those as `dep` (example 5, chapter 10, Figure 1...). We used to do these as `flat` (basically, clause e is the name of the clause), but then we ran into things like "Chapters 5-10" and changed it to `dep` to allow for internal structure in the number part.

**Comment by nschneid** [comment]
There are still some `nummod`s where the dependent is `NOUN`, but the validator doesn't complain about those.

Month-date relations are currently `nummod`, and when the date is expressed as an ordinal ("July 3rd") it is tagged as `NOUN` (#175). This policy for month-date relations may change. These are easy to identify by checking the lemma for the name of a month.
