### ISSUE TITLE
25 instances of relativizer/complementizer "that" tagged as ADV

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#173]
http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=60a9736f54f4d&clustering=N.upos

These are errors, right—tag should be SCONJ?

Are these all even relative clauses meriting `acl:relcl`, or are some complement clauses that should be `acl`?

The `PronType` appears to be wrong on some of these.

In GUM the ADV instances of "that" all appear correct (for the degree modifier use, as in "not that tall").

**Comment by nschneid** [comment]
Here are the 25 instances categorized:

left_context | pivot | right_context | category | N head
-- | -- | -- | -- | --
That was the day | that | GOD'S CURSE fell upon the world of Rock. | N complement | day
68 - Number of days after taking office | that | Bush decided Not to ratify the Kyoto Protocol, the international treaty to reduce greenhouse gases by roughly 5.2 per cent below 1990 levels by 2012. | N complement | days
53 - Number of days after taking office | that | Bush reneged on his campaign promise to regulate carbon dioxide emissions from power plants. | N complement | days
2.5 - Number of hours after Rumsfeld learnt that Osama bin Laden was a suspect in the 11 September attacks | that | he brought up reasons to "hit" Iraq. | N complement | hours
0 - Number of minutes | that | President Bush, Vice-President Dick Cheney, the Defence Secretary, Donald Rumsfeld, the assistant Defence Secretary, Paul Wolfowitz, the former chairman of the Defence Policy Board, Richard Perle, and the White House Chief of Staff, Karl Rove - the main proponents of the war in Iraq -served in combat (combined). | N complement | minutes
6 - Number of months before 11 September | that | Cheney's Energy Task Force investigated Iraq's oil reserves. | N complement | months
I don't believe that we are quite at the point | that | we can say that all business controllers worldwide have reviewed, understand and have implemented these standards. | N complement | point
The two developments, he said, could eventually enable China's space program to mature to the point | that | experts could assemble and launch from Earth's orbit a spacecraft capable of circling the moon with astronauts and returning home. | N complement | point
That rejection got to the point | that | George Harrison kicked Yoko Ono in the Apple studios during the filming of Let it Be. | N complement | point
Their chauvinisms got to the point | that | even they themselves hated each other. | N complement | point
‘’It was the first time | that | Bush totally focused on the Taliban threat rather than Al Qaeda with the Pakistanis,’’ says a Western diplomat. | N complement | time
It marks the first time in recent years | that | China has promised to wield its veto power in the UN Security Council against a petition initiated by the United States and backed by France and Great Britain. | N complement | time
73 - Number of times | that | Bush mentioned terrorism or terrorists in his three State of the Union addresses. | N complement | times
Both have shared this country for the last 14 centuries and there is no possible way | that | one can live without the other. | N complement | way
In the same way | that | no country has a law against cannibals eating its prime minister, because such an act is unthinkable, international law does not address killers shooting from hospitals, mosques and ambulances, while being protected by their Government or society. | N complement | way
On the other hand, a certain transition democracy, as in Jordan, may be a better temporary solution, paving the way for the real thing, perhaps in the same way | that | an immediate sudden democracy did not work in Russia and would not have worked in China. | N complement | way
Therefore, any trade mark registration that incorporates the word ONLINE as a suffix in the way | that | you use it will not enable its owner to prevent others from using the word ONLINE. | N complement | way
We also liked the way | that | Ray checked on the job everyday. | N complement | way
We were all American citizens and there was no way | that | anybody helped us. | N complement | way
1972 - Year | that | Bush walked away from his pilot duties in the Texas National Guard, Nearly two years before his six-year obligation was up. | N complement | year
2000 - Year | that | Cheney said his policy as CEO of Halliburton oil services company was "we wouldn't do anything in Iraq". | N complement | year
Unfortunately for them, the general has decided to take seriously Colin Powell's frequent boasts that it was on his nudging | that | the Indians made conciliatory gestures toward Islamabad. | should be expl/nsubj | &nbsp;
It was as part of that surveillance in early 2001 | that | Jafar the Pilot studied tourist helicopters in the NYC area. | should be expl/nsubj | &nbsp;
If something happens | that | I'm not able to participate I'll let you know. | ~ so that | &nbsp;
Anyway, so that was 2 days ago | that | I called and left a message, but he still hasn't called back yet. | first “that” = expl? | &nbsp;


@amir-zeldes For the N complement ones, I assume `acl:relcl` is incorrect. Should it be `acl` or `advcl`?

And any thoughts on the last 2 in the table?

**Comment by amir-zeldes** [comment]
It's a bit complicated: for relative-like cases, where "that" does not substitute an argument of the relative predicate but does introduce an adnominal modifier clause (not an argument clause), we have used `acl:relcl` + `mark`, tagging "that" as IN/SCONJ, for example:

ways that in-group / out-group biases emerged

So here "that" is like "in which", so it's basically a relative clause, but "that" is not WDT, since it does not fill a role for the verb ("emerged").

For the last two: the last one is almost like expletive "it" with `csubj` - "that I called and left a message was 2 days ago", but I don't know if we want to allow the first "that" as `expl`... 

The penultimate one is hard to replace with an oblique WDT, so I'm a bit torn about it. You could treat "that" as an adverbial pronoun and give it a free relative analysis: basically it's "such that", but the matrix part "such" is missing, so you have "that" doing double duty, in which case it should get its matrix clause dependency (ADV/RB/advmod) + acl:relcl for the free relative. But I admit it's maybe a bit avantgarde.

**Comment by nschneid** [comment]
> It's a bit complicated: for relative-like cases, where "that" does not substitute an argument of the relative predicate but does introduce an adnominal modifier clause (not an argument clause), we have used `acl:relcl` + `mark`, tagging "that" as IN/SCONJ, for example:
> 
> ways that in-group / out-group biases emerged
> 
> So here "that" is like "in which", so it's basically a relative clause, but "that" is not WDT, since it does not fill a role for the verb ("emerged").

So TBC you'd do `acl:relcl` for all my "N complement" examples above? (I used the word "complement" because the noun seems to license this construction—e.g. locatives don't work as well: _This is the city *that/in which I visited my sister last May_—but I agree the terminology is fuzzy.)

**Comment by amir-zeldes** [comment]
That's right, I wouldn't consider them complements in the same was as "the decision that...". Contrast the following:

  * The way that we do it
  * The way in which we do it

So for "way", the "that" clause is interchangeable with a canonical relative. But not so for "decision":
  * The decision that we do it (complement clause, inherited argstr for deverbal noun corresponding to "decide")
  * The decision in which we do it (also grammatical, but means something totally different: does not saturate arg clause)
  * The decision that we stop selling hamburgers in which we shot ourselves in the foot (both arg clause and a relative, which are distinct)

Given this contrast, we decided that things like "way that" are still `acl:relcl` in GUM, while "decision that" is `acl` (essentially the nominalized equivalent of `ccomp`)

**Comment by nschneid** [comment]
Would you use the same treatment if it were "where" or "when" instead of "that"? (Doesn't work for "way" but works for many of the temporal ones above)

N.B. For point it would be "point at which", not "point in which".

**Comment by amir-zeldes** [comment]
I don't think I would make a distinction based on which preposition it is, it's more the fact that it's substitutable by a canonical relative (with any preposition is fine for me).

For "place where" I see we have done `acl:relcl` almost always:

https://corpling.uis.georgetown.edu/annis/#_q=ZW50aXR5PSJwbGFjZSIgLT5oZWFkIHRvayAtPmRlcCB0b2sgLT5kZXAgbGVtbWE9IndoZXJlIg&_c=R1VN&cl=0&cr=15&s=0&l=10

But I found one or two `acl` as well. I think they should be made uniform to `acl:relcl`, since "the restaurant where we met" is analogous to "the restaurant in which we met". The alternative of adnominal `advcl` seems less appealing to me since it misses the relativization of the subordinate clause (we did in fact meet at that "restaurant", the matrix noun), and `acl` would conflate it with true adnominal arg clauses (since we don't allow `ccomp` on nouns).

**Comment by nschneid** [comment]
OK, looks like CGEL agrees with `acl:relcl` (p. 1053):

![image](https://user-images.githubusercontent.com/985263/120360535-d65ad900-c2d6-11eb-9ad4-78d871608716.png)

**Comment by nschneid** [comment]
OK now I'm having second thoughts about these two:

* it was on his nudging that the Indians made conciliatory gestures toward Islamabad.
* It was as part of that surveillance in early 2001 that Jafar the Pilot studied tourist helicopters in the NYC area.

These are best paraphrased as "The Indians made conciliatory gestures...on his nudging" and "Jafar the Pilot studied...as part of that surveillance." It sounds strange to say "That the Indians made conciliatory gestures was on his nudging" or "That Jafar the Pilot studied was as part of that surveillance". It seems the purpose of this construction is to extrapose the PP from the clause. So is the clause really a csubj?

**Comment by nschneid** [comment]
I do see one GUM token which uses `csubj` after an extraposed PP: 
* It was not until about 170 years later, in 1896 that an Italian doctor discovered a less painful method

**Comment by amir-zeldes** [comment]
Yup, and I think these are all `csubj` - the way I see it is that the tree's job is just to tell us the syntactic facts, and from a syntactic perspective I think "that the Indians made conciliatory gestures toward Islamabad was on his nudging" is fine, and the reason we get an "it" here is heavy subject extraposition, same as in the other cases.

**Comment by nschneid** [comment]
OK I think I've taken care of all of these; LMK if you spot problems.
