### ISSUE TITLE
"such" a problem

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#178]
"such" is a grammatically interesting word that gets tagged in various ways. Some of the distinctions appear legitimate but others look inconsistent:

* [EWT](http://match.grew.fr/?corpus=UD_English-EWT@2.8&custom=60c125814b47f&clustering=N.upos&eud=yes)
* [GUM](http://match.grew.fr/?corpus=UD_English-GUM@2.8&custom=60c125aee17ff&clustering=N.upos&eud=yes)

Anyone have opinions on the right analysis, particularly for cases where it precedes an ADJ like "such wonderful news"?

**Comment by amir-zeldes** [comment]
I think:

  * The 3 DET cases in GUM are all errors (should be ADJ)
  * The xpos PDT cases should maybe be upos DET in GUM (this is an automatic thing which could be altered if we decide so), but otherwise they are correct in GUM. EWT already has these as upos DET. We should probably choose between PRON and DET here and change the other corpus.
  * The SCONJ cases are exactly the ones where "such as" introduces a clause - this is probably the result of trying to satisfy the UD validator (xpos is still JJ). If we consider "such as" to be a fixed expression (as the deprel `fixed` implies), then I think this is probably correct given UD practices. 
  * I think ADV cases in EWT are not different enough from the regular usage to warrant that tag - I think they should be ADJ/JJ, and the adv-like effect of combining such + something that already has an `amod` is maybe a semantic thing and not really syntax (compare possible insertion of "very" in "such very nice people")

**Comment by nschneid** [comment]
> * The SCONJ cases are exactly the ones where "such as" introduces a clause - this is probably the result of trying to satisfy the UD validator (xpos is still JJ). If we consider "such as" to be a fixed expression (as the deprel `fixed` implies), then I think this is probably correct given UD practices.

Of "such as" cases in GUM, 2 are `SCONJ` and 49 are `ADJ`. I figure `ADJ` is fine because "such" is not really `SCONJ` by itself. But it could be a good candidate for `ExtPos=SCONJ` (or `ExtPos=ADP` where it attaches as `case`). EWT uses `ADJ` and `fixed` BTW.

**Comment by nschneid** [comment]
>  * The xpos PDT cases should maybe be upos DET in GUM (this is an automatic thing which could be altered if we decide so), but otherwise they are correct in GUM. EWT already has these as upos DET. We should probably choose between PRON and DET here and change the other corpus.

To me "such a word" looks like a predeterminer, so `DET`. What would be the argument for `PRON`?

>  * I think ADV cases in EWT are not different enough from the regular usage to warrant that tag - I think they should be ADJ/JJ, and the adv-like effect of combining such + something that already has an `amod` is maybe a semantic thing and not really syntax (compare possible insertion of "very" in "such very nice people")

Yeah I wanted to be sure there wasn't a syntactic distinction I was missing, but if there are only 2 `ADV` cases in EWT it's probably just an inconsistency.

**Comment by nschneid** [comment]
Other thoughts:

1. Reminiscent of "so" and "that", "such" can be definite+anaphoric (I was offered a job but refused to work for such a small fee/so small a fee/that small a fee) or not, merely expressing a degree (The student has such/so much talent that I expect them to ace the exam). The ambiguity is easy to see with "that" in _The cup doesn't hold that much water_: It could mean *very* (nonanaphoric), or it could mean *as* (anaphoric—there is an implied reference point of comparison). I suppose this is a purely semantic distinction?

2. I guess we ought to consider the standalone usages like prepositional object ("as such"), subject ("such is the norm"), direct object ("They believe these actions infringe upon their First Amendment rights, and have argued such in court"). Do these warrant a different tag? Reminiscent of how "many", "few", "several", etc. can be standalone (UniversalDependencies/docs#786).

**Comment by amir-zeldes** [comment]
> To me "such a word" looks like a predeterminer, so DET

Agreed, implemented in GUM dev, will propagate to UD at some point.

> Yeah I wanted to be sure there wasn't a syntactic distinction

Yeah, I also don't think so, prob. just an error IMO

> standalone usages

Yes, I think they should just get their common sense tags (nsubj, obj etc.)

**Comment by nschneid** [comment]
OK, so we've converged on the simple policy that "such" is ADJ except where it precedes a determiner ("such a good idea"), and this predeterminer usage is DET.

For "such as", I think: fixed(such/ADJ/ExtPos=SCONJ, as/ADP). The choice of `fixed` is already documented in https://universaldependencies.org/en/dep/fixed.html.

**Comment by amir-zeldes** [comment]
Yes, happy to implement this in GUM as well (except ExtPos, we're not really doing that ATM)
