### ISSUE TITLE
Treatment of adverbial "at all"

### ISSUE THREAD

**Issue by manning** [UniversalDependencies/UD_English-EWT#18]
How should we treat adverbial "at all"? At the moment the dependencies treat "at" as case on all, but then surely its POS tag should no longer be ADV?

```
8	not	not	ADV	RB	_	9	advmod	_	_
9	going	go	VERB	VBG	VerbForm=Ger	6	advcl	_	_
10	at	at	ADV	RB	_	11	case	_	_
11	all	all	ADV	RB	_	9	obl	_	SpaceAfter=No

9	at	at	ADV	RB	_	10	case	_	_
10	all	all	ADV	RB	_	6	obl	_	SpaceAfter=No

7	does	do	AUX	VBZ	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	9	aux	_	_
8	not	not	PART	RB	_	9	advmod	_	_
9	help	help	VERB	VB	VerbForm=Inf	3	parataxis	_	_
10	me	I	PRON	PRP	Case=Acc|Number=Sing|Person=1|PronType=Prs	9	obj	_	_
11	at	at	ADV	RB	_	12	case	_	_
12	all	all	ADV	RB	_	9	obl	_	_
```

**Comment by jnivre** [comment]
Isn't "at all" a good candidate for a fixed expression? The fact that both "at" an "all" have the tag ADV seem to indicate that this is what the annotator thought.

**Comment by dan-zeman** [comment]
+1 on fixed. But then there is no room for the `ADV` tag, except for the MISC column (I think we have been using it to store something like MWE_POS, if I recall the name of the attribute correctly.)

**Comment by arademaker** [comment]
We are using MWE_POS in the MISC column in the UD_Portuguese corpus

**Comment by sebschu** [comment]
This should already be `fixed` according to our guidelines (http://universaldependencies.org/en/dep/mwe.html).

**Comment by jnivre** [comment]
Actually not. The page you refer to has a list of things annotated as mwe/fixed, but it also has a list of things NOT annotated in this way. And "at all" is on the latter.

**Comment by sebschu** [comment]
Yes, of course. Sorry for the confusion!

**Comment by nschneid** [comment]
Now at/ADP all/DET in both EWT and GUM
