### ISSUE TITLE
Reciprocal pronouns

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#183]
#123 discusses "one another", and it was decided to use `fixed`. Two more issues:

1. A discrepancy between EWT and GUM as to the tag of "another": DET vs. PRON. EWT never uses PRON for "another", "some", or "all"; DET is applied even in the standalone cases.

2. The other reciprocal pronoun "each other" is currently `det(other, each)`. I wonder if it would be more consistent to use `fixed` there as well.

Note that both can be possessive ("one another's", "each other's"). I assume the constraint on `fixed` means that the possessive clitic would attach formally to the first word, though effectively to the entire expression.

**Comment by amir-zeldes** [comment]
Thanks for raising this:

1. This is just a behavior of the GUM upos converter (xpos is still DT). I actually think this is linguistically more accurate though: aren't these uses in fact pronominal?
2. Agreed, `fixed` would be nicer. Shall I change this in GUM? And yes, I would then expect the 's to attach to the first word.

**Comment by nschneid** [comment]
Yes, let's go with `fixed` for "each other".

DET vs. PRON—it can be argued that most determiners that are not articles can stand alone, so it is more parsimonious to say that these words are always tagged as DET and it is up to the deprel to indicate their function. Or we could say that DETs are only allowed to be `det`, which is easier to enforce but sort of defeats the purpose of separating POS from deprel. And it would be a huge change in EWT—I am seeing over 1000 hits with DET attaching as something other than `det` or `det:predet`.

**Comment by amir-zeldes** [comment]
I agree the precedent of EWT is strong here (esp. for substitutive DET "that", which GUM also does), and it matches the xpos too. OK, I can change this in GUM, and `fixed` for "each other" as well.

**Comment by amir-zeldes** [comment]
...actually I just realized substitutive (non `det`) "this" and "that" ARE upos=PRON in EWT... nothing else behaves that way consistently though:

http://match.grew.fr/?corpus=UD_English-EWT@2.8&custom=60d1f83298536&clustering=N.lemma&eud=yes

I can reproduce exactly that behavior of course, but what do we actually want? For all of them to be DET? If not, why not?

**Comment by nschneid** [comment]
Hmm, maybe demonstratives are another special case because they don't need to be interpreted as eliding a noun head (they can be deictic).

**Comment by amir-zeldes** [comment]
Eh, well, I don't really see how 'all' or 'some' are different there. My hunch is it's an arbitrary historical decision... What do we think is the right thing to do here? xpos is clear, so maybe "all DT is DET" is the simplest thing to do? On the other hand, linguistically the name pronoun fits better than the name determiner for these IMO. I'm don't feel strongly about it though.

**Comment by nschneid** [comment]
Let's go with DET for "another" since it fits the criteria at https://universaldependencies.org/u/overview/morphology.html#pronominal-words

Those guidelines don't address demonstratives directly. At the moment I don't have a strong opinion on demonstratives, but am inclined to leave them alone for now.

**Comment by nschneid** [comment]
Currently:

- "one another" is fixed(one/NUM, another/DET) in both [EWT](http://universal.grew.fr/?custom=634c1c4950339) and [GUM](http://universal.grew.fr/?custom=634c1cff35b3c). I think
   * PRON is better than NUM, consistent with our treatment of "no one" (#372)
   * `PronType=Rcp` should be added
- "each other" is fixed(each/DET other/ADJ) in [GUM](http://universal.grew.fr/?custom=634c1d5d1e105), with `PronType=Rcp`. I will implement this in EWT.

**Comment by amir-zeldes** [comment]
Will add Rcp and PRON to "one" in "one another" in GUM
