### ISSUE TITLE
lemma of born typo

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_English-EWT#191]
23      botn    born    VERB    VBN     Tense=Past|Typo=Yes|VerbForm=Part|Voice=Pass    18      advcl   18:advcl:if     CorrectForm=born

the typo here is botn -> born
do we want the lemma to be bear, like the lemma of every other instance of born?
i think that works better, but i don't know the overall lemma standard for typos

**Comment by nschneid** [comment]
Yes, good point
