### ISSUE TITLE
Double subjects

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#193]
A predicate is not supposed to have more than one `(n|c)subj`, but there are a number of erroneous annotations where this is the case due to mislabeled vocatives and expletives, copulas that should be heads, etc.

- [EWT instances](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=60fc3e3675bfb)
- [GUM instances](http://match.grew.fr/?corpus=UD_English-GUM@dev&custom=60fc3ddf668ef)

**Comment by nschneid** [comment]
@jl908069 could you please take a look at fixing the EWT cases? Some are clear errors. Others may require discussion.

**Comment by jl908069** [comment]
Sure! I'll try to fix these by the end of this week

**Comment by jl908069** [comment]
@nschneid  Not sure how to fix "with conditions as they are", so I leave it unchanged.
Also, I'm not sure about this sentence, "Yes, I know about the Kindle Fire but that's not what I want", I change "that" from `4:nsubj` to `13:nsubj` for now

**Comment by jl908069** [comment]
@nschneid  Not sure how to fix "with conditions as they are", so I leave it unchanged.
Also, I'm not sure about this sentence, "Yes, I know about the Kindle Fire but that's not what I want", I change "that" from `4:nsubj` to `13:nsubj` for now

**Comment by nschneid** [comment]
> @nschneid Not sure how to fix "with conditions as they are", so I leave it unchanged.

@amir-zeldes What do you think about *with*-absolutes like this?

> Also, I'm not sure about this sentence, "Yes, I know about the Kindle Fire but that's not what I want", I change "that" from `4:nsubj` to `13:nsubj` for now

It looks like "but", "that", "'s", and "not" should all be headed by "what".

**Comment by amir-zeldes** [comment]
We typically do advcl with "with" as mark in GUM, and the object of "with" (in PP terms) as the subject of the advcl.

**Comment by nschneid** [comment]
> We typically do advcl with "with" as mark in GUM, and the object of "with" (in PP terms) as the subject of the advcl.

Documented: https://universaldependencies.org/u/dep/advcl.html

**Comment by nschneid** [comment]
> Not sure how to fix "with conditions as they are", so I leave it unchanged.

So it should be treated like "with conditions (being) as they are"—"conditions" as nsubj. I guess the overt predicate is "are" and it has two `nsubj`s and two `mark`s?

**Comment by amir-zeldes** [comment]
> Documented: https://universaldependencies.org/u/dep/advcl.html

Exactly, like the "with" example there

> So it should be treated like "with conditions (being) as they are"—"conditions" as nsubj. I guess the overt predicate is "are" and it has two nsubjs and two marks?

Yes, but then again I think that about all nested copulas. I guess the weird ccomp for nesting structures guidelines would place "as" as the local root, with ccomp to "are", but I think that's 100% wrong, just like the normal nested copula issue.

**Comment by nschneid** [comment]
Related: #310
