### ISSUE TITLE
Annotate subjunctive mood

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#194]
I propose we use [`Mood=Sub`](https://universaldependencies.org/u/feat/Mood.html#sub-subjunctive--conjunctive) and `VerbForm=Inf` for the embedded verb/aux in constructions like "I decree that you **be** banished" and "I propose we **use** this feature".

An approximate query with a word list from [this page](https://www.englishclub.com/grammar/subjunctive.htm):
- GUM instances: http://match.grew.fr/?corpus=UD_English-GUM@dev&custom=6101e60e6cd63
- EWT instances: http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=6101e500b02d3

**Comment by amir-zeldes** [comment]
Sure, Mood sounds good, but why Inf?

**Comment by nschneid** [comment]
It's the bare form of the verb, same as the infinitive.

**Comment by amir-zeldes** [comment]
But, historically the English subjunctive is derived from an inflected finite form (cf. German, which still has an "e" suffix at least and is not identical to the infinitive). Would you consider the imperative to be infinitive in English just because it doesn't have a suffix?

I also think most English grammars consider the subjunctive to be finite, possibly for historical reasons (or because it has a subject, not sure if affixes or subjects matter more). Here's what CGEL says (p. 51):

> Finite clauses have as head a primary form of a verb or else a plain form used in either the imperative or the subjunctive constructions. Non-finite clauses have as head a gerund participle or past participle form of a verb, or else a plain form used in the infinitival construction.

**Comment by nschneid** [comment]
My interpretation was that `VerbForm` tells us which morphological paradigm to use, and we can say the subjunctive construction signaled with `Mood=Sub` results in a finite clause even though it borrows lexically from the infinitive paradigm. IOW, synchronically, subjunctiveness is a constructional rather than lexical phenomenon.

I guess the alternative would be to use `VerbForm=Fin` and give it a person and number based on the subject, but assume syncretism for the `Mood=Sub` paradigm such that every verb has one subjunctive form which happens to be identical to the infinitive. I just worry this would be confusing since we don't usually think of English verbs as having a subjunctive paradigm.

**Comment by nschneid** [comment]
Good point about the imperative, which is treated as `Mood=Imp`, `VerbForm=Fin`, though that is a bit different because it has an inherent 2nd person associated with it.

**Comment by nschneid** [comment]
But yes, the imperative form is always identical to the infinitive rather than the 2nd person finite present tense. (*Be*, not *(you) are*.) So the determination of the correct form requires consulting both `Mood` and `VerbForm`. By that logic `Mood=Sub` and `VerbForm=Fin` would work for subjunctives.

**Comment by amir-zeldes** [comment]
> synchronically, subjunctiveness is a constructional rather than lexical phenomenon

If that's the case then FEATS is probably not the right place for it. But I think the traditional grammar view of this is still that it's a morphological mood (even if this is historically motivated), so I'm for adding the feature (without Inf). I just pushed a change to the GUM build bot which should add this to the correct hits from the query above.

**Comment by nschneid** [comment]
Updated above. @amir-zeldes would you mind doing a sanity check?

Note that per PTB tag guidelines, subjunctives should be `VB`, so I've implemented that in XPOS.

I found a case of do-support that I think should be subjunctive but was omitted by the above query.
