### ISSUE TITLE
'take' + amount of time: obj or obl:tmod?

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#222]
This is inconsistent in both EWT and GUM: http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=6125a75e807f6&clustering=e.label

Note that there is the construction with another argument: "making the table only took me three months". The two options are "me" = `iobj`, "three months" = `obj` or "me" = `obj`, "three months" = `obl:tmod`.

"three months" is obligatory and can sort of be passivized (?"Three months were taken to make the table").

(Inspired by [this tweet](https://twitter.com/dbamman/status/1430349577199132676))

**Comment by aryamanarora** [comment]
This [StackExchange question](https://english.stackexchange.com/questions/59213/it-took-me-all-of-ten-minutes-to-find-out-what-does-it-took-me-mean) notes the alteration *I took 10 minutes* ~ *It took me 10 minutes*, which I think favours *me* = `iobj` and in both cases the length of time is `obj`?
