### ISSUE TITLE
obl:npmod inside hyphenated compounds

### ISSUE THREAD

**Issue by amir-zeldes** [UniversalDependencies/UD_English-EWT#235]
We're updating the tokenization of UD_English-GUM to match EWT with respect to hyphenated compounds, and are trying to make the trees like EWT too. One issue we are running into is cases where a compound modifier is labeled obl:npmod, such as:

  * Buddhist-dominated
  * Allawi-like
  * rock-solid

And a few other types (total of 52 hits):

http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61435988e91e2

Based on the discussion in #204 it sounds like these should all be `compound`, right?

**Comment by nschneid** [comment]
I vote for compound, and that was what we argued in our paper.

**Comment by amir-zeldes** [comment]
OK, great, will implement this way in GUM already!

**Comment by amir-zeldes** [comment]
@logan-siyao-peng FYI
