### ISSUE TITLE
"X, so Y"

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#236]
It is generally agreed that X is the head of "so Y", but what deprel?

EWT is [wildly inconsistent](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=6144234acd02f&clustering=dep.label) with the top choices being `parataxis`, `conj`, and `advcl`.

GUM [generally prefers `parataxis`](http://match.grew.fr/?corpus=UD_English-GUM@dev&custom=614423a2f1cfc&clustering=dep.label) but several other relations also occur.

**Comment by sylvainkahane** [comment]
I think it is `parataxis` because:
1) it is not `conj` because in "I know X, so Y" it is very unlikely that Y is in the scope of "I know";
2) it is not `advcl` because, "so Y" can be a sentence by itself and "so Y, X" is impossible.

**Comment by nschneid** [comment]
> I think it is `parataxis` because:
> 
>   1. it is not `conj` because in "I know X, so Y" it is very unlikely that Y is in the scope of "I know";

- He had a sandwich, so he's probably not hungry.
- I know he had a sandwich, so he's probably not hungry. — I guess this means *so* is anaphoric, taking just "he had a sandwich" as its first argument, though the so-Y part is not part of what is known.

Cf.
- He had a sandwich; therefore he's probably not hungry.
- I know he had a sandwich; therefore he's probably not hungry.

I don't have a strong objection to parataxis; the only thing that gives me pause is that this construction conventionally involves a comma rather than a semicolon, so it seems a tighter connection than other kinds of parataxis.

> 2. it is not `advcl` because, "so Y" can be a sentence by itself and "so Y, X" is impossible.

Another construction in this vein is "if X, then Y". This is almost always annotated with "if X" as advcl. If we expect advcls to occur in either order with respect to their head, consider:

- If he had a sandwich, he's probably not hungry. Then he's probably not hungry if he had a sandwich. — does this have the same meaning?

**Comment by amir-zeldes** [comment]
I agree it's parataxis, since there's no overt coordination. "So" it an optional adverbial like "therefore" in this construction, whereas "if" is a canonical subordinating conjunction, just like a WH complementizer (when etc.) The "argument structure" view of so as 'anaphoric' I think relates to its role as a discourse marker, or in PDTB terms a 'connective', which can have discourse argument spans, but I don't think that's a syntactic phenomenon, just a discourse one (e.g. "actually" can be a contrastive connective with some discourse unit arguments, but is definitely just an adverb)

I'll open an issue to fix the errors in GUM, though in context some non-parataxis cases might be correct due to weird constructions, repairs, fragments etc.

**Comment by nschneid** [comment]
[More inclusive EWT query](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61481ede88380&clustering=dep.label) (doesn't require a comma before "so")

**Comment by nschneid** [comment]
[Some connectives other than "so": "thus", "therefore", "however", etc.](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=6148939bee439&clustering=dep.label)

**Comment by nschneid** [comment]
^ updated the [parataxis guidelines](https://universaldependencies.org/u/dep/parataxis.html#paired-clauses-with-non-conjunction-connective-x-so-y-etc).

@amir-zeldes could you update GUM for a few additional tokens:
- [so](http://universal.grew.fr/?corpus=UD_English-GUM@dev&custom=62438ed32bbac&clustering=dep.label)
- [then](http://universal.grew.fr/?corpus=UD_English-GUM@dev&custom=62438ea082c71)

**Comment by nschneid** [comment]
Wider query to catch a few more of this construction: http://universal.grew.fr/?custom=626df84378272
