### ISSUE TITLE
with-absolutes

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#240]
Absolute clauses with *with* may contain verbless predication. Now documented [here](https://universaldependencies.org/en/dep/advcl.html).

These EWT sentences need to be fixed:

- [x] With these operating standards implemented worldwide
- [x] With beneficent Jupiter in your sign
- [x] With Colin Powell around
- [x] BC Gas won't sign the confirms with the rep in
- [x] if the sound is still there with the modem off
- [x] if the trouble goes away with the modem off

**Comment by nschneid** [comment]
....as well as [these 6 sentences](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=617c9eef9a823&clustering=X.lemma)

**Comment by nschneid** [comment]
- [ ] Third, with the "new age" Efrem Zimbalist, Jr. in charge of the investigation
- [ ] With a Pizza Hut, IHOP, 3 Starbucks, Chilis , Panera, and Chipotle on campus ALONE
- [ ] with your leg flopping
- [ ] With President Karzai certain to win the elections
- [ ] MY DAUGHTERS BUFFALO WINGS CAME OUT WITH A FLY ON IT
- [ ] If I went into the "pre-university" direction with business administration in mind

**Comment by nschneid** [comment]
What about these pseudopossessive constructions? with ~ having + item + location

- [ ] Possibly a freshwater tank with a ton of different species in there. 
- [ ] Yo mama`s so fat, she was born with a silver shovel in her mouth.
- [ ] the confirmation goes out with the wrong legal name on it
- [ ] we took a clay flower pot with a hole in the bottom
- [ ] with a cap on the bottom
- [ ] for example a 3x5x4 tank with light on one side
- [ ] They also start the day with no nicks or dings in their fins. 
- [ ] Leaving a jar with a dozen black worms in it
- [ ] I walked out with 5 inch long hair on the top, 2 inch long hair on the sides, and 1.5 in the back. 
- [ ] two rooms with a small opening between them
- [ ] the shower was dirty with other peoples hair in it
- [ ] suspicious papers with names and social security numbers on it. 
- [ ] With a smirk on her face she told me
- [ ] walk out with crap all over my hair

**Comment by nschneid** [comment]
I suppose these are verbless clauses because you can say "a T-shirt with me on it" or "I bought a T-shirt with myself on it", and PPs don't usually modify pronouns. It looks like CGEL agrees (example [iv]):

![image](https://user-images.githubusercontent.com/985263/139536478-156f98c9-df68-4d67-b51f-13e60f6deb8f.png)

**Comment by nschneid** [comment]
- [ ] they would never drive the car with me in it

(there are a few examples that are already correct, e.g. with an ADJ or PP as the embedded predicate)

**Comment by nschneid** [comment]
- [ ] Find a comfortable place on the floor and sit with your legs crossed.
- [ ] there have been tensions with Iran’s nuclear program with word coming this week that a deal was reached

**Comment by nschneid** [comment]
I annotated these as `advcl` but should they be considered `acl` depictives?

- Find a comfortable place on the floor and sit **with your legs crossed**.
- MY DAUGHTERS BUFFALO WINGS CAME OUT **WITH A FLY ON IT**
- If I went into the "pre-university" direction **with business administration in mind**

Also the pseudopossessives listed above.

**Comment by amir-zeldes** [comment]
I agree these are clauses, will correct the two GUM cases. "sit with your legs crossed" I think is advcl (manner, adverbial not adnominal), same for admin in mind. Buffalo might be depictive (it is the state of the wings, not the manner in which they came out)
