### ISSUE TITLE
SCONJ/case

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#243]
Initially observed in #208:

> it looks like EWT has a lot of incorrect [SCONJ/case combinations](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61213c28a4c16&clustering=X.upos), probably due to buggy conversion.

**Comment by nschneid** [comment]
On the agenda for the UD core group: whether SCONJ should always correspond to `mark` and ADP should always correspond to `case`, or whether the tags should be more lexically based.

**Comment by nschneid** [comment]
Most of these SCONJ/case instances are due to WH constructions.

**Comment by amir-zeldes** [comment]
In GUM the mapping is automatic (SCONJ/ADP upos is decided based on mark/case deprel in the conversion from xpos), so there are no exceptions, and I think it has worked fine. For English it also works out well due to the behavior of the PTB tag IN, so it's easy to convert.

**Comment by nschneid** [comment]
[detailed query](http://universal.grew.fr/?custom=63de78ed81505)

**Comment by nschneid** [comment]
An interesting idiom here is "keep track of", which licenses a complement that may be nominal or clausal. Does the complement attach to "keep" or "track"?

From a web search I see things like "Track was kept of the project's progress" (though this is marginal for me) but not things like "Track of the project's progress was kept". I suspect this reflects a shift in which the of-complement became associated with the verbal idiom as a whole, rather than the noun as you would expect of an of-phrase, and thus maybe should attach at the clause level.
