### ISSUE TITLE
Subjunctives with "should" and "lest"

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#255]
- **Should**: I can find [14 EWT matches](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61748d723b30d) and [1 EWT match](http://match.grew.fr/?corpus=UD_English-GUM@dev&custom=61748dd515b7a), e.g. "Should the Arctic Ocean become ice-free in summer, ...".
- **Lest**: [3 EWT matches](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61748f3e38268), [2 GUM matches](http://match.grew.fr/?corpus=UD_English-GUM@dev&custom=61748f4def129)

1. These are subjunctive adverbial clauses, yes? If so we should treat the verb features accordingly (#194).

2. Is it right to analyze "should" as an AUX in this construction?
 
I could see an argument that it ought to be SCONJ like "lest". AFAIK it must be clause-initial to signal the subjunctive (without a separate subordinator like "if"), and other AUXes cannot do the same (although ***would that** we had left earlier* is perhaps similar).

OTOH, it can have similar conditional semantics with "if": "If you **should** see my keys, please let me know" ⇔ "**Should** you see my keys, please let me know"  (not the normal meaning of "should" as in obligation or likelihood). In the former it looks syntactically like an AUX. So maybe it should also be tagged as AUX when inverted with the subject in the absence of "if", in which case it would be an unmarked adverbial clause.

**Comment by nschneid** [comment]
@amir-zeldes have you implemented this for GUM? If so I'll close the issue.

**Comment by amir-zeldes** [comment]
Yup!

**Comment by nschneid** [comment]
FTR, the CGEL discussion of this kind of *should* is on pp. 187–188, "Low-degree modality"
