### ISSUE TITLE
VB/VBP tags

### ISSUE THREAD

**Issue by kanayamah** [UniversalDependencies/UD_English-EWT#257]
PoS tag of "take" (ID=6) is tagged as `VBP` but it should be `VB` as it has a feature `VerbForm=Inf`.
```
# sent_id = answers-20111106032810AA43zpY_ans-0004
# text = The police would make you take it down and you may face fines and imprisonment (but definitely not execution.)
1	The	the	DET	DT	Definite=Def|PronType=Art	2	det	2:det	_
2	police	police	NOUN	NNS	Number=Plur	4	nsubj	4:nsubj	_
3	would	would	AUX	MD	VerbForm=Fin	4	aux	4:aux	_
4	make	make	VERB	VB	VerbForm=Inf	0	root	0:root	_
5	you	you	PRON	PRP	Case=Acc|Person=2|PronType=Prs	4	obj	4:obj|6:nsubj:xsubj	_
6	take	take	VERB	VBP	VerbForm=Inf	4	xcomp	4:xcomp	_
7	it	it	PRON	PRP	Case=Acc|Gender=Neut|Number=Sing|Person=3|PronType=Prs	6	obj	6:obj	_
8	down	down	ADV	RB	_	6	advmod	6:advmod	_
```

* Correctly tagged as VB (242 occurrences): http://match.grew.fr/?corpus=UD_English-EWT@2.8&custom=6178c26d0b413
* Tagged as VBP (5 occurrences): http://match.grew.fr/?corpus=UD_English-EWT@2.8&custom=6178c22a361f7
  * In these cases, VBP should be changed to VB
  * 4 out of 5 have features `Mood=Ind|Tense=Pres|VerbForm=Fin` but they should be changed to `VerbForm=Inf`

**Comment by manning** [comment]
Thanks for the report! I've now gone through every example referenced in this thread, including by Nathan, fixing things as appropriate. They'll be fixed in UD v2.9. So I'm closing this issue.
