### ISSUE TITLE
advcl attachment to nominal

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#259]
- [39 EWT examples](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=617d69a7b4886)
- [30 GUM examples](http://match.grew.fr/?corpus=UD_English-GUM@dev&custom=617d6a3112f77)

It looks like some of these are structural errors (e.g. depictives) and others should be `acl`.

**Comment by amir-zeldes** [comment]
I'm not entirely sure what the intended policy is for most of the GUM cases, which are adnominal clauses mediated by a preposition. So on the one hand, they are acl-like (adnominal clauses), on the other hand, they are prepositional, so therefore oblique, and the clausal equivalent to obl is advcl (in its function as a hypothetical `cobl`).

In other words, the GUM cases are probably a result of the confusion with what advcl means in UD - should this be `acl` or adnominal `advcl`?

  * a word/HEAD in the sense of/(mark) being a conventional lexical sign/(advcl|acl?)

**Comment by amir-zeldes** [comment]
(adding @dan-zeman - I have no strong opinion on this BTW, except for generally not liking the name advcl for 'cobl'-like things)

**Comment by dan-zeman** [comment]
If it is adnominal, it should be `acl` (which literally stands for "adnominal clause").

**Comment by amir-zeldes** [comment]
OK, I can fix for GUM

**Comment by nschneid** [comment]
[Updated EWT query](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61ed80f89fe4b) omitting PRON heads and "What if". Many of the results are implied predications so `advcl` seems OK. Some should be `acl`, some are misattached `advcl` clauses in comparative constructions.

**Comment by nschneid** [comment]
(Added `acl:since` as a validator possibility, e.g. "the stock market improvement since Bush took office")
