### ISSUE TITLE
The rationale for the POS tags of urls

### ISSUE THREAD

**Issue by zhu-y11** [UniversalDependencies/UD_English-EWT#26]
URLs is always tagged as 'X'.  However, in some sentences, there are urls that have syntactic functions, as in examples 

````
# sent_id = newsgroup-groups.google.com_civicamerican_22c54c292026bfd2_ENG_20060128_072400-0039
# text = Testimony at http://judiciary.senate.gov/testimony.cfm?id=1725&wit_id=4905
1	Testimony	testimony	NOUN	NN	Number=Sing	0	root	_	_
2	at	at	ADP	IN	_	3	case	_	_
3	http://judiciary.senate.gov/testimony.cfm?id=1725&wit_id=4905	http://judiciary.senate.gov/testimony.cfm?id=1725&wit_id=4905	X	ADD	_	1	nmod	_	_

# sent_id = newsgroup-groups.google.com_civicamerican_22c54c292026bfd2_ENG_20060128_072400-0040
# text = Descriptions and Links at http://www.UnitaryExecutive.net
1	Descriptions	description	NOUN	NNS	Number=Plur	0	root	_	_
2	and	and	CCONJ	CC	_	3	cc	_	_
3	Links	link	NOUN	NNS	Number=Plur	1	conj	_	_
4	at	at	ADP	IN	_	5	case	_	_
5	http://www.UnitaryExecutive.net	http://www.unitaryexecutive.net	X	ADD	_	1	nmod	_	_
````

In my opinion, POS tag of a word should change according its the syntactic function, and it is also what UD does for most of the normal words. Therefore, in the examples, urls should be tagged as PROPN or NOUN.

I just want to know why UD decides to tag urls always as 'X', is there a strong rationale for that?

**Comment by nschneid** [comment]
The historical explanation for EWT is given here—a bunch of miscellaneous PTB tags, including ADD for web addresses, were mapped to `X`: https://universaldependencies.org/en/pos/X.html

However, web addresses are given as examples in the guidelines for [`SYM`](https://universaldependencies.org/u/pos/SYM.html), so we should probably change to that (consistent with [Sanguinetti et al.](http://arxiv.org/abs/2011.02063)).

**Comment by nschneid** [comment]
After some consideration I now think these should be PROPN. UniversalDependencies/docs#973

**Comment by nschneid** [comment]
URLs are PROPN now: see #440.
