### ISSUE TITLE
goeswith dependents should not have feats?

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#262]
- [68 EWT tokens](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=618363269774b)
- [3 GUM tokens](http://match.grew.fr/?corpus=UD_English-GUM@dev&custom=6183638f9231d)

**Comment by nschneid** [comment]
(should be enforced by validation)

**Comment by amir-zeldes** [comment]
intuitively this makes sense - I can change this in GUM but I assume I should hold off until after the freeze, right?

**Comment by nschneid** [comment]
Once UniversalDependencies/docs#838 is approved we can fix `goeswith` in EWT

**Comment by nschneid** [comment]
fixed for EWT in #314
