### ISSUE TITLE
Determiner the with ADV and PART?

### ISSUE THREAD

**Issue by wellington36** [UniversalDependencies/UD_English-EWT#264]
I found these cases of wrong in upos for determiner ```the```

```
$ git checkout dev; cat *.conllu | udapy -q util.Eval node='if (node.form == "the" and node.upos != "DET" and node.feats["Typo"] != "Yes"): print(node.form,node.lemma,node.upos)'

the the ADV
the to PART
the the ADV
```

see query in [grew-match](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=6183fd4b5264c).

**Comment by nschneid** [comment]
None of these should actually be determiners.

* I put some chicken wiring around it **the**/ADV I got from home depot and now it can't out. — I think this is a typo for "that", should be a relative pronoun (PRON)
* i spoke to the vet and he said **the**/PART/lemma=to give him white rice — should have Typo=Yes
* "now all **the**/ADV sudden this grinder won't leave a finished look" — is this a misrendering of the expression "all of a sudden"?

**Comment by wellington36** [comment]
> None of these should actually be determiners.
> 
> * I put some chicken wiring around it **the**/ADV I got from home depot and now it can't out. — I think this is a typo for "that", should be a relative pronoun (PRON)
> * i spoke to the vet and he said **the**/PART/lemma=to give him white rice — should have Typo=Yes
> * "now all **the**/ADV sudden this grinder won't leave a finished look" — is this a misrendering of the expression "all of a sudden"?

In the third case we have to fix the token "the" to two tokens "of" and "a", is this a problem right?

**Comment by rueter** [comment]
Hi, the third one is perhaps, just a deviation from the standard. Growing up in the Seattle area, the use of "the", although not accepted in school or writing, is quite a familiar form of the suggested standard below in " a". This said, it might not even be a typo but just the wrong UPOS.
> * "now all **the**/ADV sudden this grinder won't leave a finished look" — is this a misrendering of the expression "all of a sudden"?

**Comment by nschneid** [comment]
Huh, I'd never heard it before but it is listed [in Wiktionary](https://en.wiktionary.org/wiki/all_the_sudden), well-attested among Americans on Twitter, etc. I guess "the" should be treated as the determiner of "sudden"?
