### ISSUE TITLE
Inconsistencies in token ranges, SpaceAfter=No, and CorrectSpaceAfter=Yes annotations

### ISSUE THREAD

**Issue by rhdunn** [UniversalDependencies/UD_English-EWT#265]
1. In `answers-20111108075853AAUIKRQ_ans-0007`
```
9	4	4	NUM	CD	NumType=Card	10	nummod	10:nummod	SpaceAfter=No
10	x	x	SYM	SYM	_	13	nmod:npmod	13:nmod:npmod	SpaceAfter=No
11	wide	wide	ADJ	JJ	Degree=Pos	13	amod	13:amod	_
```
is missing a `CorrectSpaceAfter=Yes` on token 10 (c.f. email-enronsent30_01-0025, which uses that in `xif`).

2. In `reviews-158335-0006`
```
17	someon	someone	NOUN	NN	Number=Sing|Typo=Yes	20	nmod:poss	20:nmod:poss	CorrectForm=someone|SpaceAfter=No
18-19	elses	_	_	_	_	_	_	_	_
18	else	else	ADJ	JJ	Degree=Pos	17	amod	17:amod	_
19	s	's	PART	POS	Typo=Yes	17	case	17:case	_
```
shouldn't the token range apply to 17-19, as that is the entire word `someonelses`?

3. In `reviews-018562-0004`
```
21	every	every	DET	DT	_	19	conj	19:conj:and|23:det	SpaceAfter=No
22	one	one	NUM	CD	NumType=Card	18	reparandum	18:reparandum	_
23	one	one	NUM	CD	NumType=Card	18	obj	18:obj	_
```
this is missing a 21-22 token range. Note: other entries classify `everyone` as a single `PRON+NN` token.

**Comment by nschneid** [comment]
The first two are errors, `CorrectSpaceAfter=Yes` should be added.

For "every one", please look at how other oversegmented indefinite pronouns are treated: "some one", "any one", "any thing", etc. I see some of them use `goeswith`. Perhaps we need better guidelines for this.

**Comment by nschneid** [comment]
(And note that "no one" is conventionally spelled as two words but grammatically acts like "everyone" or "nothing".)

**Comment by rhdunn** [comment]
Note that the 3rd case is for the text "everyone one" (deonstrating a repeated use of "one"). Tokens 21 and 22 don't have a space between them but are not annotated using a token range like they are in compounds such as "wanna", etc..

The question of how "everyone", etc. should be tokenized is an interesting one, especially given how in historic modern English texts (1800-1900) there are examples of them separated ("some one", etc.). I'm not sure how common that is now, nor what the distribution is like between the two forms in current usage compared with historic usage.

**Comment by nschneid** [comment]
> Note that the 3rd case is for the text "everyone one" (deonstrating a repeated use of "one"). Tokens 21 and 22 don't have a space between them but are not annotated using a token range like they are in compounds such as "wanna", etc..

Right, the example is "everyone one of us", and the corrected version is "every one of us", which is implemented as splitting the first token into two words and treating the second of these (first occurrence of "one") as an error. I am not sure if multiword tokens should apply when one of those words is extraneous.

**Comment by nschneid** [comment]
The [guidelines for typos](https://universaldependencies.org/u/overview/typos.html) explain that the token range should only be used for ordinary grammatical conventions:

> UD has two mechanisms capable of capturing that two words are not separated by whitespace: the `SpaceAfter=No` attribute in MISC, and multi-word tokens. The former is considered low-level and it is normally used between a word and a punctuation node. The latter is intended for situations where two real words are merged into one, but it is assumed that these cases adhere to regular rules of the grammar, i.e., they are not arbitrary errors.

So the third example looks correct.
