### ISSUE TITLE
CorrectForm

### ISSUE THREAD

**Issue by kanayamah** [UniversalDependencies/UD_English-EWT#268]
To make this consistent, word 9 should have `CorrectForm='` in its MISC field.
```
# sent_id = reviews-041925-0002
# text = I will be calling tropics for my companies next event!
8-9	companies	_	_	_	_	_	_	_	_
8	companie	company	NOUN	NN	Number=Sing|Typo=Yes	11	nmod:poss	11:nmod:poss	CorrectForm=companies
9	s	's	PART	POS	Typo=Yes	8	case	8:case	_
```

Word 19 and 28 should have `Typo=Yes` and `CorrectForm=n't`, shouldn't they?  Word 2 can have `Abbr` or `Typo` as well.
```
# sent_id = answers-20111108102621AA3hPqj_ans-0005
# text = iv owned beardies for ovr 3 yrs and i handle mine all the time.. they dont go hard like needle hard but they arent pillow soft.
1-2	iv	_	_	_	_	_	_	_	_
1	i	I	PRON	PRP	Case=Nom|Number=Sing|Person=1|PronType=Prs	3	nsubj	3:nsubj	_
2	v	have	AUX	VBP	Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin	3	aux	3:aux	_
...
18-19	dont	_	_	_	_	_	_	_	_
18	do	do	AUX	VBP	Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin	20	aux	20:aux	_
19	nt	not	PART	RB	_	20	advmod	20:advmod	_
...
27-28	arent	_	_	_	_	_	_	_	_
27	are	be	AUX	VBP	Abbr=Yes|Mood=Ind|Number=Plur|Person=3|Tense=Pres|Typo=Yes|VerbForm=Fin	30	cop	30:cop	CorrectForm=are
28	nt	not	PART	RB	_	30	advmod	30:advmod	_
```
Similar cases (arent, wasnt, theyre):
```
# sent_id = answers-20111108092643AAXe4lD_ans-0063
# sent_id = reviews-100592-0003
# sent_id = reviews-220214-0001
# sent_id = answers-20111107155845AAE3kCA_ans-0002
```

In this case, `ur`'s expected surface strings are given, but how can we know the original sentence should be `you are` rather than `youare`?  Because there is no way to know the spaces in MWT.  Can the token 17-18 have `CorrectForm=you are`?
```
# sent_id = answers-20111108102621AA3hPqj_ans-0007
# text = they puff out to look bigger and badder and they can scratch you a lil if ur holding them to tight :)
17-18	ur	_	_	_	_	_	_	_	_
17	u	you	PRON	PRP	Typo=Yes	19	nsubj	19:nsubj	CorrectForm=you
18	r	be	AUX	VBP	Mood=Ind|Number=Sing|Person=3|Tense=Pres|Typo=Yes|VerbForm=Fin	19	cop	19:cop	CorrectForm=are
```

A similar case (their->they are):
```
# sent_id = answers-20111108093211AA8bYFE_ans-0002
# text = I'm getting a dwarf Hamster tomorrow And i was just talking to my Mom and she said that we have to take out the wheel at night because it would disturb her sleep But i told her no because i said their energetic at night at my room is right next door to hers But i heard their are wheels that dont make noise at all what would be the price of it?
43-44	their	_	_	_	_	_	_	_	_
43	thei	they	PRON	PRP	Typo=Yes	45	nsubj	45:nsubj	CorrectForm=they
44	r	be	AUX	VBP	Mood=Ind|Number=Sing|Person=3|Tense=Pres|Typo=Yes|VerbForm=Fin	45	cop	45:cop	CorrectForm=are
```

**Comment by nschneid** [comment]
Thanks. I would say that "ur" is not a typo but an abbreviated version of "you're" (should have `Abbr=Yes`). So it doesn't need `CorrectForm`s.

Same for all the nonstandard spellings in

> iv owned beardies for ovr 3 yrs and i handle mine all the time.. they dont go hard like needle hard but they arent pillow soft.

(given the number and nature of nonstandard spellings there it is likely somebody was typing on their phone and deliberately abbreviating).

**Comment by amir-zeldes** [comment]
Mm, I'm not sure about this - I think we've been marking such things in GUM with typo, not because we think it's unintentional, but because it's very non-standard (I think we've been equating this with expected spelling based on a spell-checker). One could maybe argue about "ur" in online language, but "iv" or "ovr" strikes me as very non-standard, and it could be useful to know that this is not a canonical spelling.

**Comment by nschneid** [comment]
From [the guidelines](https://universaldependencies.org/u/overview/typos.html#intentionally-noncanonical-spellings):

> Intentionally Noncanonical Spellings
>
> Abbreviations and expressive spelling variants are not considered typos, but may be paired with a CorrectForm for the canonical spelling. See the Abbr=Yes and Style=Expr features.

It seems wrong to judge abridged spellings as errors if we think they are intentional and may be influenced by the genre (or modality of text entry). Note there are other values for `Style` that could be used to signal some notion of non-standardness.

**Comment by amir-zeldes** [comment]
Indeed, and for other more fine-grained indications of non-standard language, I can also recommend some of the MISC annotations from our survey of especially user-generated internet content in UD data, here:

https://arxiv.org/pdf/2011.02063.pdf

If there are more fine-grained tags, then I agree we do not need to have Typo here, but between having nothing and having something, I'd rather have `Typo=Yes` than not having any indication that this is unusual on some level.

BTW I'm guessing part of the reason I feel this way is that GUM's Typo annotations are derived from the native annotation scheme's TEI tag `<sic>`, which indicates many things that are not Typos. It's been a long standing to-do to clean that up in GUM for better UD compatibility, but for now all of the above would have `Typo=Yes` there, so it's another difference with EWT.

**Comment by kanayamah** [comment]
@nschneid @amir-zeldes thank you for discussion.  I agree that "ur" is something different from `Typo`.
Problem here is, whichever (`Typo` or `Abbr`) it is, as long as there are `CorrectForm`s, the correct sentence should be recovered with information in MISC field.   To solve this problem, I propose to change `CorrectForm=are` to `CorrectForm='re` in the two cases at the end of https://github.com/UniversalDependencies/UD_English-EWT/issues/268#issue-1071933123.

**Comment by nschneid** [comment]
Thanks @kanayamah. Fixed the tokens listed above + a few others. If you see more feel free to submit a pull request against the dev branch.

**Comment by kanayamah** [comment]
@nshneid I found `CorrectForm` is missing for `Typo=Yes` cases for apostrophe.
Please review my PR which fixed this.  Thanks!

**Comment by nschneid** [comment]
OK the possessive and "ur" cases are now fixed. @kanayamah are there other problems listed above that you want to fix?

**Comment by kanayamah** [comment]
@nschneid thank you, what I've found so far were fixed!
