### ISSUE TITLE
Predicate ADVs

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#279]
`ADV` tokens heading a `cop` relation:
- [EWT results](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61c758680e695&clustering=X.lemma)
- [GUM results](http://match.grew.fr/?corpus=UD_English-GUM@dev&custom=61c7596995804&clustering=X.lemma)

Some of these ("alone", "late") are better tagged as adjectives.

Some of these are core adverbs (e.g. "really") that cannot be *be*-complements; the predicate is missing, and the analysis of ellipsis is incorrect (the copula should be the head).

Many of these are spatial terms that CGEL calls prepositions (that framework stipulates that adverbs cannot be *be*-complements).

"if you think it should be better, please help it be **so**": should this be a pronoun (cf. "that way")? ADJ because it substitutes for an adjective phrase ("better")? CGEL treats it as a maverick: "we prefer to classify anaphoric *so* simply as a pro-form; its properties are unquestionably unique, and we do not believe that anything is gained by forcing it into one or more of our general part-of-speech categories" (p. 1538).

**Comment by nschneid** [comment]
"The food was good, and so was our waitress." Should "was" be promoted to head of the 2nd clause? Right now the head is "so".

**Comment by nschneid** [comment]
In #200 we decided ADV for predicative close/far. So I'll leave those alone.

**Comment by nschneid** [comment]
[EWT ADVs with a subject but no `cop`](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61c78ca263f91&clustering=X.lemma): most are incorrect handling of ellipsis

**Comment by amir-zeldes** [comment]
I think in general there is no problem with adverbs being copula predicates; if PPs can be predicates, than why not adverbs? From "outside" they are basically the same:

  * Kim is in the house
  * Kim is there

So notwithstanding possible errors, I don't see an issue here. 

  * The food was good, and so was our waitress. - I think it's correct for "so" to be the `conj` of "good", no promotion needed

**Comment by nschneid** [comment]
> I think in general there is no problem with adverbs being copula predicates; if PPs can be predicates, than why not adverbs? From "outside" they are basically the same:
> 
>   * Kim is in the house
>   * Kim is there

But it is normally only certain spatiotemporal adverbs (including "outside", "there", and "now") that can be predicate complements. Usually an adjective phrase or PP is required:

* The team's loss was sudden/*suddenly.
* Losses by the team were frequent/*often.
* The team's loss happened again. *The team's loss was again.

If we treat "so" as an ADV predicate complement, I think the justification would be that ADV is basically a garbage category for grammatical words that don't easily fit any other POS.

**Comment by amir-zeldes** [comment]
I'm not sure I'm on the right level of the discussion here: is this a question about English grammar and what kinds of adverbs do we find in predicate position, or is it an annotation question about "what do we do when we see a non-spatio-temporal adverb in predicate position?

If it's the latter, then if I actually saw the sentence "The team's loss was suddenly", then I think I would still go with `root(suddenly)`. Are you saying you would prefer "was" in this situation because it's non-standard?

**Comment by nschneid** [comment]
No I'm questioning whether "so" is really an adverb here. It is a pro-...something, I just don't know what is the best POS. If we call it ADV (a pro-adverb) it would be an exception to the pattern of what kinds of adverbs occur as predicate complements (in perfectly grammatical English). But I don't love calling it PRON either.

Or maybe it's not a predicate complement, but an adverb modifying "be" in a similar fashion as do-so substitution. In which case "be" should be promoted to head of the clause. How about:

- I wanted it to snow, and it **did (so)** on Christmas.
- I wanted it to be cold, and it **was (so)** on Christmas.
- I want the house to be clean—please help it to **be (so)** (on Christmas).

The infinitive "be" sounds a bit awkward if both the "to" and "so" are omitted, but maybe it's OK with the right intonation.

**Comment by amir-zeldes** [comment]
Yes, I think it's a pro adverb, but I think so is "there", and we don't question the tag for that one. I would say being an ADV outranks being somehow pronominal as well, but I guess this shows that our POS scheme is not really targeting the same level across the board (ADV is a functional category, PRON is a semantic one). 

All of the examples above look possible to me, and I think of "so" as an ADV in all of these positions. Consider also that although "so" is conventionalized as the pro-ADV and is especially linked with the "do so" construction, it is still basically substitutable with "thus" (I wanted it to be cold and it was thus on Christmas). For me "thus" is also clearly an adverb.

**Comment by nschneid** [comment]
OK. "So" is a grammatically weird word and ADV seems as good a tag as any. So I'll leave the annotations as is.
