### ISSUE TITLE
As-as comparatives: fixes and a few difficult cases

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#281]
[EWT results](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61c8091a0ebb0): often the second part attaches to the first "as" where it should instead attach to its head

(Added explicit guidelines for "as soon as", "as long as" in [en/fixed](https://universaldependencies.org/en/dep/fixed.html) since these have idiomatic meanings)

**Comment by nschneid** [comment]
[another largely overlapping query](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61c813db64bbc&clustering=Y.lemma)

**Comment by nschneid** [comment]
What to do with "It's not quite as freewheeling an environment as you'd imagine"? What is the main predicate, "freewheeling" or "environment"? "Freewheeling" makes more sense semantically but then it's not obvious how to attach "environment" (`obl:npmod(freewheeling, environment)`?).

Note that "of" can be inserted after "freewheeling".

**Comment by nschneid** [comment]
Found it in CGEL, pp. 550-551: adjective phrases in predeterminer position!

![image](https://user-images.githubusercontent.com/985263/147416798-8fa43ba0-2889-4d36-9cf2-f980454fe244.png)
![image](https://user-images.githubusercontent.com/985263/147416802-c914d7c6-69bd-4749-81dd-bb8f7c02cc25.png)

**Comment by nschneid** [comment]
In addition to the as-as cases, found these which have an ADJ followed by "a":
- You can order appetizers rather than a full meal and have **just as good** a dinner. 
- it really depends on **how good** a horse your horse really is

Should we use `det:predet` for the adjectives in these and the as-as cases?

Exclamative ["what a"](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61c8b48aa9e90&clustering=rel.label) is often but not always annotated as `det:predet`. (Looks like "such a" is consistent.)

**Comment by nschneid** [comment]
Also, what about the construction "as much/many/few/little as (AMOUNT)"?

- getting a soaking **as many as** 270 days of the year
- there are **as many as** 42 RAW agents based in Kandahar

This is very similar to the approximator construction "more/less than (QUANTITY)", which is `fixed`+`advmod` as documented [here](https://universaldependencies.org/en/dep/fixed.html). I suppose "as many as" should be treated the same way and added to the guidelines?

**Comment by amir-zeldes** [comment]
I think they should come out of the ADJ that licenses them, so:

  * It's not quite as freewheeling an environment as you'd imagine
  * advmod(freewheeling, as1)
  * advcl(freewheeling, imagine)

It would be the same if we had heavy extraposition:

  * It's not quite an environment as freewheeling as you'd imagine

**Comment by nschneid** [comment]
The issue isn't really the as-as construction; the issue is the predeterminer adjective construction.

- How good a book is it?
- Yes, it is indeed [that(ADV) good] a book!

Do we want to say this is amod(book, good) despite the fact that the adjective is before a determiner?

**Comment by amir-zeldes** [comment]
Yes, definitely IMO. It's just extracted because of wh movement/topicalization. In dependencies the analysis should stay normal like the unextracted word orders, so amod.

**Comment by nschneid** [comment]
WFM. Are you OK with `fixed` for "as many as (QUANTITY)"?

**Comment by amir-zeldes** [comment]
It's not on the current list... and it's pretty much compositional and regular, so why add it? I realize this is similar to "more than", but I guess my skepticism comes from the fact that I've never understood why these things are fixed to begin with.

**Comment by nschneid** [comment]
These are multiword expressions in the approximator construction: In "I can devour over 5 cookies", "devour" expects an NP object, not a PP/oblique, so we say it is advmod(5, over). By analogy, we can say "I can devour as many as 5 cookies" involves as_many_as modifying 5. Treating it compositionally would be an ellipsis reading, "I can devour [as many \<cookies\> [as 5 cookies]]", which seems like overkill. Compare:

1. I can devour as many as 5 cookies, and you can devour as many as 5 too.
2. ?I can devour as many as 5 cookies, and you can devour as many too.

(2) feels a bit zeugmatic to me—like the first part of the sentence is answering the question "How many cookies can you devour" and the second part is answering "Can you devour exactly 5 cookies?", not "Can you devour *up to* 5 cookies?".

**Comment by amir-zeldes** [comment]
Well, I guess in for a penny... But would you then also do "as few as" and "as much as"? My problem is that I don't like huge `fixed` lists and I'm not convinced it's right to express these quirks on the syntax level, where these things are more or less 'normal' and have a rather high potential for variation. This kind of defies my expectation that 'fixed' is a list of literal frozen expressions possibly with inert, fossilized syntax that is no longer relevant. But we can say "devour as pathetically little as 5" etc. etc., which really shows that these things are 'alive' and not fossilized.

**Comment by nschneid** [comment]
I think these 3 expressions are pretty well fossilized. COCA results:

- "as many as": 10930 hits. "as ADV many as": 1 non-typo hit ("as uncountably many as")
- "as few as": 630 hits. "as ADV few as": 0 hits
- "as little as": 3564 hits. "as ADV little as": 2 hits which are actually "as a little as", which could be errors or could indicate that "a little" is a fixed expression

**Comment by amir-zeldes** [comment]
Right, but first of all, adding 4 expressions to the list just for this is quite a bit, and they are not totally frozen either:

- you can spend as much or as little as you like
- pick up some blood as fresh and as much as possible
- Costs the same as T-Mobile for greatly reduced service , not half as god damn much as anything
- You will need to discover as very much as you can on how to prevent shopping for a replica

(examples from ENCOW)

The coordination is especially suspicious for fixed IMO

**Comment by nschneid** [comment]
Yes, "much" etc. can continue to act as standing for an item (as a fused head), including in comparative constructions. I would say they are only fixed expressions when followed by a numeric quantity or measure, where they have the meaning 'up to' or its opposite. The above examples cannot be substituted with "up to".

**Comment by nschneid** [comment]
> I realize this is similar to "more than", but I guess my skepticism comes from the fact that I've never understood why these things are fixed to begin with.

Let me see if this convinces you regarding the "more than QUANTITY" construction:

When "more" is the head in a comparison (2nd part of the sentence), the than-PP can be dropped with enough context:

- I have more cookies than you, and Alice has **more than you** too.  
→ I have more cookies than you, and Alice has **more** too.

But in the approximator use of "more than", this would produce weird results:

- I have more than 5 cookies, and Alice has **more than 5** too.  
→ ?\#I have more than 5 cookies, and Alice has **more** too.

It is at best a stretch for me to get the intended reading there (I think it requires focus on "5"). If the first sentence neutrally expresses my possession of some cookies, the 2nd one doesn't make sense. I think this is because I am parsing it as [[more than] 5], i.e. '>5'.

**Comment by amir-zeldes** [comment]
Sure, I don't really disagree with any of this; if we accept that "more than" is fixed, then it's not a stretch to do it with as-as. It's really more that I fundamentally think we are overusing fixed. Lots of constructions have idiosyncratic properties that don't get distinguished in an inventory of 50 labels, and we do lose something by using fixed (namely the compositional properties are lost, everything becomes a left-to-right fountain even though there is clear internal structure on the syntactic level).

But I don't want to stand in the way of consistency, and "more than" is an established case, so it you want to do this in EWT I can reproduce it in GUM as well.

**Comment by nschneid** [comment]
Searching for "as many/much/few/little as QUANTITY"—I can find [4 in EWT](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61db0fb71689a&clustering=Q.upos) (before NUM) and [2 in GUM](http://match.grew.fr/?corpus=UD_English-GUM@dev&custom=61db1017424f0&clustering=Q.upos) (before NUM or DET "a little").

**Comment by amir-zeldes** [comment]
For GUM, the det case looks a bit doubtful, since I'm not sure it really modifies "few":

  * after as little as a few months of limited exposure

Isn't it modifying the whole "months" phrase? The only really clear example I see is:

  * as many as 300,000 people

Here I think the expression truly modifies the number. But maybe the semantics are confusing me?

**Comment by nschneid** [comment]
Hmm...I could go either way. This sounds a bit strange:

- How many months will it last? ?As little as a few.

Whereas with a number it's better:

- How many months will it last? As little as 5.

**Comment by amir-zeldes** [comment]
OK thanks, added to GUM dev
