### ISSUE TITLE
Double objects

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#282]
Predicates with multiple `obj`s:

- 44 [EWT results](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61cb5179a2133)
- 1 [GUM result](http://match.grew.fr/?corpus=UD_English-GUM@dev&custom=61cb525920567)

I think these should use `iobj` for the first object or are structural errors (most notably vocatives, relative clauses, and supplements).

No predicates have multiple `iobj`s.

Whether `iobj` without `obj` should be allowed is under discussion in #256.

**Comment by nschneid** [comment]
Updating the query to omit relativizers: http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61f5d0eeca2d5

**Comment by amir-zeldes** [comment]
Yup, I think this is basically the origin of the resumptive construction, which is a canonical strategy in many languages and logically makes sense. It's more common for object relatives typologically than for subject relatives, but still well attested even for subjects, incl. e.g. in Hebrew for subject relatives with copulas (in Modern Hebrew it's 'sub-standard' except if the relative clause is a copula clause).

**Comment by nschneid** [comment]
Or maybe in this case transfer from a language with this construction. So "that" should be SCONJ/mark?

**Comment by amir-zeldes** [comment]
Yeah, since the subject literally appears as a pronoun I would give it then nsubj. 'that' is indeclinable, so SCONJ/mark sounds sensible to me (the alternative is maybe dislocated but I like it less here)
