### ISSUE TITLE
passives: inconsistency between subject and aux

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#289]
- {n,c}subj:pass without aux:pass: [EWT](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61dbc6c8c3615), [GUM](http://match.grew.fr/?corpus=UD_English-GUM@dev&custom=61dbc8442ed76)
  * {n,c}subj:pass with non-:pass final aux or cop: [EWT](http://universal.grew.fr/?custom=63267790704f0)
- aux:pass with only plain {n,c}subj: [EWT](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61dbc82700c84), [GUM](http://match.grew.fr/?corpus=UD_English-GUM@dev&custom=61dbc7e012ba4)

**Comment by amir-zeldes** [comment]
Thanks for catching! Most of the GUM cases are errors, will fix (there are quite a few legitimate cases though, such as headings with no verb but a passive participle predicate: "At least 107 killed in Mecca crane collapse")

**Comment by nschneid** [comment]
A lot of main verbs with `:pass` dependents are missing `Voice=Pass` in [EWT](http://universal.grew.fr/?custom=632679032a7d8), and several in [GUM](http://universal.grew.fr/?custom=6326792f7c6ed). Is there a principled reason or are these errors?

**Comment by nschneid** [comment]
The few that are `Voice=Pass` without a `:pass` dependent look like errors: [EWT](http://universal.grew.fr/?custom=632679c4a8450)

**Comment by nschneid** [comment]
In EWT, missing Voice=Pass:
- [ ] [38 verbs](http://universal.grew.fr/?custom=63d68914764e3) with aux:pass (no subject)
- [ ] [186 verbs](http://universal.grew.fr/?custom=63d69774c40bc) with a passive subject
- [ ] [49 VBN verbs](http://universal.grew.fr/?custom=63d6959d8fae3) that are non-initial conjuncts where the head has Voice=Pass
   * note that auxes are not propagated across coordination in edeps
- [ ] [129 VBN verbs](http://universal.grew.fr/?custom=63d696b3c310c) that are non-initial conjuncts where the head lacks Voice=Pass or a "have" aux
   * may be best to first add Voice=Pass in modifier environments like acl and advcl, then propagate across coordination

**Comment by nschneid** [comment]
Remaining `Voice=Pass` implementation tracked in #290
