### ISSUE TITLE
Features for "some"

### ISSUE THREAD

**Issue by amir-zeldes** [UniversalDependencies/UD_English-EWT#291]
Currently the word "some" is tagged as a determiner, but had no PronType or Definiteness value. I propose making it `PronType=Art` and `Definiteness=Def`. Any objections/alternative thoughts?

**Comment by nschneid** [comment]
`PronType=Ind` as it's indefinite, right? https://universaldependencies.org/en/feat/PronType.html

**Comment by nschneid** [comment]
#230

**Comment by amir-zeldes** [comment]
No, I also had to think twice about this, but actually that page seems to imply that indefinite articles still take PronType=Art (like "a"), and all the examples for PronType=Ind are independent things like "somebody". If I read the guidelines right, then I think the correct solution is to put the indefiniteness into Definiteness=Ind + PronType=Art. Maybe independent "some" (like "I want some") should be PronType=Ind.

**Comment by nschneid** [comment]
"Article is a special case of determiner that bears the feature of definiteness." I read that as they exist primarily/solely to give the NP a definiteness value, i.e. mark it as definite or indefinite.

The English documentation page I linked to gives "some" as an example of `PronType=Ind` without qualification. I suspect it just wasn't implemented for "some" in EWT.

**Comment by nschneid** [comment]
(Yes it's a bit confusing that `PronType=Ind` covers indefinite determiners and doesn't explicitly exclude "a(n)" from its definition, but I take it that the `PronType` values are supposed to be mutually exclusive.)

**Comment by amir-zeldes** [comment]
The fact that the Art list specifically lists "a", and the PronType=Ind list does not list indefinite determiners but focuses on independent pronouns is suspicious for me - to me it suggests that indefinite determiners belong to Art + Definite=Indef (just like "a"). Do you feel that determiner "some" is different from "a"? It is also tagged DT and DET, not PRON...

**Comment by nschneid** [comment]
Maybe @dan-zeman can clarify, but I always understood the articles to be "a(n)" and "the" and nothing else.

**Comment by dan-zeman** [comment]
> I always understood the articles to be "a(n)" and "the" and nothing else.

So did I. For _some_, I would use `PronType=Ind`.

**Comment by amir-zeldes** [comment]
OK, so do you mean it should be PronType=Ind AND Definiteness=Indef, or just PronType=Ind? And can it be added to the PronType documentation?

**Comment by amir-zeldes** [comment]
OK, thanks, I'll implement just `PronType=Ind` in GUM. Leaving open for EWT.

**Comment by nschneid** [comment]
features for DETs were added in #416
