### ISSUE TITLE
Coordinated auxes

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#298]
The validator is giving an error for a coordination analysis of auxes in "may or may not VERB":

```
# sent_id = answers-20111108101906AA2JJqq_ans-0003
# text = There may or may not be snow, depending on local weather conditions.
1	There	there	PRON	EX	_	6	expl	6:expl	_
2	may	may	AUX	MD	VerbForm=Fin	6	aux	6:aux	_
3	or	or	CCONJ	CC	_	4	cc	4:cc	_
4	may	may	AUX	MD	VerbForm=Fin	2	aux	2:aux	_
5	not	not	PART	RB	_	4	advmod	4:advmod	_
6	be	be	VERB	VB	VerbForm=Inf	0	root	0:root	_
7	snow	snow	NOUN	NN	Number=Sing	6	nsubj	2:nsubj|6:nsubj	SpaceAfter=No
```

Should this be allowed?

Treating this as main verb ellipsis ("there [[may \<be snow\>] or [may not be snow]]") seems distinctly unintuitive. It would mean the basic level has `expl(may, there)`, which doesn't look existential.

I suppose in theory another possibility is to treat it like "there may be snow or may not", but that would involve a left-pointing conj(be, may-4).

@dan-zeman

**Comment by nschneid** [comment]
Actually it appears this is already allowed for `cop` dependents ("is or is not"). So I vote to extend that to `aux`. Then we can dispense with the flat coordination analysis seen in [some of these](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61ec40020ea03).

**Comment by dan-zeman** [comment]
Nodes 2 and 4 should be connected via `conj`, not `aux`.

**Comment by nschneid** [comment]
🤦 Thanks. Now to fix the other ones that use the sister analysis....

**Comment by nschneid** [comment]
There are a couple of interesting cases with complex conjuncts:

(1)  Various mitigating actions have been and will be taken

I'm going with

- Various mitigating actions have been [and will be] taken
  * `aux(taken, have)`, `aux(taken, been)`, `conj(been, be)`, `aux(be, will)`

(2) ... who should be or has the right to be the Santa of nuclear weapons

I'm going with

- who should be<sub>14</sub> [or has the right to be<sub>20</sub>] the Santa of nuclear weapons
  * `aux(Santa, should)`, `cop(Santa, be-14)`, `conj(be-14, has)`

If we were doing a phrase structure/constituency analysis I'd group the initial auxes together: [have been] and [will be], [should be] or [have the right to be]. But the UD way is probably to analyze it such that the second part of the coordination can be removed without altering the rest of the sentence.

**Comment by nschneid** [comment]
Similarly for:

- we will not, [nor will an affiliate,] have another agreement in place
- which has been [and will again be] presented
