### ISSUE TITLE
Check comparatives

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#299]
I think it is necessary to do a systematic review of comparative constructions in EWT. A lot of the attachments of the 2nd part of the comparison have been updated to meet the [v2 guidelines for comparatives](https://universaldependencies.org/u/overview/specific-syntax.html#comparatives), but not all of them.

e.g.
- ["more/less X than Y" where *than-Y* is not headed by the comparative](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61ed871012894)
- ["PP than PP"](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61f563005fdea) (from #101)

Similarly, it would be good to investigate sufficiency constructions ("enough", "too", etc.), which are not yet officially documented (UniversalDependencies/docs#672) but presumably should use a similar structure.

**Comment by nschneid** [comment]
- [ ] [sufficiency/excess constructions where `advcl` should be moved to main ADJ/ADV](https://universal.grew.fr/?custom=64fea720cd50c)

**Comment by nschneid** [comment]
Related: #423

**Comment by nschneid** [comment]
than+PP: 1 error in GUM (the No/No instance of https://universal.grew.fr/?custom=652ae2116d99d)

**Comment by amir-zeldes** [comment]
>than+PP: 1 error in GUM (the No/No instance of https://universal.grew.fr/?custom=652ae2116d99d)

Fixed upstream, thanks!
