### ISSUE TITLE
Sentence-initial conjunction attached to 2nd conjunct

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#307]
...(or parataxis), creating nonprojectivity. Not sure how this happened.

- [EWT](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=620b0b5b188a7)
- [GUM](http://match.grew.fr/?corpus=UD_English-GUM@dev&custom=620b0b6fa4f0b)

**Comment by amir-zeldes** [comment]
Weird. Will fix for GUM!

**Comment by amir-zeldes** [comment]
While looking at these I noticed some ADV which are `obl:tmod` (should be advmod?):

http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=620bbc6638994

**Comment by amir-zeldes** [comment]
And a couple of adjacent premodifier acls (should be amod?):

http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=620bbcc4bdf0a

**Comment by nschneid** [comment]
> While looking at these I noticed some ADV which are `obl:tmod` (should be advmod?):
> 
> http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=620bbc6638994

"all the sudden" isn't in my dialect (cf. "all of a sudden")—not sure if "sudden" is a noun or adverb there. Agree about `advmod` for the others. Note that in https://arxiv.org/pdf/2108.12928.pdf example (32) we proposed `obl:tmod` for the modifier of "ago".

**Comment by amir-zeldes** [comment]
If it's not tagged ADV that's fine; but I think whatever is tagged ADV should be attached as advmod rather than obl:tmod

**Comment by nschneid** [comment]
"all the sudden" noted in UniversalDependencies/docs#863; others corrected
