### ISSUE TITLE
use X to Y

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#311]
With the transitive verb "use", should the infinitival clause be considered a purpose clause adjunct (`advcl`) or an `xcomp`? Corpora are inconsistent:

http://universal.grew.fr/?corpus=UD_English-EWT@dev&custom=622945e06dc65&clustering=rel.label

I think this can be interpreted as a purpose clause so I guess I lean toward `advcl`, but certainly "use" is often collocated with a purpose of use; it is more *semantically* core than for most verbs.

**Comment by aryamanarora** [comment]
So `xcomp` takes a subject from an external argument, but in "use X to Y", X is a non-core (i.e. `obl`) instrumental argument to the very Y.

* I used the money to buy a house.
* =I bought a house [with the money]<sub>obl</sub>.

That doesn't seem to satisfy `xcomp`.

**Comment by nschneid** [comment]
Good point. I misunderstood your post at first. Let me bold the key word

> So `xcomp` takes a **subject** from an external argument

`xcomp` is incorrect in "I want to use this opportunity to welcome Brian Ryner to Google!" because it would imply that the opportunity is the implied subject of welcoming, not just any dependent of welcoming.

So there are about 20 incorrect examples in EWT.

**Comment by nschneid** [comment]
Actually...well...is `xcomp` of a transitive verb required to project the matrix object? That is certainly the typical case (e.g. "I told John to leave."). The [`xcomp` guidelines](https://universaldependencies.org/u/dep/xcomp.html) say

> (normally by the object of the next higher clause, if there is one, or else by the subject of the next higher clause)

"normally"—is "use" an exception?

**Comment by amir-zeldes** [comment]
I usually tell annotators as sufficient tests to use `advcl` if you can insert "in order" and to use `xcomp` if the infinitive is required (not omittable). So:

  * I used a hammer to do it ->advcl (I used hammer in order to do it; I used a hammer)

Compare: 

  * I used to go ->xcomp (cf. * I used in order to go; * I used)

I don't recall if we've had a case where these criteria conflict (sometimes you can insert "in order" but it's a bit awkward)

**Comment by nschneid** [comment]
http://universal.grew.fr/?custom=638cbabe508f6

The ones in the upper left quandrant (with nsubj but no obj) are the past "used to" which should remain xcomp; and the others are the purpose clauses which should be changed to advcl.

**Comment by nschneid** [comment]
1 GUM error: http://universal.grew.fr/?custom=638cbc293e219

**Comment by amir-zeldes** [comment]
fixed in GUM, thanks!
