### ISSUE TITLE
Check: transitive verbs whose matrix subject is also E:nsubj:xsubj

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#312]
- [x] EWT: http://universal.grew.fr/?corpus=UD_English-EWT@dev&custom=622961a44f3df (Mostly due to relative clauses. I suspect most of these are errors.)
- [ ] GUM: http://universal.grew.fr/?corpus=UD_English-GUM@dev&custom=6229f7a12fed6

**Comment by nschneid** [comment]
a few more worth a look: http://universal.grew.fr/?corpus=UD_English-EWT@dev&custom=6229630a71750

**Comment by nschneid** [comment]
Fixed the EWT ones. @amir-zeldes is this a limitation of the GUM enhancer?

**Comment by amir-zeldes** [comment]
Is what a limitation of the GUM enhancer? 

The first few GUM examples look correct to me.

**Comment by nschneid** [comment]
See the highlighted E:nsubj:xsubj. I think the issue is that when the matrix verb has a direct object and xcomp with coordination, the first conjunct receives the correct enhanced subject but the others do not.

Easiest to see in the shorter sentences, e.g. "I called it Character, walks and words."

**Comment by nschneid** [comment]
The enhanced attachments of "I" to tokens 6 and 8 are superfluous.

**Comment by amir-zeldes** [comment]
Oh, I see - I thought there was a missing edge. Just fixed it in the enhancer script, will push a correction.
