### ISSUE TITLE
Tricky ellipsis with coordination

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#318]
I found [my initial selection] [satisfactory] but <sub>found</sub> [the wine flight we chose] [to be poorly composed]. (reviews-101398-0005)

I suppose the closest of the [documented ellipsis examples](https://universaldependencies.org/u/overview/specific-syntax.html#ellipsis) is "She gave the dog a bone, and the man a flower" (conj(gave, flower), orphan(flower, man)). So I'm guessing:

obj(found, selection)
xcomp(found, satisfactory)
conj(found, composed)
orphan(composed, flight)

with an empty node in the Enhanced layer to make things more logical.

**Comment by sebschu** [comment]
Nice example :) And yes, I'd also use orphan here!

**Comment by amir-zeldes** [comment]
Agreed on orphan, but shouldn't the conj go into the subject? I mean, subject should be promoted before xcomp, right? I would do:

obj(found, selection)
xcomp(found, satisfactory)
conj(found, flight)
orphan(flight, composed)

And the appropriate empty node + edeps.

**Comment by sebschu** [comment]
Yes, I overlooked that. _flight_ is the head of an object but that should still be promoted before xcomp.

**Comment by nschneid** [comment]
Documented with an example:
<img width="374" alt="image" src="https://user-images.githubusercontent.com/985263/166306664-9ece74e5-157b-46ff-b064-b3d5c4ed7291.png">
