### ISSUE TITLE
"alone": ADJ vs. ADV

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#320]
Originally raised in UniversalDependencies/docs#855:

Should "alone" be considered an ADV or depictive ADJ in "I did it alone"?

[EWT](http://universal.grew.fr/?custom=6275721a8ccca) and [GUM](http://universal.grew.fr/?custom=6275722c4e9e0) both have ADJ and ADV instances of "alone".

Per the new policy on optional depictives, this would not affect the tree structure, but the deprel would differ: `advmod` (ADV) vs. `advcl` (depictive ADJ).

https://simple.wiktionary.org/wiki/alone (based on CGEL) is one point of reference.

**Comment by amir-zeldes** [comment]
I think "I did it alone" is ADV, and the CGEL based wiki seems to agree. I think the GUM cases reflect this distribution, with 24 ADV and only two ADJ:

  * ...is alone/ADJ (concurs with CGEL)
  * find oneself alone/ADJ/xcomp (i.e. find oneself [one-is-]alone)

(there are 2 errors of ADV for ADJ in predicate position, which I can fix)

**Comment by nschneid** [comment]
Fancier view: http://universal.grew.fr/?custom=627598c24250f

It looks pretty straightforward actually—ADJ for "be alone" and predicative uses like "leave alone" (xcomp); ADV/advmod for manner and focus modifier uses.

The hard one is "put it alone in a breeding tank"—I guess this is a [resultative](https://universaldependencies.org/u/overview/complex-syntax.html#secondary-predicates), like "paint the house blue", so xcomp?

**Comment by amir-zeldes** [comment]
Agreed. I also think "let alone", although 'fixed' underlyingly belongs to this type, so pos should be JJ. GUM Reddit has three cases and regular has one, but they were inconsistent, so I will consolidate to ADJ (but keep fixed, not xcomp, which seems sensible).
