### ISSUE TITLE
"if" meaning "whether" should mark ccomp not advcl

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#325]
With the verbs "see", "check", "determine": http://universal.grew.fr/?custom=62a41bf4e405b

**Comment by nschneid** [comment]
(also one error in GUM)

**Comment by nschneid** [comment]
Verbs where "if" is attested with ccomp—can be used to expand out the first query: http://universal.grew.fr/?custom=62a41cfc48e1f

**Comment by amir-zeldes** [comment]
Fixed for GUM, thanks for reporting!

**Comment by nschneid** [comment]
- [ ] Better query: [EWT](http://universal.grew.fr/?custom=62a956b652f17), [GUM](http://universal.grew.fr/?custom=62a9571fc691b)

"know" is the biggest driver, and some of these seem ambiguous ("let me know if you want more information"—"if" could be replaced with "whether" suggesting `ccomp`, or the phrase can be fronted suggesting `advcl` and a conditional interpretation)

**Comment by amir-zeldes** [comment]
Will fix GUM errors, thanks!

**Comment by nschneid** [comment]
There are a few "if"-marked ccomps/csubjs of non-interrogative-taking predicates. Do complement-marking uses of "if" always have the meaning of 'whether', or should we say it can mark an extraposed element in cases like

- I know that it helps if you've been tracking your period so you know your cycle.

"That" is an acceptable paraphrase of "if". It would be grammatical but odd to front the if-clause (why use "it" in that case?).

The "whether" test is easy to apply, though. If we allow the above to be csubj, then we have to decide borderline cases like

- I would appreciate it if you could get this one fixed today

where it is quite natural to front the if-clause.

(I checked CGEL and don't see a discussion of extraposition vis-a-vis "if": they treat "if" as having either conditional-adjunct or interrogative-complement use. These examples may be evidence of grammaticalization of the conditional meaning as non-interrogative complementizer.)

**Comment by nschneid** [comment]
I forgot about the substitution test for extraposition. The if-clause cannot substitute for "it" in the first example. In the second it can, in casual speech (for me at least):

- (3) I would appreciate if you could get this one fixed today.

If (3) is grammatical for you, then we have to acknowledge non-interrogative complementizer "if", because the if-clause cannot be fronted. But that's different from the "it" case (if (3) is grammatical why go to the trouble of extraposition which just adds an optional "it"?).

So let's treat (3) as a special case and go with advcl for non-interrogative if-clauses where possible.

**Comment by nschneid** [comment]
EWT advcl cases for manual review: http://universal.grew.fr/?custom=638b8810d828b
