### ISSUE TITLE
Lemma of "rights"

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_English-EWT#328]
EWT uses "human rights" lemmatized as "rights", GUM uses "right"  Original EWT lemmas are based on CoreNLP lemmatizer, which leaves it as "rights" in all circumstances

Can we unify those labels for future versions?  I can easily update CoreNLP to do whatever the final decision is.

@amir-zeldes

**Comment by nschneid** [comment]
I would follow WordNet/GUM and lemmatize as "right". https://en-word.net/lemma/right

Also, in EWT I noticed a token of "Springs" that was not lemmatized to "Spring". I think it should be.

**Comment by AngledLuffa** [comment]
I agree, but `rights` was deliberately set this way in CoreNLP

**Comment by amir-zeldes** [comment]
Yeah, that sounds right, you can say singular "a basic human right", and "rights" is the plural of that.

**Comment by nschneid** [comment]
Can we close this?
