### ISSUE TITLE
English-specific validation rules

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#333]
Many can be derived from issues in the issue tracker.

For example, consistency in passive constructions #289.

Existential "there" is another case, with the following implications:

- X.xpos=EX  <=> X.deprel=expl & X.lemma=there
- X.xpos=EX => X.upos=PRON

**Comment by amir-zeldes** [comment]
There are a lot of validations for UD English dependencies in the GUM buildbot, most of which can be found in the code starting here: (POS/lemma and other layers are also checked elsewhere)

https://github.com/amir-zeldes/gum/blob/master/_build/utils/validate.py#L627

Probably many of these can be re-implemented outside of the buildbot, along with other consistency checks (for example, the buildbot flags minority lemmas for each form+POS combination, which, outside of some known exceptions, usually map to unique lemmas)

**Comment by nschneid** [comment]
Some lemmas to enforce: "TV" (`[Tt]\.?[Vv]\.?`), "a.m." and "p.m." (#334)

**Comment by nschneid** [comment]
X[Abbr=Yes] => X.lemma<>X.form.lower()

**Comment by amir-zeldes** [comment]
> X[Abbr=Yes] => X.lemma<>X.form.lower()

This would rule out abbreviations whose standard form is the abbreviated one (e.g., etc.)

**Comment by nschneid** [comment]
Those are not `Abbr=Yes` in EWT at present. Perhaps they should be; in fact "etc." appears as an example on the [`Abbr` page](https://universaldependencies.org/u/feat/Abbr.html).

**Comment by nschneid** [comment]
X[lemma=re"[0-9]+/[0-9]+(/[0-9]+)?"] => X.upos=NUM

**Comment by amir-zeldes** [comment]
> Those are not Abbr=Yes in EWT at present.

Huh, I hadn't realized! They are Abbr in GUM, and that seems right to me.

**Comment by nschneid** [comment]
X[lemma=what,xpos=WDT] <=> X[lemma=what,deprel=det|det:predet]

**Comment by nschneid** [comment]
X-[E:ref]->W => W[PronType=Rel] (possibly with rare exceptions) - [3 GUM errors](http://universal.grew.fr/?custom=62ec66d50903d)

X-[E:ref]->W => X-[acl:relcl|advcl:relcl]->* (possibly with rare exceptions) - [1 GUM error](http://universal.grew.fr/?custom=62ec6781ca0fe)

**Comment by amir-zeldes** [comment]
Thanks for catching in GUM, will fix

**Comment by nschneid** [comment]
Decided not to implement checks for lemmas "TV", "a.m."/"p.m." based on regexes—now that these are consistent in the data, hopefully any exceptional annotations will be flagged as anomalous by the lemma frequency heuristics.

> X-[E:ref]->W => W[PronType=Rel] (possibly with rare exceptions) - [3 GUM errors](http://universal.grew.fr/?custom=62ec66d50903d)
> 
> X-[E:ref]->W => X-[acl:relcl|advcl:relcl]->* (possibly with rare exceptions) - [1 GUM error](http://universal.grew.fr/?custom=62ec6781ca0fe)

Not implementing this check for now, though there are checks in the opposite direction (ensuring E:ref is present where necessary). I see 4 GUM errors: https://universal.grew.fr/?custom=652acf957fe00

**Comment by amir-zeldes** [comment]
I see the issue, it's relative pronouns that are governed by a ccomp or xcomp child of the acl:relcl, so things like:

  * books which/WDT you think/acl:relcl I read/ccomp

This should fix it, I'll add it to the morphology depedit:

```
xpos=/WDT/;func=/.*:relcl/;func=/[xc]comp/	#2>#3>#1;#1.*#2.*#3	#1:morph+=PronType=Rel
```
