### ISSUE TITLE
Adding the advcl:relcl subtype

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#346]
It has been decided that relative clauses modifying entire clauses, not nominals, should no longer be `acl:relcl`: UniversalDependencies/docs#886

This issue is to track English-specific implementation

**Comment by nschneid** [comment]
@amir-zeldes How are you handling edeprels given the type mismatch of "which" (PRON) and its clausal antecedent? I am thinking nsubj/obj for "which" at the basic level and csubj/ccomp as the enhanced dependency for its antecedent.

**Comment by nschneid** [comment]
some more GUM hits (as well as false positives) in:
http://universal.grew.fr/?custom=62e9b21aa045b
http://universal.grew.fr/?custom=62e9b7f6c21e5
http://universal.grew.fr/?custom=62e9b9167881c

**Comment by nschneid** [comment]
Was surprised how few adverbial `acl:relcl`s were in EWT—turns out most of them were `parataxis`.
Need to go through:
- [ ] http://universal.grew.fr/?custom=62e9b999cd2e5
- [ ] http://universal.grew.fr/?custom=62e9baddb5ce8

**Comment by nschneid** [comment]
- [ ] http://universal.grew.fr/?custom=62eaac2fdaf97: "which" marked as `PronType=Int` (the default for WH-pronouns) but not appearing in a typical relative clause context. Some are errors (`ccomp` should be `advcl:relcl`); some are relative clauses as full sentences, so should be `PronType=Rel`; others are truly interrogative. I will go through them and mark the truly interrogative ones with a MISC feature `ManuallyChecked=PronType`.

**Comment by amir-zeldes** [comment]
> some more GUM hits (as well as false positives) in: http://universal.grew.fr/?custom=62e9b21aa045b http://universal.grew.fr/?custom=62e9b7f6c21e5 http://universal.grew.fr/?custom=62e9b9167881c

Thanks for reporting, there were two instances I'd missed in there!

**Comment by amir-zeldes** [comment]
> @amir-zeldes How are you handling edeprels given the type mismatch of "which" (PRON) and its clausal antecedent? I am thinking nsubj/obj for "which" at the basic level and csubj/ccomp as the enhanced dependency for its antecedent.

Yeah, that looks good, just implemented it. I also saw cases of obl ->advcl and even csubj:pass once...

BTW, not exactly related but since I'm looking at the (e)deps, did we settle on flip-flopping when/where back to advmod where they were previously mark? If so, do you have an exhaustive list of the items this applies to? I have:

`when|where|whither|whence|while|why`
