### ISSUE TITLE
"cut short" (ADJ particle)

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#351]
I think it is standard to term this a verb-particle construction despite "short" being an adjective. E.g.:

_Originally posted by @jnivre in https://github.com/UniversalDependencies/docs/issues/203#issuecomment-253806928_
> I don't think there is a universal preference for ADP over ADV. This has to be settled on a language-specific basis. Verb particles can even be ADJ sometimes ("cut short"). The basic idea is that we regard "verb particle" as a syntactic function, not a part-of-speech category. Different languages allow different word classes to have this function (none at all in most languages).

EWT uses `compound:prt`; GUM uses `xcomp` and the GUM validator requires particles to be RP.

I don't see this case addressed in PTB tag guidelines. Arguably "short" could be RP when used as a particle, but with ADJ as its UPOS.

(Why is this not quite the same as a standard secondary predicate adjective (xcomp)? With a transitive verb-particle construction the particle is mobile with respect to the direct object: _cut my friend short/off_, _cut short/off my friend_—unless the object is a light pronoun: _*cut short/off it_. With a standard obligatory secondary predicate, only heavy NPs would be expected to go after the adjective: _made my friend angry_, not _*made angry my friend_, at least not in contemporary English.)

**Comment by amir-zeldes** [comment]
I think there is precedent in PTB though: it occurs twice in WSJ, both times annotated as a secondary predicate (though once tagged JJ and once RB), and twice more in OntoNotes outside WSJ, both tagged JJ. The semantics also fits since there is a secondary predication: something is cut short, and then it is short as a result (expected in xcomp arg sharing).

**Comment by nschneid** [comment]
The semantics argument could be made for non-idiomatic verb particles in general, though.

But I don't mind calling it JJ/xcomp if you think that will be less surprising to people.

**Comment by amir-zeldes** [comment]
Yeah, I think that would be better, plus there are morphological reasons to prefer that when you have comparative forms like:

  * These dudes are mad the sketch was cut shorter than they wanted
  * While our time was cut shorter than we anticipated, we look back on the memories...

**Comment by nschneid** [comment]
Ah yeah that's a good argument against RP
