### ISSUE TITLE
Implement "etc." as NOUN

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#353]
UniversalDependencies/docs#820

**Comment by amir-zeldes** [comment]
I'll add this to the GUM buildbot as well

**Comment by nschneid** [comment]
Since we're going with NOUN I'm assuming NN and Number=Sing

**Comment by nschneid** [comment]
and might as well add Abbr=Yes though we haven't done that yet for other standard abbreviations in EWT

**Comment by amir-zeldes** [comment]
> Since we're going with NOUN I'm assuming NN and Number=Sing

No, I would not assume that we can just change an established PTB xpos guideline (otherwise we will create a divergence where in UD xpos it's NN and in LDC xpos datasets it's FW). I'd just leave it as xpos=FW, that's not a UD thing anyway.

**Comment by nschneid** [comment]
Hmm OK, I guess I'm confused why we decided not to treat it as foreign in UD if that was a well-established Penn guideline. But I can change it back.
