### ISSUE TITLE
"X is as follows"

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#354]
What is the correct structure for sentences of the form:

X is as follows
X is as described
X is as requested
That is as I thought.

Right now, this is analyzed with "be" as root, which we are mostly eliminating (#310). Should it be an exception, or is "be" a copula? If so, I suppose the subject should be `nsubj:outer`; "That is as I thought" shows that there can be an inner subject after "as".

**Comment by nschneid** [comment]
FWIW, CGEL p. 1150:

<img width="371" alt="image" src="https://user-images.githubusercontent.com/985263/192121691-2617295f-8af6-4764-bffb-7f6c6e032a52.png">

**Comment by amir-zeldes** [comment]
Yeah, I would not treat "be" as the main verb there (what would be the deprel to "follows"?). I think it's plain old copula predication where the predicate is a clause.

**Comment by nschneid** [comment]
And the same for "X is like Ying" I presume? http://universal.grew.fr/?custom=63322b6aeceb1

**Comment by nschneid** [comment]
Looks like there are a bunch of errors with "be + SCONJ + clause"—opened a separate issue #357

**Comment by amir-zeldes** [comment]
> And the same for "X is like Ying" I presume? 

Yes, I'd say so!
