### ISSUE TITLE
advcl attaching to copula for "X is because Y", "X is like Ying", etc.

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#357]
- [EWT](http://universal.grew.fr/?custom=634622c05ff27): 50 hits
- [GUM](http://universal.grew.fr/?custom=6344b1b6bf298): 18 hits

Many of these should have a clause as copular predicate (Y) and outer subject (X).

**Comment by amir-zeldes** [comment]
Thanks for catching, will fix GUM cases

**Comment by nschneid** [comment]
We have cases like "Our first diagnosed EPM horse was back when there was no treatment in the US"

or, to write a cleaner sentence: "The diagnosis was when there was no treatment".

Is "when there was no treatment" a free relative or an advcl? Compare: "The diagnosis **happened** when there was no treatment."

Note that you cannot say:

*The diagnosis was a time when there was no treatment.

Which might be expected of a free relative, e.g. "Tomorrow is when you should leave" / "Tomorrow is the time when you should leave".

If this is an advcl, should "was" be AUX promoted to main predicate?

**Comment by amir-zeldes** [comment]
I'm sorry, I'm not sure what that means. It could be a vocative + imperative or it could be a third person optative (like "long live the king", or "may the Force be with you", i.e. the wish for a third person type). Assuming you mean the latter kind of subjunctive, and this means "may power reside there, where power lies", then I would do:

root(where)
nsubj(where, Power)
cop(where, be)
advcl:relcl(where, lies)
nsubj(lies, power)

**Comment by nschneid** [comment]
I'm not sure what it means either. (https://twitter.com/complingy/status/1579625235980365824) It seems like an attempt to coin a proverb couched in archaic language.
