### ISSUE TITLE
advcl:relcl for relative clause headed by an ADV

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#361]
A number of `acl:relcl` instances are headed by ADJs—these look OK as they are coerced into nominals ("the last", etc.).

But per the [new guidelines](https://universaldependencies.org/en/dep/acl-relcl.html#free-relatives), `advcl:relcl` should be used by [ADV-headed free relatives](http://universal.grew.fr/?custom=6339a39c9fc55) ("where you work").

**Comment by amir-zeldes** [comment]
I'm not sure that guideline should apply universally to ADV-headed free relatives: in the "go" example, the "where" really serves an adverbial function. But if it's standing in for a direct object, for example, I would still expect acl:relcl, for example:

  * I hate where/obj I live/acl:relcl

Here "where I live" is effectively a unary derivation converting the clause into an NP, so I think it's more intuitive to use `acl:relcl`, just as we give "where" the typically norminal label of `obj` (like you say, when the head is coerced into a nominal).

I agree that for predicative adjectives or true adverbs we should use advcl, for example:

  * It was delicious/ADJ/root, which delighted/advcl:relcl all the guests.

**Comment by nschneid** [comment]
We already discussed this—I see the issue but the group decided it was simpler to use `advcl:relcl` based on a shallow look at the head being ADV. For cases like "go where/advmod you want", a full coercion analysis would have to explain that the where/ADV projects an NP with relative clause modfier which is then used adverbially (in which case the correct deprel would be obl:npmod, not advmod). UD doesn't give us the luxury of expressing all the levels of coercion, though, so we prefer adverb-style deprels where possible.

**Comment by amir-zeldes** [comment]
> We already discussed this—I see the issue but the group decided it was simpler to use advcl:relcl based on a shallow look at the head being ADV

Really? I remember we discussed things like "John came which annoyed/advcl:relcl me", but if we had agreed to base the deprel purely on parent POS, then wouldn't that contradict what you propose for "the last" above?

I generally thin we should not be making deprels totally and automatically depend on parent POS - there is a reason those are two separate fields, and just as an ADJ can be nominalized but still tagged morphologically as ADJ, so can ADV be wrapped in a noun-y structure.

**Comment by nschneid** [comment]
Yes, we discussed in the 8/23 meeting. I agree we should not have a general rule that we ignore coercion or that all deprels are purely based on POS. But in the tricky case of adverb-headed free relatives, we decided it was simplest to take our cue from the POS.

**Comment by amir-zeldes** [comment]
Hm, this is fairly trivial to engineer for the WH cases... I don't really see the value, but it's no better or worse than having them all as acl:relcl (as long as they're all the same, we're doing injustice to one of the classes). What about non-WH ones? Or ones with a WH modifying an ADJ?

  * Hapupu is a special place, and somewhere that you will want to tell/???:relcl others about
  * I wonder how long it will take/???:relcl
  * Sit anywhere you like/???:relcl (has a wh in it, but not xpos=WRB based on PTB)

**Comment by nschneid** [comment]
I think it's simplest to include all ADVs—so `advcl:relcl` for "somewhere" and "anywhere".

The second one is an interrogative complement clause ("wonder" doesn't take NP objects).

**Comment by amir-zeldes** [comment]
Whoops, nice catch (paradigm example of a complement clause, how embarrassing!)

But it's easy to find non-wonder-like ones too, where "how long" is a duration type object NP:

  * I don’t know how long we’ll be (=I don't know the amount of time that it will take us)

For "somewhere" above, I feel like this heuristic basically makes the wrong call, since it's clearly a coordinate NP predicate (it is a special place and somewhere that...). 

But like I wrote above, if we just make them all be advcl:relcl, it's not worse than making them all acl:relcl, and currently at least in GUM that distinction is not being made one way or the other.

**Comment by nschneid** [comment]
In reality I suspect "somewhere" has both adverb-like and noun-like properties. But "If a word is tagged as ADV, call its relative clause dependent `advcl:relcl`" is the most straightforward policy I can think of. :) Maybe some ADJs, too, but most of the EWT ADJs heading a relative clause were clear cases of nominal coercion ("the last"), so I left `acl:relcl` for those.

**Comment by amir-zeldes** [comment]
OK, I can live with this I guess.
