### ISSUE TITLE
"There seems to be an issue"

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#366]
What is the correct structure for such a sentence? It's not consistent (also "there needs to be/is going to be/is supposed to be"): [EWT](http://universal.grew.fr/?custom=6342406b17bfa), [GUM](http://universal.grew.fr/?custom=634240aebe84c)

[expl guidelines](https://universaldependencies.org/u/dep/expl.html) show that the expletive *there* attaches to the matrix verb.

One approach that makes sense to me is to treat "be" as a full VERB attaching as `xcomp`. GUM does this for all 4 tokens. EWT is all over the place. I guess the EWT ones should be corrected.

In that case the nominal ("an issue") should be the nsubj of "be". There is one erroneous GUM result where this is not the case.

**Comment by nschneid** [comment]
check to make sure all EWT cases have been handled: http://universal.grew.fr/?custom=63424dfb31223

**Comment by nschneid** [comment]
Now fixed in EWT - just the 1 GUM token: http://universal.grew.fr/?custom=6342694782244

**Comment by amir-zeldes** [comment]
Thanks for catching, will fix
