### ISSUE TITLE
ADJ/ADV + "enough"

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#367]
E.g. "big enough", "easily enough". What is the correct structure? I see

- enough as advmod of ADJ: 16 [EWT](http://universal.grew.fr/?custom=6342e4f92a1c0), 14 [GUM](http://universal.grew.fr/?custom=6342e4bce82ba)
- enough as advmod of ADV: 1 [EWT](http://universal.grew.fr/?custom=6342e5d83381c), 4 [GUM](http://universal.grew.fr/?custom=6342e60bcd6d0)
- ADJ as amod of enough: 13 [EWT](http://universal.grew.fr/?custom=6342e53505857), 0 GUM
- ADV as advmod of enough: 6 [EWT](http://universal.grew.fr/?custom=6342e554d65b5), 1 [GUM](http://universal.grew.fr/?custom=6342e5a8a8f61) ("just enough"—I suppose "just" is a degree modifier of "enough")

Related: UniversalDependencies/docs#672

**Comment by amir-zeldes** [comment]
I think enough is the modifier - equivalent to "sufficiently big" etc.

**Comment by nschneid** [comment]
Fair enough :) This means "enough" should be ADV in this construction, unlike "I have enough books".
