### ISSUE TITLE
Inconsistent UPOS for anyone, someone and everyone across English treebanks

### ISSUE THREAD

**Issue by bguil** [UniversalDependencies/UD_English-EWT#372]
These 3 lemmas (*anyone*, *someone* and *everyone*) are annotated inconsistently (either `NOUN` or `PRON`) in different English treebanks.

In 2.10 data, the UPOS tags used are: 

| Corpus | `NOUN` | `PRON` |
|--------|------:|------:|
| [UD_English-GUM](http://universal.grew.fr/?custom=634a7e73d6b97) |   83  | 0 |
| [UD_English-ParTUT](http://universal.grew.fr/?corpus=UD_English-ParTUT@2.10&custom=634a7e73d6b97) |   0  | 40 |
| [UD_English-PUD](http://universal.grew.fr/?corpus=UD_English-PUD@2.10&custom=634a7e73d6b97) |   8  | 0 |
| [UD_English-LinES](http://universal.grew.fr/?corpus=UD_English-LinES@2.10&custom=634a7e73d6b97) |   0  | 74 |
| [UD_English-EWT](http://universal.grew.fr/?corpus=UD_English-EWT@2.10&custom=634a7e73d6b97) | 3| 265 |

**Comment by nschneid** [comment]
In PTB they are considered nouns, but according to https://universaldependencies.org/u/pos/PRON.html they should be considered PRON in UD. Since this is a closed class I don't see that divergence as a problem.

See also #230 re: feats

**Comment by nschneid** [comment]
Full table at https://universaldependencies.org/en/pos/PRON.html#indefinite-pronouns

EWT query for all except "no one": http://universal.grew.fr/?custom=634adbc7a092f

I will fix the 5 errors in EWT.

**Comment by amir-zeldes** [comment]
I'm not passionate about upos, if those guidelines are meant to be/can be made consistent across languages, let's do it. I'll fix GUM/Reddit.

**Comment by amir-zeldes** [comment]
> Full table at https://universaldependencies.org/en/pos/PRON.html#indefinite-pronouns

Looking at that page I think 'everything/one' should not be PronType=Ind, it should be PronType=Tot, no?

**Comment by nschneid** [comment]
I'm not familiar with "indefinite" versus "total" pronouns being a distinction in English grammar. See [this table](https://en.wikipedia.org/wiki/Indefinite_pronoun#Table_of_English_indefinite_pronoun_usage), for example. @dan-zeman was that intended mainly for determiners?

**Comment by amir-zeldes** [comment]
That table has a column 'universal' - I think that's what is intended here. GUM uses `Tot` for things like "all, each":

https://gucorpling.org/annis/#_q=UHJvblR5cGU9IlRvdCI&_c=R1VN&cl=5&cr=5&s=0&l=10

**Comment by nschneid** [comment]
OK I think this is fixed for EWT and GUM (the treebanks maintained at Georgetown). Consider opening an issue in the repo for PUD.
