### ISSUE TITLE
Tagging and features for "one"

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#373]
According to the PTB tagging guidelines, *one* should be

- CD by default, even when not a prenominal modifier, e.g. _one of the best reasons_, BUT
- a pronoun if referring to a generic individual (roughly 'a person')
- NN(S) "if it could be pluralized or modified by an adjective", and in _another one_
   * shouldn't this include *this one*, *which one*, *a later one*, etc.? Currently some of these are tagged as NUM/CD.
   * *one* as head of `det`: [EWT](http://universal.grew.fr/?custom=634c15bdaf4f5), [GUM](http://universal.grew.fr/?custom=634c139b440c7). I'm not sure NUM/CD is correct for any of these.
   * *one* as head of `amod` but not `det`: [GUM](http://universal.grew.fr/?custom=634c160bf063d) has some NUM/CD tokens (all are NN(S) in EWT)
   * remaining uses of *one*: [EWT](http://universal.grew.fr/?custom=634c1683e2639), [GUM](http://universal.grew.fr/?custom=634c16bc6d5f1)

Features:

- `PRON` *one*
    * generic individual:  I suppose `Gender=Com|Number=Sing|Person=3|PronType=Prs`. Not sure there's a good feature to indicate genericity.
    * in "no one": `Number=Sing|PronType=Neg` (#372)
- `NOUN` *one*: just a `Number` feature, I assume
- `NUM` *one*: I assume these should all be `NumType=Card`

Related: #123, #183 ("one another")

**Comment by amir-zeldes** [comment]
All OK by me except 'Gender=Com', which is not otherwise used in English ATM. Unless we plan a broader campaign to include it in various places, I think adding it just for this item is confusing. I would just leave it genderless for now.

**Comment by nschneid** [comment]
Are there other places where it would make sense? I thought gender in English was just for 3rd person singular pronouns (and possibly who(m)(ever) to contrast with which(ever)).

**Comment by amir-zeldes** [comment]
Not sure, but if there is no other relevant word, then I think not including it on 'one' is the way to go.  There are many words with generic meaning/indeterminate gender, so having this unique feature value just on this word isn't worth it IMO - it's not really an agreement category.

**Comment by nschneid** [comment]
It's an agreement category as much as masculine and feminine for non-generic 3sg pronouns, right? I.e. you wouldn't use "one" to refer to a generic inanimate object, only a generic *person*.

**Comment by nschneid** [comment]
Although there is an argument to be made that if we are putting in features for animacy, we should do so as well for indefinites pronouns: -one/-body (Gender=Com) vs. -thing (Gender=Neut). Maybe this level of detail will just confuse people.

**Comment by amir-zeldes** [comment]
Yeah, since this never 'agrees' with another verb, noun etc. I would just leave it alone.

**Comment by nschneid** [comment]
OK. Can we enforce a rule that "one" as NUM/CD cannot have `det` or `amod` dependents?

**Comment by amir-zeldes** [comment]
No det seems in keeping with PTB guidelines, I can't imagine an exception to it. GUM has only 2 exceptions to amod (and an error I just fixed), which are for post nominal amods, like:

  * A popular option, and **one/CD good** for your health too, is by sea kayak

What's weird about it is that according to PTB, a postnominal relative clause would not cause us not to tag it as CD. So I feel a bit weird tagging it as NN, even though it's pretty clear it's just a heavy extraposed amod (due to "good for your health" having a PP dependent on the adjective). What do you think, is it weird to change that to NN when the following stays CD:

  * one/CD that was made with the American public in mind

**Comment by nschneid** [comment]
> * one/CD that was made with the American public in mind

Couldn't that be pluralized: 

- The most popular options, ones that were made with the American public in mind, ...

I think that qualifies it as NN per PTB.

**Comment by nschneid** [comment]
"One" can have a similar meaning whether it is CD or NN, which is why I find the PTB distinction tricky. I think the partitive construction is relevant—if you're willing to rephrase a partitive as a non-partitive or vice versa it changes the judgments. But I'm not sure partitive always implies CD (what if it is "the last one of the lost jewels"?). One of the places where the minimal nature of PTB guidelines is frustrating.

FTR, CGEL discusses two kinds of "one" starting on p. 1513, but I think they draw a somewhat different boundary than PTB.

**Comment by amir-zeldes** [comment]
Yeah, I'll be honest this pos distinction in PTB is not very convincing, I just want to stay consistent with it as best as possible, and drawing a line in the sand around a determiner actually being realized there seemed simplest. 

So let's say presence of `det` or `amod` mandates `NN`, but I'll leave relative alone. Sound OK?

And another thing I'm noticing from the validator now: 

`Value Card of feature NumType is not permitted with UPOS PRON`

This is triggered by those cases where the canonical xpos is CD, but the UPOS is now PRON, primarily "one another". Should "one" in "one another" not be tagged Card? And similarly it triggers an error for NumForm=Word.

**Comment by nschneid** [comment]
Lets say Num* features for `NUM` tokens only.

**Comment by amir-zeldes** [comment]
OK

**Comment by nschneid** [comment]
Would substitutability of the numeral "1" in casual (but not SMS-style) writing make a good heuristic for CD?

I would never write something like

- A popular option, and 1 good for your health too, is by sea kayak
- It is 1 that was made with the American public in mind

but I might causally write

- IBM adapted 1 of these versions in 1981
- a form asking them to check 1 of 3 answers
- a solicitor representing 1 of the banks said

**Comment by amir-zeldes** [comment]
I wouldn't be confident that people are consistent about what they would and wouldn't substitute by numerals, and in spoken data we can't even tell how things are 'spelled', so I would stick to a totally decidable version of the criteria which most closely reproduces prior art (PTB xpos), and mapping to UPOS as we've discussed based on pretty rigid criteria.
