### ISSUE TITLE
Inconsistent analysis of "quality work"

### ISSUE THREAD

**Issue by lgessler** [UniversalDependencies/UD_English-EWT#377]
Three occurrences in EWT:

> (1) Very reasonable prices and quality/NN work/NN `compound(quality, work)`
> (2) Excellent customer service and quality/JJ work/NN `amod(quality, work)`
> (3) Excellent customer service and quality/JJ work/NN `amod(quality, work)` (again)

The analysis in (1) is to be preferred, IMO, since _quality_ as used in _quality work_ doesn't tolerate adverbial modification well:

> (4a.)   really famous work
> (4b.) ? really quality work
> (5a.)   marginally famous work
> (5b.) ?? marginally quality work
> (6a.)   strikingly famous work
> (6b.) ?? strikingly quality work

**Comment by nschneid** [comment]
Agreed, I don't see any reason to say "quality" is an ADJ as well as a NOUN.

**Comment by rueter** [comment]
Confused by the idea of amod(quality, work), which as far as I knew was supposed to indicate that "work" was an adjective,
I'm not sure we are on the same wave lengths for understands the archs in compound(quality, work). Are you setting the arrow tip of the arch on the word "work"?

**Comment by lgessler** [comment]
yes, my bad--forgot what the UD conventions were for that. Corrected OP

**Comment by arademaker** [comment]
> IMO, since quality as used in quality work doesn't tolerate adverbial modification

What about `strong quality work` or `high quality work`? Sorry, I may have misunderstood the argument, not a native speaker.

**Comment by nschneid** [comment]
That would be [high quality] work = work of high quality, i.e. amod(quality, high). No need to say that "high" is an adverb.

"Strong quality work" is a bit less idiomatic but "strong" is more clearly an adjective, as opposed to *strongly quality work.
