### ISSUE TITLE
Inconsistent Annotation of "over there"

### ISSUE THREAD

**Issue by mr-martian** [UniversalDependencies/UD_English-EWT#385]
http://universal.grew.fr/?custom=63d94d15542d7

There's an instance where both have `advmod` and ones where it's `obl` and `case`. The UPOS of "over" differs, and I'm also puzzled by `PronType` on an `ADV`.

**Comment by nschneid** [comment]
Thanks. I believe ADV/advmod is correct.

Re: `PronType`, see [this page](https://universaldependencies.org/en/feat/PronType.html#dem-demonstrative-determiner-or-adverb). `PronType` applies chiefly to pronouns but also to other pro-forms.

**Comment by nschneid** [comment]
Broader query: http://universal.grew.fr/?custom=63d9f92d15d65
