### ISSUE TITLE
POS tags for 'whatever'

### ISSUE THREAD

**Issue by amir-zeldes** [UniversalDependencies/UD_English-EWT#393]
It seems "whatever" has 4 POS tags [in EWT](https://universal.grew.fr/?custom=64484a6785e2f):

  * WP (only used when whatever heads an NP)
  * WDT (mostly used as a real determiner: "whatever X", but some errors that should probably be WP?)
  * UH as an exclamation
  * GW for 'goeswith' cases

The wrong WDT cases should be corrected (I see some of these in GUM and ON as well). I'm not sure if we want UH - OntoNotes seems to treat these literally so GUM does as well. Should we use UH for the exclamation? (considering we don't use UH for a dejected 'what?')

**Comment by AngledLuffa** [comment]
> I'm not sure if we want UH - OntoNotes seems to treat these literally so GUM does as well. Should we use UH for the exclamation?

Whatever...

> WDT (mostly used as a real determiner: "whatever X", but some errors that should probably be WP?)

An example of the error you have in mind is this, where it's the head of the noun phrase?

```
# sent_id = weblog-blogspot.com_dakbangla_20050311135387_ENG_20050311_135387-0217
# text = Whatever your political persuasion, the FBI and CIA deserve our support.
1       Whatever        whatever        DET     WDT     PronType=Int    10      advcl   10:advcl        _
2       your    your    PRON    PRP$    Case=Gen|Person=2|Poss=Yes|PronType=Prs 4       nmod:poss       4:nmod:poss     _
3       political       political       ADJ     JJ      Degree=Pos      4       amod    4:amod  _
4       persuasion      persuasion      NOUN    NN      Number=Sing     1       nsubj   1:nsubj SpaceAfter=No
```

whereas in this case, it is acting as a determiner?

```
# sent_id = newsgroup-groups.google.com_misc.consumers_a534e32067078b08_ENG_20060116_030800-0120
# text = The dangers implicit in any attack upon that nation, however, seem to significantly offset whatever gains could be made in the so-called "War on Terror."
14      to      to      PART    TO      _       16      mark    16:mark _
15      significantly   significantly   ADV     RB      _       16      advmod  16:advmod       _
16      offset  offset  VERB    VB      VerbForm=Inf    13      xcomp   13:xcomp        _
17      whatever        whatever        DET     WDT     PronType=Int    18      det     18:det  _
18      gains   gain    NOUN    NNS     Number=Plur     16      obj     16:obj  _
19      could   could   AUX     MD      VerbForm=Fin    21      aux     21:aux  _
20      be      be      AUX     VB      VerbForm=Inf    21      aux:pass        21:aux:pass     _
21      made    make    VERB    VBN     Tense=Past|VerbForm=Part|Voice=Pass     18      acl:relcl       18:acl:relcl    _
```

then this one seems different from the other two

```
# sent_id = answers-20111108104350AAp4hGP_ans-0023
# text = If you can find a pet at a shelter, or that a friend needs to get rid of because they're moving or whatever, you might be able to talk your parents into "giving it a good home" where you might not be able to talk them into buying a new pet.
20      because because SCONJ   IN      _       23      mark    23:mark _
21-22   they're _       _       _       _       _       _       _       _
21      they    they    PRON    PRP     Case=Nom|Number=Plur|Person=3|PronType=Prs      23      nsubj   23:nsubj        _
22      're     be      AUX     VBP     Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin   23      aux     23:aux  _
23      moving  move    VERB    VBG     Tense=Pres|VerbForm=Part        17      advcl   17:advcl:because        _
24      or      or      CCONJ   CC      _       25      cc      25:cc   _
25      whatever        whatever        DET     WDT     PronType=Int    9       conj    4:obl:at|9:conj:or      SpaceAfter=No
```

**Comment by nschneid** [comment]
The WH-ever pronouns enter into some tricky constructions involving interrogative/relative clauses with particular meanings. I have not yet figured out what to do with [these dependent WH cases](https://universal.grew.fr/?custom=643c60408191f) from #278. See also the ["no matter" subsection of the English RC guidelines](https://universaldependencies.org/en/dep/acl-relcl.html#no-matter-and-similar) (still TBD).

Regarding WDT vs. WP, though, the PTB guidelines are clear:
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/985263/234410664-cf41d3df-8f32-4244-814f-8ed4735efc65.png">

**Comment by nschneid** [comment]
And: I suspect the 1 UH token is an error.

**Comment by AngledLuffa** [comment]
> I suspect the 1 UH token is an error.

How would you label "Whatever" as a complete sentence, then?

**Comment by nschneid** [comment]
WP. I am guessing that "boy" in "Oh boy!" and "Dude!" would both be tagged as nouns, and "Amazing!" as an adjective, though they head an utterance with exclamatory meaning.

**Comment by amir-zeldes** [comment]
Fixed in GUM upstream

**Comment by nschneid** [comment]
> WP. I am guessing that "boy" in "Oh boy!" and "Dude!" would both be tagged as nouns, and "Amazing!" as an adjective, though they head an utterance with exclamatory meaning.

Though I am keeping INTJ as the UPOS at least for now (cf. #429) because I am not sure what features would be appropriate if tagged as PRON.

**Comment by nschneid** [comment]
Note that the structure of "whatever" adjuncts is still up in the air (are they relative or interrogative?)—related to "no matter" (#376).
