### ISSUE TITLE
help (NP) VP: xcomp vs. ccomp

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#401]
- [EWT](https://universal.grew.fr/?custom=647bd411c34fb) has 13 ccomp, 44 xcomp
- [GUM](https://universal.grew.fr/?custom=647bd3dac6394) has 2 ccomp, 25 xcomp

I assume xcomp is correct even if there is an interpretation where the direct object/controlled subject is implicit. Will fix EWT.

**Comment by amir-zeldes** [comment]
Will fix GUM, thanks for catching it!
