### ISSUE TITLE
be/VERB is suspect

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#404]
- [110 in EWT](https://universal.grew.fr/?custom=648487a617a3b)
- [204 in GUM](https://universal.grew.fr/?custom=64848767def1c)

Many of these look like they should be AUX, stranded due to ellipsis (cf. #403).

**Comment by nschneid** [comment]
@amir-zeldes If "there **is**..." should stay VERB, what about "there seems to **be**"?

**Comment by nschneid** [comment]
Used the following DepEdit script:

```ini
; AUX for "be" (excl. "there is", "there seems to be")
lemma=/be/&upos=/VERB/;xpos=/EX/	#1>#2	#1:storage=has_expl
lemma=/be/&upos=/VERB/&func=/xcomp/;xpos=/EX/;func=/.*/	#3>#1;#3>#2	#1:storage=has_expl
lemma=/be/&upos=/VERB/&storage!=/has_expl/	none	#1:upos=AUX
```

**Comment by nschneid** [comment]
Related: "do", "have" VERB->AUX #403

**Comment by nschneid** [comment]
A few more where the tag doesn't match the tree (excepting tag questions)—AUX should be VERB for existential, or copula is incorrectly promoted: https://universal.grew.fr/?custom=64bca7e416fb4

**Comment by nschneid** [comment]
@amir-zeldes Does the above look OK?

**Comment by amir-zeldes** [comment]
LGTM, incorporating into GUM
