### ISSUE TITLE
"a couple NOUN"

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#405]
The quantity expression "a couple" can immediately precede the noun quantified—like "a few", "a little". (Contrast "a lot", which requires "of".)

It is handled inconsistently:
- [EWT](https://universal.grew.fr/?custom=649adf360c643): 8 compound, 7 nmod, 2 nummod
- [GUM](https://universal.grew.fr/?custom=649adf8211bf3): 1 nummod

nmod seems incorrect as there is no preposition.

In #170 we decided to stick with the status quo for "a few"/"a little"—treat both article and adjective as headed by the noun, with det and amod.

But "couple" is a noun. Should it be considered a NUM? (And if so, shouldn't other approximate quantities—"lot", "bunch", "handful", etc. also qualify?)

If "couple" and other approximate quantities are not NUM, then it seems odd to attach them as `nummod`. Currently "couple" is among very few items attaching as `nummod` with no NUM or NumType: [EWT](https://universal.grew.fr/?custom=649aded884559), [GUM](https://universal.grew.fr/?custom=649adea762e2a)

Syntagmatically, "couple" and "few" seem to fill the nummod slot—they cannot cooccur with another nummod, and "a" cannot coocurr with a definite article:

- *a couple 2 books
- *2 a couple books
- *a few 3 books
- *3 a few books
- *the a couple books
- *the a few books
- the couple weeks since December (attested in COCA; seems very colloquial)
- the few weeks since December (BUT: different meaning from "a few")

Another option is `fixed` for all these "a" + quantity noun expressions that occur prenominally—treating them as multiword DETs or NUMs. But that doesn't solve "the couple weeks since December". And at the time of #170 we decided to avoid rocking the boat.

Is `compound` the least bad solution, by analogy to `amod` for "few"/"little"?

**Comment by amir-zeldes** [comment]
I see the issue. I think NUM/nummod is not right, because if "few" isn't a NUM, the neither is "couple" IMO, since it's not literally two, it's non-exact (and "many" etc. are also not NUM).

If we accept that it remains NOUN and is similar to "(a) few" (which is adjectival), then I think the better label here would be `nmod:npmod`, which is used elsewhere for extent modifiers. Since nouns normally take articles, I would attach the "a" as usual, to "couple", and consider it an extent modifer NP.

**Comment by nschneid** [comment]
`nmod:npmod` for MEASURE + NOUN (without "of") appears to be the policy for the multiplicative noun "times" as in "it is eight times the price", as well as occasional percentages ("Genius is one percent inspiration", "it is 100% a scam"). [EWT](https://universal.grew.fr/?custom=64ac27ff9b44a), [GUM](https://universal.grew.fr/?custom=64ac280b94f40)

So I guess extending this to "a couple NOUN" makes sense in practice. It's a bit linguistically unsatisfying as a theory of how English noun phrases are formed, because some of these `nmod:npmod`s and `amod`s ("a few") substitute for determiners, but we'd need to do a bigger overhaul of the treatment of `det` to account for that.

**Comment by nschneid** [comment]
Implemented `nmod:npmod` for EWT
