### ISSUE TITLE
plain nmod without case

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#406]
Some of these are clear errors:

- [EWT](https://universal.grew.fr/?custom=649ad78defce7)
- [GUM](https://universal.grew.fr/?custom=649ad764545cf)

In EWT "a couple" is often analyzed in this way. Opened a separate issue: #405

**Comment by amir-zeldes** [comment]
Fixed GUM cases, thanks!

**Comment by nschneid** [comment]
EWT: mostly cases where "of" is missing or where there is an object shared by two different governor+preposition combinations in coordination.
