### ISSUE TITLE
det in compound dependent

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#407]
Some of these are valid hyphenated compounds ("all-in-one", "behind-the-scenes"), but others are errors:

- [EWT](https://universal.grew.fr/?custom=649ae60408a17)
- [GUM](https://universal.grew.fr/?custom=649ae5a923494)

**Comment by amir-zeldes** [comment]
Fixed the GUM error, thanks!

**Comment by nschneid** [comment]
Assuming we want to use `compound` for "what size horse" or "this size horse" I think remaining EWT ones are OK.

GUM: several [of these](https://universal.grew.fr/?custom=652ab9a4dc20b) look like errors. Are they fixed upstream?

**Comment by amir-zeldes** [comment]
Fixed the ones that were wrong, thanks!
