### ISSUE TITLE
illicit plural compound dependents

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#408]
While plural nouns may be compound modifiers ("securities exchange", "political affairs director"), it is a relatively closed set. After going through the EWT ones, here are ones to fix—many are really possessives missing an apostrophe (#82):  https://universal.grew.fr/?custom=649c960b3da18

**Comment by lgessler** [comment]
FWIW there's a paper arguing that plurals in compounds are productive, see page 261 (Punske and Jackson) http://linguistics.berkeley.edu/bls/previous_proceedings/bls43_1.pdf

**Comment by nschneid** [comment]
Yeah I dunno if I buy this. p. 265: 

> We claim that regardless of regularity [of the noun plural], singular modifiers are required when an individuating interpretation is required, plurals are required for a collective/group interpretation, and in cases where both are allowed, there are clear differences in meaning, such that the plurals support collective or idiosyncratic interpretations.

If it's purely semantic, why not _*eggs carton_? That refers to a group of eggs.

I think it's more likely to be the case that there are certain semantic classes where a plural is motivated, and sometimes possible, but we have item-based knowledge as well and it's not totally predictable.
