### ISSUE TITLE
obl:tmod should be obj

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#409]
Some temporal objects of transitive verbs are mistakenly treated as `obl:tmod`. E.g. "enjoy those 2 days".

- [EWT tokens to review](https://universal.grew.fr/?custom=64a2293bae788)
- GUM: not a systematic problem. I found [4 suspicious tokens](https://universal.grew.fr/?custom=64a22b67952d3) - 2 clear errors ("waste time", "remember that night"), and "last" which takes a temporal complement that might be considered an object.

**Comment by nschneid** [comment]
[Query with verbs used only intransitively filtered out](https://universal.grew.fr/?custom=64a23df39706f)

**Comment by amir-zeldes** [comment]
Thanks, fixed the two GUM errors - I don't think 'last' is an error, since you can't passivize the time participant:

  * the drought lasted two centuries
  * * two centuries were lasted by the drought

**Comment by nschneid** [comment]
It is similar to a sense of "take", which also cannot be passivized. For "take", the duration is obligatory and cannot be marked by a preposition:

- The test takes an hour.  
  *The test takes.  
  *The test takes for an hour.  
  *An hour is taken by the test. (in the sense of "an hour is what the test takes")

"Last" is murkier because "for" can be inserted:

- The test lasts an hour.
   The test lasts for an hour.
   ?The test lasts. (wrong meaning)
   *An hour is lasted by the test.

Regarding whether passivization is a necessary and sufficient test for direct object: CGEL (p. 246) says it is sufficient but not necessary. They give the example of "have":

- His uncle had two yachts.  
   *Two yachts were had by his uncle.

Very weird to passivize "have" here where it means 'own'. (You can say things like "fun was had by all", or "there are no yachts to be had", but those are different senses.)

**Comment by amir-zeldes** [comment]
Sure, almost no test is air-tight, but I think interpreting 'last' as intransitive makes more sense. FWIW I can find some examples of passive time taken in encow, e.g.:

  *  no time was taken to check on the legitimacy of such a criticism
  *  Many patients are frustrated with the length of time being taken to implement medical use

But I can find no such examples with "last".

**Comment by nschneid** [comment]
Since English doesn't provide much in the way of morphological evidence, I think this is a case where the core (obj) vs. non-core (obl) distinction that UD tries to make is just murky. It is easier to see how to test for complement vs. adjunct.

We could have a rule for English that the absence of a preposition on an NP *complement* in a clause means it is core. But there are prepositionless *adjunct* NPs too, and these are clearly obl. If complement vs. adjunct is meant to be completely orthogonal to UD criteria, I don't see a reason to rule out `obl:tmod` for the NP complement of "last".

**Comment by amir-zeldes** [comment]
> I don't see a reason to rule out obl:tmod for the NP complement of "last".

Sure, but then I think we agree, right? Interpreting 'last' as intransitive means that it has to be `obl:tmod` (or npmod if it's a distance or something).

**Comment by nschneid** [comment]
Yeah, unless somebody else has a counterargument we should change the `obj` tokens ([here](https://universal.grew.fr/?custom=64a5c08c69286), [here](https://universal.grew.fr/?custom=64a5c0b7eefff)) to `obl:tmod`.

**Comment by amir-zeldes** [comment]
Sure, will fix GUM

**Comment by nschneid** [comment]
What do you think about "live" + duration ("They live 11-15 years")?

Seems really hard to passivize, but "for" can be inserted.

**Comment by amir-zeldes** [comment]
That sounds like obl:tmod as well, but then there are examples that look more like cognate objects, and those are maybe more object-like:

  * live your life
  * she lived a short life

Those aren't exactly a duration, even if the second one is semantically equivalent to it, it doesn't feel adverbial, if you know what I mean.

**Comment by nschneid** [comment]
OK I'm fine treating live+life as `obj` and live+duration as `obl:tmod` similarly to "last".

**Comment by nschneid** [comment]
"live"/"last" + `obj`, should be `obl:tmod` if a temporal duration per above: [EWT](https://universal.grew.fr/?custom=64c2f911b113a), [GUM](https://universal.grew.fr/?custom=64c2f9750af44)

**Comment by amir-zeldes** [comment]
Yup, GUM cases are already done!
