### ISSUE TITLE
semi-auxiliaries/quasi-modals: "ought to/PART", "have to/PART", "go to/PART"

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#411]
Should the first word be AUX or VERB? Currently it is exclusively VERB for "go" (frequent) and exclusively AUX for "ought" (rare).

In general, we decided that "have" should be changed to AUX when it lacks an object (#403), but perhaps this construction (where it has an `xcomp`) is an exception.

"go to/PART" with `xcomp` is not exclusively the futurate, at least [in the current data](https://universal.grew.fr/?custom=64b884778ed2d). E.g. there is a GUM sentence "went to live as a hermit" (should be advcl?)

There is also the idiom _go on to do something_.

Because "ought" is not a regular verb I'm fine with keeping it as AUX. But "go" and "have" clearly have verbal paradigms and do not act like auxes with respect to inversion, negation, etc., so maybe they should remain VERB even with an `xcomp`.

**Comment by nschneid** [comment]
(Plus this class may not be neatly closed: _fixing to_, _aiming to_, ...)

**Comment by nschneid** [comment]
(Related topic: "had better/best" UniversalDependencies/docs#803)

**Comment by amir-zeldes** [comment]
I would vote against, for the same reasons these things are not deprel `aux`. I think it's inconsistent to say we take bare infinitive as the criterion for deprel `aux` (so "should" is an auxiliary but "want" is not), and then split UPOS a different way.

**Comment by nschneid** [comment]
OK, let's keep VERB for "have to"
