### ISSUE TITLE
PROPN for title of work of art

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_English-EWT#414]
In the sentence `# sent_id = newsgroup-groups.google.com_alt.animals_434fe80fb3577e8e_ENG_20031011_200300-0017`, there is `Revolution_PROPN number_PROPN 9_NUM`.  I think the tag is incorrect given the latest standard, especially on `number`

```
# sent_id = newsgroup-groups.google.com_alt.animals_434fe80fb3577e8e_ENG_20031011_200300-0017
# text = Came the disintegration of the Beatles' minds with LSD which has caused, among others, schizophrenic lyrics such as "I am the Walrus" and incoherent schizophrenic musical expositions like "Revolution number 9".
34      "       "       PUNCT   ``      _       36      punct   36:punct        SpaceAfter=No
35      Revolution      Revolution      PROPN   NNP     Number=Sing     36      compound        36:compound     _
36      number  number  PROPN   NNP     Number=Sing     32      nmod    32:nmod:like    _
37      9       9       NUM     CD      NumForm=Digit|NumType=Card      36      nummod  36:nummod       SpaceAfter=No
38      "       "       PUNCT   ''      _       36      punct   36:punct        SpaceAfter=No
```

**Comment by AngledLuffa** [comment]
for that matter, elsewhere in that sentence, I wonder if `The Walrus` is a single walrus whose lemma should be capitalized and whose tag is `PROPN`, or a generic walrus.  might have to ask the beatles themselves to get a definitive answer

```
22      "       "       PUNCT   ``      _       26      punct   26:punct        SpaceAfter=No
23      I       I       PRON    PRP     Case=Nom|Number=Sing|Person=1|PronType=Prs      26      nsubj   26:nsubj        _
24      am      be      AUX     VBP     Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin   26      cop     26:cop  _
25      the     the     DET     DT      Definite=Def|PronType=Art       26      det     26:det  _
26      Walrus  Walrus  PROPN   NNP     Number=Sing     19      acl     19:acl:such_as  SpaceAfter=No
27      "       "       PUNCT   ''      _       26      punct   26:punct        _
```

**Comment by nschneid** [comment]
Why do you think the tag for "number" is incorrect in the first example?

**Comment by AngledLuffa** [comment]
I was under the impression that in titles, things still get their basic POS, rather than the whole thing being labeled proper noun

**Comment by nschneid** [comment]
Non-nouns get their basic POS. Nouns get PROPN.

**Comment by AngledLuffa** [comment]
Got it.  So either way Walrus is also PROPN

**Comment by nschneid** [comment]
Yeah. There are names like Office Depot that consist only of nouns with transparent meaning being combined to form a name. I think the spirit of making a NOUN/PROPN distinction in UD is that it should be possible to recover most names (and explain why they don't need determiners etc.).
