### ISSUE TITLE
(be/get s.t.) "over with"

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#419]
There are at least two ways that "over with" can have a completive meaning:

- [2 GUM tokens](https://universal.grew.fr/?custom=6501d36d193f7)
  * the class is **over with**
  * it's **over with** now
- [1 EWT token](https://universal.grew.fr/?custom=6501d41612b8b)
  * let's get this **over with** now

Collins Dictionary [lists this](https://www.collinsdictionary.com/dictionary/english/over-with) as an Americanism.

In the predicative complement usage seen in GUM, "with" is technically optional—maybe it adds some sort of emphasis or is just more colloquial.

In the idiom "get something over with", both "over" and "with" are mandatory. This is NOT the standard verb particle construction (`compound:prt`) because the direct object must precede both "over" and "with": _*Let's get over with our remaining tasks._

Would it make sense to treat "over"+"with" as some sort of `compound`, or `fixed`?

What are the correct UPOS tags? ADV+ADV? The current data are inconsistent.

**Comment by amir-zeldes** [comment]
Hm, I really don't know... I don't love inflating the fixed list, it seems like a really niche expression to list. Maybe `flat`? Or I guess `compound` would be OK too. As you pointed out, the cases where it's optional require "over", so maybe that is actually the head?

**Comment by nschneid** [comment]
I'm skeptical of adding it to `fixed` because it doesn't seem as grammaticized as items on the list. It is just a sort of idiom. `compound` headed by "over" is probably our best bet. ADV+ADV?

**Comment by amir-zeldes** [comment]
It's a pretty unusual thing to call a compound, but I don't see a much better option... maybe `dep` is better? We have it in various places in GUM where we want to say 'we know what the head is, but this is idiosyncratic and there is no general name for this' (currently includes cases discussed under the proposed `nmod:desc` too)

**Comment by nschneid** [comment]
I think `compound` is pretty broad and makes sense since it's rather lexicalized. I'd rather reserve `dep` for combinations that are not really grammar, but rather genre-specific textual conventions like citations, or uninterpretable combinations, etc.

**Comment by amir-zeldes** [comment]
OK, I don't have a better suggestion and I can live with that

**Comment by nschneid** [comment]
fixed in EWT

**Comment by amir-zeldes** [comment]
fixed upstream in GUM as well
