### ISSUE TITLE
"but" should be CCONJ?

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#427]
[6 instances](https://universal.grew.fr/?custom=650f80e46a652), some involving idioms

**Comment by nschneid** [comment]
"I was able to cancel it **but**/ADV/advmod only after paying a $50 fee": Currently the second clause is advcl. 

This seems to fit what CGEL calls the "addition of new element" subtype of an end-attachment coordinate (conjunct). While it uses the coordinating conjunction, is not really coordination because it does not form a constituent with another conjunct.

<img width="875" alt="image" src="https://github.com/UniversalDependencies/UD_English-EWT/assets/985263/2df9baa4-04d8-49f8-b676-d7351806fdae">

<img width="948" alt="image" src="https://github.com/UniversalDependencies/UD_English-EWT/assets/985263/67f421c9-5581-475d-aa09-fc0826a58304">

So I'll leave the structure as is but change "but" to CCONJ/cc. CCONJ is already used for [all other "and/but only" instances](https://universal.grew.fr/?custom=652a9f1342540).

**Comment by nschneid** [comment]
EWT has [2 tokens of "all but"](https://universal.grew.fr/?custom=652aa3e7ce6f0). One of them is compositional (meaning 'all except'), tagged DET+ADP. This is consistent with one of [2 GUM tokens](https://universal.grew.fr/?custom=652aa423f32fd)—the second has CCONJ/cc but I think it should be ADP/case.

The noncompositional one is "all but impossible". I think the tags should be DET+ADP as well though it is a `fixed` expression functioning as advmod. I will add ExtPos=ADV and update the `fixed` guidelines.

**Comment by nschneid** [comment]
but/SCONJ is legitimate I think when it functions like 'except' + clausal complement.

**Comment by amir-zeldes** [comment]
Agreed, GUM error is fixed
