### ISSUE TITLE
be about/? to do something: ADJ, ADV, or ADP?

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#430]
https://universal.grew.fr/?custom=650f89d98e82c

**Comment by nschneid** [comment]
Remarks:
- GUM has exclusively ADV. EWT has a mix of ADV and ADJ.
- Neither corpus has about/ADJ outside of this construction. This makes me suspicious of ADJ, along with the fact that the infinitival is mandatory: _We are ready (to leave)_ but _*We are about_.
- Dictionaries I checked are mixed. [MW](https://www.merriam-webster.com/dictionary/about) and [OED](https://www.oed.com/dictionary/about_adv?tab=meaning_and_use#6789614) say Adv. [Collins COBUILD](https://www.collinsdictionary.com/dictionary/english/be-about-to), [Longman](https://www.ldoceonline.com/dictionary/about), and [Oxford Advanced Learner's](https://www.oxfordlearnersdictionaries.com/us/definition/english/about_3#about_idmg_3) say Adj. @brettrey also [has Adj](https://simple.wiktionary.org/wiki/about), which may be influenced by CGEL's narrow view of the Adv category (CGEL AdvPs can't be complements of *be*).
- OntoNotes 5 prefers Adj but is mixed: 43 JJ tokens, 20 IN, 4 RB

There's also the question of the correct structure:
- (A) "about" as head of predicate with `xcomp` dependent, or
- (B) "about" as `advmod` of following predicate (perhaps `fixed` à la "so as to")

**Comment by nschneid** [comment]
I suppose the treatment of semi-auxiliaries like "ought to" and "have to" is relevant (#411). For the sake of argument:

- (C) "about" as AUX/`aux` of following predicate, and "be" as the progressive auxiliary rather than the copula
   * "ought to" uses the `xcomp` analysis though, despite "ought" being tagged AUX, so that weighs against the shallow structure
- (D) "about" as AUX with `xcomp` dependent, like "ought"

**Comment by nschneid** [comment]
An argument against (B) is that the position of an `advmod` in a clause is often flexible, but this is not the case with "about to":

- Soon, he will leave.
   He will soon leave.
   He will leave soon.
- *About, he is to leave.
   *About to, he is leave.
   He is about to leave.
   *He is to leave about.
   *He is leave about to.

"so as to" differs because it attaches as `mark`, which is expected to occur at the beginning of the clause.

**Comment by nschneid** [comment]
Argument against AUX: "about to" can appear in a predicative adjunct, e.g. "(Being) about to leave, the president was stopped by an aide". This suggests that when "be" is present, either in an adjunct or in a main clause, it is the copula, not the progressive aux. The copula would not normally be followed by an aux.

So I am leaning toward (A) for the structure and ADJ or ADV for the tag.

**Comment by amir-zeldes** [comment]
Would definitely vote for xcomp dependent. For POS I would try to follow ON, so I would prefer JJ/ADJ, and can fix GUM.
