### ISSUE TITLE
VERB-headed appos

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#437]
A lot of these look fishy to me: https://universal.grew.fr/?custom=65182c0944276

- complement of "named", "dated" (`xcomp`?)
   * Two top Iraqi scientists, code **named** **Charlie** and Alpha
   * letter **dated** **November** 16, 2000
- setup-reveal discourse structures (I am thinking `parataxis` would be better)
   * There **is** an old saying that applies in this situation: "**Act** in haste, repent at leisure." 
   * And I **have** to wonder: Did he **forget** that he already has a memoir called "A Charge to Keep"? 
       - this could be `ccomp`, treating the colon like a comma
   * Get six separate pieces of paper and write the **following** on each piece of paper "PLEASE **PUT** ME ON YOUR MAILING LIST." 
- action verb elaborated with examples (implicit "namely, ...") - `parataxis`?
   * Maybe **do** volunteer work at the humane society, **walk** dogs, groom the animals etc. 
   * they have been **playing**(**chasing** each other up and down the hall, rolling around on the ground and pawing at each other). 
- stative verb elaborated with a description (implicit "namely, ...") - `parataxis`?
   * I was not happy with the way they **looked**, very **wavy**, uneven edges, and with the exception of 1, there is a dip in the center of each nail. 
   * Their Thali was not brought out as **described** (no **saag**).
- action verb & noun that characterizes/elaborates on that action (`parataxis`?)
   * The next day an angry Musharraf categorically said that Pakistan would not **send** Pakistani troops to Iraq, a clear **snub** to the Americans. 
   * They explained that elk in Yellowstone used to **browse** unmolested on young aspen and willow growing near the banks of streams, a **behavior** that prevented the saplings from reaching mature stages and increased the possibility of soil erosion. 
 - parenthetical that is not next to the thing it elaborates (`parataxis`?)
    * This term was first **used** in German (**Hochrenaissance**) in the early nineteenth century

(I think the EVENT: DATE ones like "Koran descends to Earth: April 6, 610 AD Monday" are valid as key-value pairs in a list; https://universaldependencies.org/u/dep/appos.html)

**Comment by nschneid** [comment]
> * letter **dated** **November** 16, 2000

Let's consider an active voice variant: "I dated the letter November 16". Is that a sort of obligatory resultative? It's a bit nonprototypical for `xcomp` because you wouldn't say the letter is/became November 16, but by metonymy, the writing on the letter became that...a similar verb would be "label".

**Comment by nschneid** [comment]
@amir-zeldes curious for your input

**Comment by amir-zeldes** [comment]
I think this should be xcomp, it falls under the same general type as appointment verbs IMO (I appoint you president) - you're dating the letter X, and it is therefore so dated, a kind of performative action.

**Comment by nschneid** [comment]
OK. Does parataxis look good for the others?

**Comment by amir-zeldes** [comment]
LGTM, except "do volunteer work at the humane society, walk dogs, groom the animals etc.", since "etc." is analyzed as as conj effectively containing a cc, so maybe conj across the board makes more sense there (you can't say "and etc." so this is the only way to make an explicit coordination here)

**Comment by nschneid** [comment]
> * Maybe **do** volunteer work at the humane society, **walk** dogs, groom the animals etc.

Yes the "etc." is in a coordination, but I take walking the dogs and grooming the animals to be examples of volunteer work at the humane society. So "work" is not part of the coordination.

**Comment by amir-zeldes** [comment]
Oh, I see, that makes sense.
