### ISSUE TITLE
amod headed by non-nominal

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#438]
Some of these are errors or may benefit from discussion:

- EWT: https://universal.grew.fr/?custom=6518336dc3383
- GUM: https://universal.grew.fr/?custom=6518333c531c4

**Comment by nschneid** [comment]
- EWT: I guess the main issue here is what to do about compounds like "Canadian-born" and "French-trained".
- GUM: Some errors here including with secondary predicates.

**Comment by amir-zeldes** [comment]
Fixed GUM cases upstream, thanks!
