### ISSUE TITLE
acl headed by non-nominal

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#439]
(sister issue to #438)

These need review. Some look like depictives that should be switched to `advcl` per the new policy.

- EWT: https://universal.grew.fr/?custom=651834e9568ca
- GUM: https://universal.grew.fr/?custom=651835255739b (some of these are tough-constructions)

**Comment by nschneid** [comment]
Also this one in EWT (ADV head but it's a clausal adjunct): https://universal.grew.fr/?custom=65187e1bcc4b8

**Comment by nschneid** [comment]
Many of these are "much to offer" and similar, which seems valid as `acl`.

- Noticed a few of these Cookie cutter places **opening** in Summit and New Providence.

I take it this should be xcomp(Noticed, opening).
 
- For those who care, a good proportion of the my class went on to 4-year colleges, many of them **ranked** in the top 50 of US News. 
- Armed militias, many **staffed** by former Iraqi military men with substantial training and experience, have proliferated. 

These have "many" attaching as `appos` and heading an `acl`. I can see the logic but it doesn't feel right. "...colleges, many of them ranked" is really a paraphrase of "colleges, many of which are ranked" (i.e. "many of them ranked" is a verbless clause not an NP). So I'm thinkin acl(colleges, ranked) and nsubj(ranked, many).

**Comment by nschneid** [comment]
EWT is fixed

**Comment by amir-zeldes** [comment]
OK, I fixed the non-tough GUM ones. I'm not sure what we are doing about tough constructions in the end.
