### ISSUE TITLE
Not only but also

### ISSUE THREAD

**Issue by amir-zeldes** [UniversalDependencies/UD_English-EWT#452]
EWT and GUM are inconsistent on "not only" in "not only... but also". In EWT, they are separate dependents of the first phrase, and in GUM mostly so (but sometimes "not" modifies "only"). Both corpora vary on the label for "only" between `advmod` and `cc:preconj`. I think it should probably be `advmod` and maybe lean towards the separate dependents interpretation syntactically, though pragmatically I see why they are considered 'one thing' and similar to cc:preconj.

https://universal.grew.fr/?custom=653a6f4aa65aa

**Comment by nschneid** [comment]
See #442 and #114

The prototypes of `cc:preconj` are words that are normally determiners but can also introduce correlative coordinations: both...and, either...or, neither...nor. In these constructions, "both"/"(n)either" do not function as part of the nominal as they would when acting as determiners: "Both the cat and the dog are brown" does not entail "Both the cat is/are brown".

Though "not only"..."and also" tend to correlate, I'm not sure there's such a strong argument that "not only" wouldn't have a normal function as modifier within the first conjunct: "Not only the cat but also the dog is brown" DOES entail "Not only the cat is brown".

So I'd be inclined to go with advmod(cat, only) and "not" attaching as advmod either to "only" or to "cat".

**Comment by amir-zeldes** [comment]
Right, that's what I think too. But so should we go with "cat" or "not" as the head of "only"? I could see arguments for both - it's quite closely related to only (negating the exclusivity), but we have often attached "not" to phrases, meaning the whole phrase is negated.

**Comment by nschneid** [comment]
CGEL p. 809: "Not only was the acting appalling"—this suggests to me that "not only" is a phrase, so advmod(only, not). p. 1314 concludes "It thus functions as a modifier, not a marker of correlative coordination" (agreeing with our rejection of `cc:preconj`).

**Comment by amir-zeldes** [comment]
I just realized this already had an issue in #442. So I agree it's not cc:preconj but I want to be sure about the attachment and prevent flip-flopping later. Don't we attach "not" to the phrase in cases like "not very difficult" or "not exactly certain"?

https://universal.grew.fr/?custom=653a9157af8d2

I don't disagree that "not only" could be seen as a phrase, but I thought we had an overarching policy of attaching negations to the phrase governing the adverb as a whole.

**Comment by nschneid** [comment]
As a general rule I think it makes sense to default to the shallower one, but maybe some cases should be exceptions? It's not 100% consistent currently:

- EWT: https://universal.grew.fr/?custom=653a92c1c6ff2
- GUM: https://universal.grew.fr/?custom=653a92e16400c

**Comment by amir-zeldes** [comment]
GUM is pretty consistent - I see only one error (in the other cases, there is no noun, so no alternative attachment option)

**Comment by nschneid** [comment]
If shallow attachment is a simpler general policy then sure

**Comment by amir-zeldes** [comment]
OK, done in GUM

**Comment by nschneid** [comment]
EWT should be fixed for "not only" (`cc:preconj`->`advmod`) as well as standardizing on the shallow attachment of "not" in most cases
