### ISSUE TITLE
Morph. features are alphabetized ignoring case?

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_English-EWT#460]
In Python we would get:

```
>>> "Number" < "NumForm"
False
>>> "number" < "numform"
True
```

whereas in EWT we are sorting features like this:

```
12      1990s   1990    NOUN    NNS     Number=Plur|NumForm=Digit|NumType=Card  4       nmod    4:nmod:during   _
```

**Comment by nschneid** [comment]
The UD validator in https://github.com/UniversalDependencies/tools/ enforces alphabetical order of features.

**Comment by AngledLuffa** [comment]
Right, but my question is, are we ignoring case?  In Python and Java, `NumForm` comes before `Number` unless we specifically ignore case

**Comment by nschneid** [comment]
We are doing whatever the validator does. Apparently yes, it is ignoring case, otherwise the treebank would trigger an error.
