### ISSUE TITLE
Installing UDPipe2 on local amchine

### ISSUE THREAD

**Issue by Shasetty** [UniversalDependencies/UD_English-EWT#470]
Hi All,
I am Shankar from Bangalore India.

I tried to install  UDPipe 2 locally, on my machine, 
with the help of different python programmers.
(I am a non programmer).

No python programmer was able to install them.

Can any of you install UDPipe 2 locally on my machine 
or 
suggest some body, who can install it.

If you do this to me, It would be of great help to me.

Thanks in advance

Regards
Shankar

**Comment by nschneid** [comment]
ufal/udpipe#180 is the correct place to ask this
