### ISSUE TITLE
Unify lemmas of pants, glasses, jeans

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_English-EWT#476]
What do we do with single items with plural word forms such as `pants`, `glasses`, `sunglasses`, `jeans`, etc?

In general, `jeans` or `pants` get lemmatized to the plural lemma in EWT but then to the singular in GUM:

EWT:

```
# sent_id = email-enronsent08_02-0021
# text = Yo mama`s so fat, instead of Levis 501 jeans, she wears Levi`s 1002`s.
11      jeans   jeans   NOUN    NNS     Number=Plur     14      obl     14:obl:instead_of       SpaceAfter=No
```

```
# sent_id = email-enronsent08_02-0018
# text = She has to iron her pants on the driveway.
6       pants   pants   NOUN    NNS     Number=Plur     4       obj     4:obj   _
```

but in GUM:

```
# sent_id = GUM_fiction_claus-18
# text = His white V-neck undershirt was tucked into his pants in front, pulled taught over his belly.
11      pants   pant    NOUN    NNS     Number=Plur     8       obl     8:obl:into      Entity=69)|MSeg=pant-s
```

then both treebanks agree that one pair of glasses is lemmatized as `glass`, but that's inconsistent with `pants` or `jeans` and is kind of unsatisfying IMO

EWT

```
# sent_id = answers-20111107175720AAlb2TB_ans-0010
# text = It may be shirtsleeves and sunglasses in February, but winter woollies in March and even during the summer.
6       sunglasses      sunglass        NOUN    NNS     Number=Plur     4       conj    4:conj:and      _
```

@nschneid @amir-zeldes

**Comment by AngledLuffa** [comment]
I suppose a similar question would apply to `pyjamas` although that doesn't exist anywhere in EWT or GUM (it does in PUD)

**Comment by AngledLuffa** [comment]
(or `pajamas` depending on how you spell it, but that doesn't show up anywhere that I see)

also `clothes`, I suppose.  It should be noted that in GUM, `clothes` stays as `clothes`, which is inconsistent IMO with lemmatizing `pants` as `pant` or `glasses` as `glass`

**Comment by AngledLuffa** [comment]
it should be noted that this was quite similar to

https://github.com/UniversalDependencies/UD_English-EWT/issues/374

**Comment by nschneid** [comment]
Changed "sunglasses" in EWT. I take it the rest of the issue overlaps with UniversalDependencies/docs#999.
