### ISSUE TITLE
Lemma of human remains

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_English-EWT#477]
`After annoying people with too many lemma inconsistencies, his remains were found in ...`

`remains` or `remain`?  This is inconsistent between EWT and GUM

EWT

```
# sent_id = answers-20111107144339AA0qw5S_ans-0004
# text = After a person dies, their remains are “waked ” in their home for roughly 2-3days.
7       remains remains NOUN    NNS     Number=Plur     10      nsubj:pass      10:nsubj:pass   _
```

GUM

```
# sent_id = GUM_bio_gordon-29
# text = Originally buried in the Foreign Quarter, his remains were reinterred at Azov in 1877, with an inscription in German which mistakenly gives his rank as Oberst, Colonel.
9       remains remain  NOUN    NNS     Number=Plur     11      nsubj:pass      11:nsubj:pass   Entity=128)|MSeg=remain-s
```

@nschneid @amir-zeldes @rhdunn

**Comment by rhdunn** [comment]
Wiktionary defines this as plural only (with the singular form being rare and not applicable to human remains), so is would be `Number=Ptan` for the plurale tantum form instead of `Number=Plur` and the lemma would be "remains".

**Comment by amir-zeldes** [comment]
Yes, I'm fine with remains -> remains as the lemma. Will fix in GUM.
