### ISSUE TITLE
Unable to install UDPipe 2 as a local REST server

### ISSUE THREAD

**Issue by Shasetty** [UniversalDependencies/UD_English-EWT#501]
Requirements installed:

tensorflow_gpu~=2.10.1
ufal.chu_liu_edmonds
ufal.udpipe>=1.3,<2
----------------------------------------------------
error while installing wembeddings

command: pip3 install -r requirements.txt,
python3 ./start_ wembeddings_server.py 8000
[UDPIPE.docx](https://github.com/UniversalDependencies/UD_English-EWT/files/13768971/UDPIPE.docx)

---------------------------------------------------

Please help me in installing.

**Comment by nschneid** [comment]
The UDPipe repo is the correct place: ufal/udpipe#183
