### ISSUE TITLE
POS tag is wrong for "that" in relative clauses

### ISSUE THREAD

**Issue by xiulinyang** [UniversalDependencies/UD_English-EWT#502]
***_that_*** in all relative clauses below are wrongly annotated with _SCONJ_ & _IN_.  

- Both have shared this country for the last 14 centuries and there is no possible way **that** one can live without the other.
2000 - Year **that** Cheney said his policy as CEO of Halliburton oil services company was "we wouldn't do anything in Iraq".
- That was the day **that** GOD'S CURSE fell upon the world of Rock.
- Both have shared this country for the last 14 centuries and there is no possible way **that** one can live without the other.
- ‘’It was the first time **that** Bush totally focused on the Taliban threat rather than Al Qaeda with the Pakistanis,’’ says a Western diplomat.
- On the other hand, a certain transition democracy, as in Jordan, may be a better temporary solution, paving the way for the real thing, perhaps in the same way **that** an immediate sudden democracy did not work in Russia and would not have worked in China.
- 73 - Number of times **that** Bush mentioned terrorism or terrorists in his three State of the Union addresses.
- The two developments, he said, could eventually enable China's space program to mature to the point **that** experts could assemble and launch from Earth's orbit a spacecraft capable of circling the moon with astronauts and returning home.
- 1972 - Year **that** Bush walked away from his pilot duties in the Texas National Guard, Nearly two years before his six-year obligation was up.
- 2.5 - Number of hours after Rumsfeld learnt that Osama bin Laden was a suspect in the 11 September attacks **that** he brought up reasons to "hit" Iraq.
- It marks the first time in recent years **that** China has promised to wield its veto power in the UN Security Council against a petition initiated by the United States and backed by France and Great Britain."
- 2000 - Year **that** Cheney said his policy as CEO of Halliburton oil services company was "we wouldn't do anything in Iraq".
- In this hard economic times is very important to save money Very reasonable prices top quality work The owner operator he does all the the work with Helpers very friendly I definitely recommend this this guys Don't get jack by big companies **that** they pay alot of money to be on top of the list Thanks

**Comment by nschneid** [comment]
Thanks. These are adverbial relatives. Cf. https://universal.grew.fr/?custom=658e140b8b247

**Comment by nschneid** [comment]
> * In this hard economic times is very important to save money Very reasonable prices top quality work The owner operator he does all the the work with Helpers very friendly I definitely recommend this this guys Don't get jack by big companies **that** they pay alot of money to be on top of the list Thanks

Left this one alone: it is a (nonstandard) resumptive pronoun relative, so the subject position in the relative clause is already occupied by "they".

Fixed all the others.
