### ISSUE TITLE
confusion in UD 2.12 and UD 2.10 (Which one should be followed by non-experts in Grammar? )

### ISSUE THREAD

**Issue by Shasetty** [UniversalDependencies/UD_English-EWT#507]
There are lot of structural changes on the parent & child relationship between version 2.10 & 2.12.
-----------------------------------------------------
1)Which version is the correct one?
2)Which version should be followed by non-experts in Grammar?
-----------------------------------------------------
Text:
The Unregistered Warrants and the Unregistered Warrant Shares are not being registered under the Securities Act of 1933, as amended (the “Securities Act”), pursuant to the registration statement of which this prospectus supplement and the accompanying base prospectus form a part and are not being offered pursuant to this prospectus supplement and the accompanying base prospectus.

acl(Act-16,amended-21) : version ud 2.10-220711

advcl(registered-12,amended-21) : version 2.12.230717

**Comment by nschneid** [comment]
Thank you for the question. Which corpus is this from?

As a general matter, no dataset is perfect. Each version tries to improve the datasets so they will be more correct and coherent as grammatical descriptions. So in general we would recommend using the most recent version, though of course it is possible that some new errors have been introduced.

**Comment by Shasetty** [comment]
english ewt ud 2.12-230717
english ewt ud 2.10-220711

**Comment by nschneid** [comment]
That sentence doesn't appear in the English-EWT corpus. Are you referring to the output of a parser?

**Comment by Shasetty** [comment]
referring to the output of a parser.

**Comment by nschneid** [comment]
I see—parsers do make errors, and different parsers behave differently on the same input. So my advice is to use the most recent parser version if you are not sure, but there is no guarantee that it will always be correct.

**Comment by Shasetty** [comment]
acl(Act-16,amended-21) : version ud 2.10-220711

advcl(registered-12,amended-21) : version 2.12.230717

---------------------------------------------------------------

it's not a convincing answer.

Acl modifies noun, but advcl modifies verb, there is a day night difference.

**Comment by Shasetty** [comment]
Being a non-expert in Grammar, stuck in a confused status.

**Comment by AngledLuffa** [comment]
I think it would help if you said which parser you're looking at
