### ISSUE TITLE
case/det/mark attachment in unusual environment

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#517]
Need to review:

- [x] case/det: https://universal.grew.fr/?custom=660c06384ab10
- [x] mark: https://universal.grew.fr/?custom=660c06c0439f9

**Comment by nschneid** [comment]
"about the same noise level" is

<img width="619" alt="image" src="https://github.com/UniversalDependencies/UD_English-EWT/assets/985263/25454ae8-8ab4-4750-837c-7827b8644d88">

but it seems that elsewhere, approximators "about", "approximately", "almost" followed by "the" attach to a head noun unless the adjective "same" (or "last") is promoted to head of the nominal: https://universal.grew.fr/?custom=661af51245862

So I'll change both "about" and "the" to attach to "level".

**Comment by nschneid** [comment]
That leaves this weird case—"terms substantially the same as what's in the draft":

<img width="767" alt="image" src="https://github.com/UniversalDependencies/UD_English-EWT/assets/985263/d35722cf-f322-41c4-8f8e-cdb6717c1e4c">

"same" is analyzed as a adjective post-modifier—but then why does it have its own determiner? The determiner cannot be separated from "same": *_We negotiated the terms same as what's in the draft_ (non-paratactic interpretation)

Is it like a size/extent modifier NP: "dogs [the size of elephants]"? That would suggest a noun head could be inserted, but: *_terms the same terms/policies as what's in the draft_

@amir-zeldes thoughts?

**Comment by nschneid** [comment]
A few of the `mark` ones are part of the larger clausal `appos` problem: UniversalDependencies/docs#1024

**Comment by amir-zeldes** [comment]
> That would suggest a noun head could be inserted, but: *terms the same terms/policies as what's in the draft

Not sure follow this - you also can't say "dogs the size dogs of elephants", so in that respect they are similar. I guess `nmod:npmod` would be OK?

**Comment by nschneid** [comment]
Well "size" is a noun so it is expected to head a nominal. But "same" is an adjective, so I was wondering whether we take "same" as promoted from "same N".

**Comment by amir-zeldes** [comment]
Oh yeah, I think that's what I was trying to say with `nmod:npmod` (so treat it like an NP)

**Comment by nschneid** [comment]
But if it was promoted, we would expect to be able to demote it by inserting a head noun, right? I guess you could say "terms substantially the same as X" is short for "terms **that are** substantially the same (terms) as X". So yeah, maybe `nmod:npmod` works. I could see annotators being confused about why it's a different deprel from "terms equal to X" (that would be `amod` because there's no determiner before the adjective).

**Comment by nschneid** [comment]
closing this as clausal `appos` is in another issue
