### ISSUE TITLE
NumType & NumForm for pluralized decades?

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#527]
These are tagged NOUN and the "s" is retained in the lemma (#344, #467).

Should NumType and NumForm be included as these are numeric in nature? The discussion in #344 suggests yes. But it was not implemented consistently in f19511a for EWT. GUM appears not to implement these features.

Queries for NOUN+NumType+Number: [EWT](https://universal.grew.fr/?custom=6637cd24b19de), [GUM](https://universal.grew.fr/?custom=6637cd33eb494)

**Comment by nschneid** [comment]
@amir-zeldes thoughts?

**Comment by amir-zeldes** [comment]
I guess they are a kind of number... I'd be OK with Number=Plur, Card and NumForm=Combi? Or did we decide if it's NOUN it can't have NumType/NumForm?

**Comment by nschneid** [comment]
Ordinals are ADJ but have numerical features. I think it's reasonable to apply them to NOUNs as well.

I have a slight feeling that this is not a typical NumForm=Combi because the morphology is unrelated to its status as a number (it's regular noun morphology, and the noun happens to be derived from a number). But it is literally a number plus suffix so I guess it's fine.

**Comment by amir-zeldes** [comment]
Yeah, I understand NumForm as an orthographic feature, so I think it would fit. Can implement for GUM/GENTLE.

**Comment by nschneid** [comment]
Actually it looks like `Number=Ptan` applies (https://github.com/UniversalDependencies/docs/issues/999).

So:

    1990s	1990s	NOUN	NNS	Number=Ptan|NumForm=Combi|NumType=Card

    50's	50s	NOUN	NNS	Number=Ptan|NumForm=Combi|NumType=Card

    mid-1980s	mid-1980s	NOUN	NNS	Number=Ptan|NumForm=Combi|NumType=Card

**Comment by amir-zeldes** [comment]
OK, Ptan it is then!
