### ISSUE TITLE
implement ExtPos for fixed expressions; is CCONJ possible for "as opposed to", "rather than", "instead of"?

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#530]
The Core Group decided it would be a good idea for treebanks to specify how each `fixed` expression functions externally via `ExtPos` in the MISC column.

This is already implemented for a few expressions in EWT. We might as well expand to all of them. If the external deprel is correct, it can be used to infer the ExtPos (which is one of ADV, ADP, CCONJ SCONJ).

**Comment by AngledLuffa** [comment]
Can you give a bit more explanation on what ExpPos means in this case or how the external deprel will be represented?

**Comment by nschneid** [comment]
External POS: https://universaldependencies.org/en/feat/ExtPos.html

For example, "instead" is individually an ADV, but where it attaches as `mark`, it is due to the fixed expression "instead of" acting as SCONJ. So in those cases it would receive `ExtPos=SCONJ`.

**Comment by amir-zeldes** [comment]
(BTW this has also been implemented in GUM)

**Comment by bguil** [comment]
BTW2: In v2.14, most of the treebanks that use  `ExtPos` put the `ExtPos` feature in the `FEATS` column.
This includes the SUD native corpora, English-EWT, UD_Portuguese-Bosque and UD_Portuguese-GSD.

For consistency, it would be nice to have the same policy in others such as English-GUM.

**Comment by nschneid** [comment]
For EWT I've just moved it to MISC following @dan-zeman's statement that FEATS should be reserved for properties of individual words, not larger units.

**Comment by amir-zeldes** [comment]
Yes, it's in MISC in GUM for the same reason.

**Comment by nschneid** [comment]
New issue about standardizing ExtPos at the universal level: UniversalDependencies/docs#1037

**Comment by nschneid** [comment]
Implemented in the above commit.

I've made some small updates to the English `fixed` [docs](https://universaldependencies.org/en/dep/fixed.html#pragmaticmiscellaneous-markers): see #317.

One question:
- He couldn't tell when things were becoming more unstable **as opposed to** less.
   * What's the correct ExtPos here? The  give an example of "as opposed to" as `case`, but I'm wondering if this is CCONJ-like, cf. "rather than"

**Comment by nschneid** [comment]
I think "as opposed to" is like "rather than"—its coordination vs. prepositional function depends on context.

- We were eating (as opposed to drinking): `cc` (directly connects contrasted elements of like categories)
- We were eating, as opposed to Sam, who was drinking: `case`

**Comment by nschneid** [comment]
@amir-zeldes OK to add CCONJ as a possibility for "as opposed to"?

**Comment by amir-zeldes** [comment]
I'm not totally sure, but why do we need it to be cc syntactically? I mean, how is it different from like/unlike:

  * Eating, like drinking, is not allowed
  * Eating, unlike drinking, is not allowed
  * Eating and drinking is not allowed

But we don't think "like/unlike" is a cc, right?

**Comment by nschneid** [comment]
My intuition is that "as opposed to" readily connects a wider range of phrase types, and does not always require a prosodic break:

- _AdjPs:_ The wall is now pale green as opposed to bright yellow.
- _Advs:_ He is now speaking boldly as opposed to timidly.
- _PPs:_ Leave the box inside the door as opposed to on the porch.

"Rather than" can be substituted. Having trouble coming up with "like"/"unlike" examples that are good parallels.

**Comment by amir-zeldes** [comment]
Mm, maybe it's headed that way, but I think it's still not quite a CC yet, since it can be pre-poned. OntoNotes example:

  * As opposed to the $ 1.4 million deficit of the 1987 - 88 season , the 1988 - 89 year concluded with a $ 200,000 surplus

**Comment by nschneid** [comment]
I'm not arguing it's exclusively CCONJ. We concluded that "rather than" is sometimes CCONJ, sometimes ADP/SCONJ.

**Comment by nschneid** [comment]
Here's another piece of evidence—coordination of transitive VBGs in the progressive construction:

- He is ripping rather than/as opposed to carefully slicing the bread.
- *He is ripping unlike carefully slicing the bread.

**Comment by amir-zeldes** [comment]
> I'm not arguing it's exclusively CCONJ

Right, I'm just thinking if we allow it to be CCONJ, then this case would probably be tagged that way:

  * The 1988 - 89 year concluded with a $ 200,000 surplus as opposed to the $ 1.4 million deficit of the 1987 - 88 season

But as the original example shows, this case is actually invertible, which suggests it isn't CCONJ. Because it's hard to tell if a case is invertible, and because I think underlyingly this is syntactically still case, I would rather play it safe and just tag it uniformly as case/mark, and not leave room for inter-annotator inconsistencies which would come in if we allow two analyses.

> He is ripping unlike carefully slicing the bread.

Yeah, I'm not saying unlike has the same distribution, just that I'm not clear on when "as opposed to" is frontable, which, at least when it is, suggests it's not CCONJ. In that respect it's similar to "unlike", which is also often frontable.

**Comment by nschneid** [comment]
How is it different from "rather than"? https://universaldependencies.org/en/dep/fixed.html#augmentativesubstitutiveconjunctive-expressions

**Comment by amir-zeldes** [comment]
TBH probably only in that it was put on the list during SD already. If someone had asked me I would have probably raised the same objection about it ("rather than" is very often frontable):

  * Rather than a cat, I decided to get a dog

That shouldn't be CCONJ either IMO.

**Comment by nschneid** [comment]
The rule we decided in #182 was to use case/mark only for the fronted ones, and cc for the others.

**Comment by amir-zeldes** [comment]
Right - since it was already on the fixed list, I thought it was better to at least have the fronted cases as case/mark, and I still think that's better than some weird inverted conj or something. But in an ideal world, I think neither of these should be conj, so I think the fewer of these things we have the better.

**Comment by nschneid** [comment]
I just worry that saying it is never CCONJ will paint us into a corner and produce some strange structures.

Here's one I found in COCA:

- the mother is almost always the caregiver, **she rather than the father** usually teaches the child what lessons it learns at this stage

Hard for me to avoid reading that with "she rather than the father" as a constituent, and `nmod` seems wrong as personal pronouns resist most types of PP modification. It *could* be phrased as a parenthetical (so `parataxis` I guess), or maybe "rather than the father" can be moved to the clause level with the speaker counting on the pragmatics to be clear, but neither of those fits the word order and punctuation given.

Another one:

- Regardless of setting, self-talk was employed most frequently **during as opposed to prior to or post** practice and competition.

"During" is a (transitive) preposition. Prepositions can't take PP modifiers right? Looks to me like the equivalent of _[during and not [before or after]] practice_.

Also, in terms of paraphrasing, the "as opposed to Y" part can be moved to the end of the clause, but it relies on heavy inference that "during" is in focus:

- self-talk was employed most frequently during practice and competition, as opposed to prior to or post.

Fronting just sounds like a bizarre misuse of ellipsis:

- *As opposed to prior to or post, self-talk was employed most frequently during practice and competition.

One more, with adjectives:

- Election cycles tend to emphasize **short-term as opposed to long-term** performance.
- *As opposed to long-term, election cycles tend to emphasize short-term performance.

**Comment by amir-zeldes** [comment]
I think these arguments apply to things like "instead of" too - 

  * she, instead of the father, usually teaches the child 
  * self-talk was employed most frequently during instead of prior to or post practice
  * Election cycles tend to emphasize short-term instead of long-term performance

Would you want "instead of" to also be a CC? I think these are just nmod/obl + case as appropriate - the simpler, more consistent the analysis the better IMO. Just saying "instead of" ->case, "as opposed to" -> case makes it easier to teach and validate.

As for fronting, I think the reason it sounds weird in "As opposed to prior to or post, self-talk was employed.." is that the elided repeated argument of prior does not occur on first mention. This would be much better as:

  * As opposed to prior to practice, self talk was employed post-practice

**Comment by nschneid** [comment]
Yeah good point, "instead of" patterns similarly to "rather than" and "as opposed to" (there may be slight differences though, I'm not sure).

You really think "during instead of before" would be nmod(during, before)? I don't know that we have precedent for an nmod between two prepositions. They are not nominals but rather markers-of-nominals.

**Comment by amir-zeldes** [comment]
No, I'd say obl since it's not a nominal. You could also see it as a kind of promotion I guess...

**Comment by nschneid** [comment]
But we wouldn't use a promotion analysis for "during or before practice". Apart from coordination and a few other exceptions, the universal guidelines [speak against function words having dependents](https://universaldependencies.org/u/overview/syntax.html#the-status-of-function-words). The "promotion by head elision" examples given there are pretty different because they do not involve a dependency between two function words.

Anyway for now I'll stick with the existing trees when assigning ExtPos, but I do think the `fixed` guidelines need to be more consistent for these expressions, and I'm not convinced that "if it starts with a preposition and can introduce an adjunct it can never be CCONJ" is the right way to go. See also "as well as".

**Comment by AngledLuffa** [comment]
To resurrect this whole thing - I hadn't finished implementing it in PUD.  Going back to look at that, I found this example for "such as":

```
# text = The witching hour starts up at least by the time the scary organ is played, such as in the 60s hit Monster Mash.
17      such    such    ADJ     JJ      Degree=Pos      22      case    22:case _
18      as      as      ADP     IN      _       17      fixed   17:fixed        _
19      in      in      ADP     IN      _       22      case    22:case _
20      the     the     DET     DT      Definite=Def|PronType=Art       22      det     22:det  _
21      60s     60      NOUN    NNS     Number=Plur     22      nmod:unmarked   22:nmod:unmarked        TemporalNPAdjunct=Yes
22      hit     hit     NOUN    VBD     Mood=Ind|Tense=Past|VerbForm=Fin        4       obl     4:obl:in        _
```

Most of the `such as` I believe are `ExtPos=ADP`.  Would this one be as well?

**Comment by nschneid** [comment]
- **up to:** According to https://universaldependencies.org/en/dep/fixed.html, quantity "up to" is `fixed`. Agreed that "up to $5 million" fits. Other "up to" expressions (up to date, up to par) are idiomatic in meaning but probably not structurally weird enough to warrant `fixed`.
- **such as:** "such as in the 60s" is interesting because it goes with "in the 60s hit" which is itself a PP. Some other prepositions ("like", "except", ...) can also do this. I think ExtPos=ADP is probably our best bet.
