### ISSUE TITLE
"Every" instance that escaped?

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_English-EWT#533]
in the test set:

```
# sent_id = newsgroup-groups.google.com_JokeEruption_df151b356f94881c_ENG_20050819_155700-0027
# text = Every now and then she stops to breathe.
1       Every   every   ADV     RB      _       2       advmod  2:advmod        _
2       now     now     ADV     RB      PronType=Dem    6       advmod  6:advmod        _
3       and     and     CCONJ   CC      _       4       cc      4:cc    _
4       then    then    ADV     RB      PronType=Dem    2       conj    2:conj:and|6:advmod     _
5       she     she     PRON    PRP     Case=Nom|Gender=Fem|Number=Sing|Person=3|PronType=Prs   6       nsubj   6:nsubj|8:nsubj:xsubj   _
6       stops   stop    VERB    VBZ     Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin   0       root    0:root  _
7       to      to      PART    TO      _       8       mark    8:mark  _
8       breathe breathe VERB    VB      VerbForm=Inf    6       xcomp   6:xcomp SpaceAfter=No
9       .       .       PUNCT   .       _       6       punct   6:punct _
```

or was that intentional, such as it's an expression?

Also, there's this, which appears to be a typo:

```
# newdoc id = reviews-039173
# sent_id = reviews-039173-0001
# newpar id = reviews-039173-p0001
# text = The waiting staff is really friendly, its like every one knows each other, the manager is really sweet and the food..well no complaints from me.
11      every   every   DET     DT      PronType=Tot    12      det     12:det  _
12      one     one     NOUN    NN      Number=Sing     13      nsubj   13:nsubj        _
```

**Comment by nschneid** [comment]
Oh interesting, I think the issue is that "every" is normally a DET but in "every now and then" it is tagged ADV. #432

"every one": yeah maybe that should be `goeswith` despite it being a clear etymological origin of the pronoun.

**Comment by nschneid** [comment]
EWT & GUM are consistently using `det` for some/any/every + one even though the spelling is a bit nonstandard. @amir-zeldes do you think it's worth changing to `goeswith`?

**Comment by amir-zeldes** [comment]
I think it depends on whether it's actually an error for "everyone" - the case I see in GUM isn't IMO, because it says "every one of your tribes" which I think can't be replaced by "everyone of your tribes" (maybe that's also grammatical, but would mean every person amongst those tribes, not "each tribe of those tribes"). If it's replaceable by "everyone" I'd be open to analyzing it as goeswith.

**Comment by nschneid** [comment]
GUM has "some one" and "any one" with `det` though—I think these are replaceable with the pronouns.

**Comment by amir-zeldes** [comment]
Ordinarily I'd say sure, let's make it goeswith, but I don't think these cases are replaceable with pronouns. They actually come from an official political speech transcript (so less likely to be typos), and I think it means something slightly different. Notice how both cases are partitive with "of", and can be replaced with "any single one of":

  * There is no resting for **any one of us** till we redeem our pledge in full, till we make all the people of India what destiny intended them to be.
  * Those dreams are for India, but they are also for the world, for all the nations and peoples are too closely knit together today for **any one of them** to imagine that it can live apart. 

Regular "anyone" can't be replaced by "any single one":

  * Anyone can learn to play darts
  * ??Any single one can learn to play darts

I can't find the "some one" case, can you point me to it?

**Comment by nschneid** [comment]
Oh you're right. I was accidentally searching EWT yesterday when I found

- I highly recommend **any one** considering home repair to give these guys a call. 
- Can **ssome oone** please tell me where i can buy some weed in auckland. 

I can replace those with `goeswith`.

**Comment by amir-zeldes** [comment]
Yes, those look right to me too
