### ISSUE TITLE
Optatives

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#538]
Some of the suspicious `Verb=Inf` matches in #284 are (AFAICT) subjunctive optatives:

- Praise be
- Long live Irony
- god forbid

There are also proverbs with bare-form verbs like

- Monkey see, monkey do

I guess all of these should be 3rd person present tense, `Mood=Sub`?

cf. #194, #357

**Comment by nschneid** [comment]
TODO: "First come, first serve"

**Comment by nschneid** [comment]
@amir-zeldes OK with these all being subjunctive?

**Comment by amir-zeldes** [comment]
I think the following are subjunctive:

  * Praise be
  * Long live
  * God forbid
  * come December

Monkey see, monkey do is apparently originally meant to be Jamaican pidgin:

https://en.wikipedia.org/wiki/Monkey_see,_monkey_do

So I'm not sure it should be seen as subjunctive. "First come, first serve" is a probably erroneous but frequent variant of the version with -d as "served", so I think the "come" is subjunctive, but the second part is arguably a typo for a VBN. See:

https://www.vocabulary.com/articles/pardon-the-expression/first-come-first-served-vs-first-come-first-serve/

I think "act in haste, repent in leisure" is second person without a subject, not third person, so even though it's meant as a hypothetical, it might be better to classify it as an imperative conditional (like "study hard and you'll succeed").

**Comment by nschneid** [comment]
> [](https://en.wikipedia.org/wiki/Monkey_see,_monkey_do)
> 
> So I'm not sure it should be seen as subjunctive. 

Along the lines of "Long time no see"? Maybe `VerbForm=Inf` by default for those.

> "First come, first serve" is a probably erroneous but frequent variant of the version with -d as "served", so I think the "come" is subjunctive, but the second part is arguably a typo for a VBN. See:
> 
> https://www.vocabulary.com/articles/pardon-the-expression/first-come-first-served-vs-first-come-first-serve/

It doesn't strike me as an error even if it originated with the -ed form. Merriam-Webster lists both versions of the expression: https://www.merriam-webster.com/dictionary/first%20come%2C%20first%20served

To hazard an interpretation: 'They that come first, we/the staff will serve first': could both verbs be VBP?

> I think "act in haste, repent in leisure" is second person without a subject, not third person, so even though it's meant as a hypothetical, it might be better to classify it as an imperative conditional (like "study hard and you'll succeed").

So like "act in haste and you'll repent in leisure"—imperative "act", indicative "repent"?

**Comment by amir-zeldes** [comment]
Yeah, these are really corner cases, so I think it comes down to opinion more than a clear cut reason. I'm sort of etymology-focused as a default, and only consider re-analysis when the environment makes the etymologically correct version untenable. I'm fine if you want to accept the "serve" version as grammatical, but my hunch is that it's historically wrong and just comes from phonetic erosion. 

Inf qua base form for 'pidgin' forms sounds fine. I'm not sure if repent is then indicative or still morphologically imperative, it's still 2nd person without a subject... Makes me miss those complex Indo-European paradigms English sadly ditched 🤔

**Comment by nschneid** [comment]
One test for English imperatives is *don't* negation. "Act in haste, don't repent in haste"? Or to coin one with a more straightforward meaning: "Don't eat your vegetables, don't get dessert"? Doesn't sound idiomatic (I would say "Don't eat your vegetables, (and) you don't get dessert"). So I think I'll leave "repent" as VerbForm=Inf.

**Comment by nschneid** [comment]
"come December": "December" is attached as `obj` but it's the subject right?

**Comment by amir-zeldes** [comment]
Definitely subject IMO. I would not say it's plausible to suggest it's now a preposition, for example it doesn't coordinate with preps easily:

  * at, before and after the end of the year
  * ??come, before and after the end of the year

And in general I think we should avoid surprising analyses like these without strong evidence, most users will probably assume and expect that come is annotated as a verb.

**Comment by rueter** [comment]
> - [x] "First come, first serve"
> - [x] "if we're still dating come December": subjunctive with "December" as subject?
> - [x] "Act in haste, repent at leisure"

It hadn't occurred to me that the last of the three could be understood other than second person: "act in haste" "repent at leisure."

**Comment by amir-zeldes** [comment]
> I agree they're referring to an addressee, and "act" is an imperative used conditionally, but is "repent" imperative? 

I'm not totally sure, but maybe we could see it as a hypothetical sequence of events, in which case they're both imperative, like "go and see". So in the (bad) world where you act in haste and then repent, they're telling you: go ahead, do those two actions (and then you'll see how bad it would be). I'd be curious if IE langs with proper mood marking have such an expression, then we could see if the apodosis is really subjunctive in a related language?

**Comment by nschneid** [comment]
Closing as I think we have an acceptable solution given the lack of a clear test
