### ISSUE TITLE
Nonprojective modifiers

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#545]
- [x] [Premodifiers that attach nonprojectively](https://universal.grew.fr/?custom=66a2af7f468af): most are errors involving coordinated heads (should attach to the first conjunct)
  * [a few in GUM too](https://universal.grew.fr/?custom=66a2b03b93956)
- [x] [Postmodifiers that attach nonprojectively](https://universal.grew.fr/?custom=66a2b1b8dfb96): many are legit (stranded prepositions in questions, etc.), but not all

**Comment by nschneid** [comment]
(inspired by https://github.com/grew-nlp/grew/issues/49)

**Comment by nschneid** [comment]
Checked off the first one for EWT because I think all 12 results at https://universal.grew.fr/?custom=66a348a1d87f3 are correct

**Comment by amir-zeldes** [comment]
Fixed the 3 GUM cases that were errors, thanks!
