### ISSUE TITLE
More nonprojectivity errors

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#548]
Some nonprojective modifiers were weeded out in #545, but more errors causing nonprojectivity remain.

- [x] [q1](https://universal.grew.fr/?custom=66c5ac2558c40) sentences with slashes
- [ ] [q2](https://universal.grew.fr/?custom=66c5adbff0db8) others
   * [ ] [q3](https://universal.grew.fr/?custom=66cddf1bb3be3) zooming in on the most suspicious cases

Valid causes of nonprojectivity: comparatives, fronted-WH constructions, (arguably) parentheticals, floating quantifiers/emphatic reflexives

Some of the errors are due to optional depictives with the old `acl` annotation (should be `advcl`, not caught in #321).

**Comment by nschneid** [comment]
"Performance tests will either be performed on a project basis or a unit by unit basis in a given project." Coordinated PPs. Should the "either" be a nonprojective `cc:preconj`?

**Comment by nschneid** [comment]
Nonprojective expansions include "X, not Y", "X, even Y", "X, rather than Y" where X contains a nominal antecedent being contrasted with (but not at the end).

Also a problem: city/state/ZIP/country in street addresses.

**Comment by nschneid** [comment]
"up to a 60 day delivery"; "up to and including delivery" (note that the `fixed` guidelines only cover "up to" when used with quantities)

**Comment by nschneid** [comment]
"simply the best instructor": attachment of "simply"? It is currently attached to "best", whereas "the" attaches to "instructor", causing nonprojectivity. @amir-zeldes

**Comment by mr-martian** [comment]
> "simply the best instructor": attachment of "simply"? It is currently attached to "best", whereas "the" attaches to "instructor", causing nonprojectivity. @amir-zeldes

"simply" there sounds to me like an adverbial modification of the entire predicate. If we had "he is looking for simply the best instructor" it would be "looking", if it's "he is simply the best instructor" I'd think "instructor".

**Comment by nschneid** [comment]
I think (and dictionaries agree) that there's an intensifier adverb sense of "simply", e.g. "a simply amazing instructor" (*_a simply instructor_). What seems to have happened is that ["the best"](https://www.merriam-webster.com/dictionary/the%20best) started acting like an adjective ("amazing") and taking modifiers accordingly. You can't add another determiner though: *_I want a the best wine._ So maybe there's an incongruity between the syntactic and semantic modification structure.

**Comment by amir-zeldes** [comment]
I agree with @mr-martian , by default I would assume it modifies the entire phrase, which is why it stands outside the NP span (English doesn't generally allow intensifiers on an adjective to stand outside the NP bracket). "Simply" is also not a modification of the way in which this instructor is good or of that goodness (i.e. simply good vs. complicatedly good, "good in a way which is simple/complicated"). I think it's more like "Simply put, this is the best instructor".

**Comment by nschneid** [comment]
That is one possible reading. I get the feeling that "simply" and "the best" are collocates to accentuate the praise; _He is simply the/an instructor_ feels very different. We certainly need to acknowledge that "simply" can have intensification semantics in "a simply amazing instructor". But in "simply the best instructor" I think it doesn't make much sense to have "the" and "simply" headed by different things, so whether you view it as adnominal or adverbial, it has the same UD structure.

**Comment by amir-zeldes** [comment]
Yeah, I agree "a simply amazing instructor" should have the normal adjective intensifier tree, but if it's outside the NP I think we should stick to the expected phrase modifier reading.

**Comment by nschneid** [comment]
OK I think I've fixed the low-hanging fruit. Lots of theoretical issues that can be revisited though, e.g. how we treat expansions/parentheticals that are not classic appositions—whether they ought to be `appos` (often nonprojectively so) or something else (cf. UniversalDependencies/docs#1024). And street addresses need a policy.
