### ISSUE TITLE
SQL as an abbreviation - capitalized?

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_English-EWT#564]
What should be the lemma of SQL?  It's a specific name of a language, so capitalizing its lemma would follow examples such as NYC -> NYC.  However, it is lowercase in the one example in EWT:

```
# sent_id = newsgroup-groups.google.com_emails_ec0a1064de05e74b_ENG_20040929_023800-0037
# text = The project was designed to help use the newly written SQL code by IBM.
11      SQL     sql     NOUN    NN      Number=Sing     12      compound        12:compound     _
```

**Comment by nschneid** [comment]
I think it should be a PROPN, and capitalized. Will fix.
