### ISSUE TITLE
Enhanced dependency ambiguity

### ISSUE THREAD

**Issue by matgrioni** [UniversalDependencies/UD_English-EWT#72]
I was looking at that specification for enhanced dependencies and I am having trouble understanding the specification, as it seems that there is ambiguity in its use. Looking at the `edeprel.en` (file) [https://github.com/UniversalDependencies/tools/blob/master/data/edeprel.en](https://github.com/UniversalDependencies/tools/blob/master/data/edeprel.en) in the tools repo, the lines include:
```
obl:regardless
obl:since
obl:such_as
obl:the
obl:then
obl:through
```

These seem to me like the universal relation, followed by case information without any subrelation in between. Using the deprel.en file, it might seem possible to separate out if the second part is a subrelation or case information, but there are several duplicates between the two such as `acl:relcl`, so an instance of this cannot be determined as a subrelation or case information.

**Comment by nschneid** [comment]
Lexical enhancements in Enhanced Dependencies are added to the syntactic relation type following a colon. Sometimes the syntactic relation label includes a subtype introduced with a colon, e.g. `acl:relcl` and `nsubj:pass`. These subtypes may be language-specific. They are listed here: https://universaldependencies.org/ext-dep-index.html

Some of the Enhanced Dependencies also contain the special subtype `:xsubj`.

More at https://universaldependencies.org/u/overview/enhanced-syntax.html
