### ISSUE TITLE
Recommended detokenizer

### ISSUE THREAD

**Issue by Henry-E** [UniversalDependencies/UD_English-EWT#73]
Let's say the `space after` information was not available or not generated. What kind of tokenization scheme is used to create the corpus and hence what detokenizer would be recommended for recreating the original sentence from a conllu representation?

**Comment by ethanachi** [comment]
The original tokenization comes from the [LDC English Web Treebank](https://catalog.ldc.upenn.edu/LDC2012T13), which is the textual source of this treebank; I presume that more authoritative documentation on tokenization decisions can be found there :)
