### ISSUE TITLE
Many incorrect $ amounts

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#80]
An expression like "$ 1" should be nummod($/SYM, 1/NUM), but there are [numerous examples](http://bionlp-www.utu.fi/dep_search/query?search=%22%24%22%20%3E%21nummod%20NUM&db=UD_English-EWT-dev&case_sensitive=True&hits_per_page=100) which incorrectly use a `compound` relation, and 1 example where the number is the head instead of "$".

**Comment by ethanachi** [comment]
See 69d074db08d91643f29d351d5fb5b15b1ac4023a.

**Comment by nschneid** [comment]
Thanks for fixing the deprels. Is there also still an example where the number is the head of "$"?
