### ISSUE TITLE
Inconsistent decisions about SCONJ/ADV and mark/advmod for subordinate-clause-introducers

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#88]
Especially with "when" and "where":

![image](https://user-images.githubusercontent.com/985263/81325966-1cf3ea80-9067-11ea-89b8-b856e2eb4fc8.png)

![image](https://user-images.githubusercontent.com/985263/81325986-22513500-9067-11ea-8135-7f0c57bd7071.png)

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/985263/81326225-84119f00-9067-11ea-97b2-43f4e58513b5.png">

Should all of these be `SCONJ` and `mark` in UDv2? [`SCONJ` guidelines](https://universaldependencies.org/u/pos/SCONJ.html) mention "when" introducing a clause.

Note that in [GUM](/UniversalDependencies/UD_English-GUM), "where" and "when" are always tagged `SCONJ`, and nearly always attach to a subordinate clause as `mark` or head a relative clause.

**Comment by dan-zeman** [comment]
_When_ is trickier of the two and I can imagine that it will be more `SCONJ`-like in some sentences (when it alternates with _if_) and more `ADV`-like in other sentences (when the meaning is more temporal). I am not sure if a sharp boundary can be established and tested.

However, _where_ is adverb, and in the above example it is even coreferential with the modified nominal _in Sudan_.

**Comment by nschneid** [comment]
@dan-zeman If these can be `ADV`, would they attach to subordinate clauses as `mark` or `advmod`?

**Comment by dan-zeman** [comment]
When they are `ADV` then they should be `advmod`. Similar to wh-pronouns, which attach as `nsubj`, `obj` or `obl`, not as `mark`.

**Comment by nschneid** [comment]
@dan-zeman Should that be added to the `rel-upos-mark` test in the validator? I see errors for "'mark' should not be 'DET'" and "'mark' should not be 'VERB'" but none regarding ADV.

**Comment by nschneid** [comment]
Relatedly, there are instances of instead/`ADV`--`fixed`-> of/`SCONJ` attaching as `mark`, and so/`ADV` attaching as `mark`. Maybe those are errors too.

**Comment by dan-zeman** [comment]
I can confirm that the test currently specifically targets `(NOUN|PROPN|ADJ|PRON|DET|NUM|VERB|AUX|INTJ)`, that is, it allows `SCONJ` with `mark`, but also `ADP`, `CCONJ`, `ADV`, `PART`, `SYM` and `X` (but not `PUNCT`, which will be caught by other tests). I don't remember whether being benevolent to adverbs was my idea, or it is a result of a later discussion here (I could imagine that people protested that border cases like _when_ should be allowed). But I don't see any reference to such a discussion in the comments in the source code, so maybe we could try to exclude adverbs from `mark` – but not before UD 2.6 is released.

**Comment by amir-zeldes** [comment]
My knee-jerk reaction to this is to say that distinguishing temporal/conditional 'when' in the syntax tree is unrealistic, and I think that's probably the right thing to say. But paradoxically, this is actually something we could probably distinguish for GUM automatically because we have complete discourse parses distinguishing a relation `condition` from `circumstance` and `sequence`. 

But since that's not feasible to use for the other English corpora, I'd say we should just make the interrogative ones be `advmod` and the subordinate ones `mark`. I'm happy to implement this for GUM if the consensus is that that would be better.

**Comment by dan-zeman** [comment]
@amir-zeldes : But if some occurrences of _when_ are `advmod` and some others `mark`, it is probably easy to also tag the former `ADV` and the latter `SCONJ`, hence the validator could in principle test it, right?

**Comment by amir-zeldes** [comment]
Yes, the tagging and deprel issue are bundled, I just meant that distinguishing the two cases in EWT is non-trivial so probably not a feasible edit. 

If anyone does want to try, I'm happy to point out training resources for `condition` vs. not, there's data from GUM, RST-DT, possibly PDTB (I'd need to check if it's distinguished) and other resources. Just in case someone looks into this later, for GUM you can find this information for example here:

  * As RST trees: https://github.com/amir-zeldes/gum/blob/master/rst/rstweb/GUM_academic_replication.rs3#L35
  * As discourse dependencies: https://github.com/amir-zeldes/gum/blob/master/rst/dependencies/GUM_academic_replication.rsd#L4

or as a query in ANNIS, something like this:

http://corpling.uis.georgetown.edu/annis/#_q=bGVtbWE9IndoZW4iIF9sXyByc2RfcmVsPSJjaXJjdW1zdGFuY2VfciI&_c=R1VN&cl=5&cr=5&s=0&l=10

http://corpling.uis.georgetown.edu/annis/#_q=bGVtbWE9IndoZW4iIF9sXyByc2RfcmVsPSJjb25kaXRpb25fciI&_c=R1VN&cl=5&cr=5&s=0&l=10

**Comment by amir-zeldes** [comment]
The ADV/SCONJ split is now implemented in GUM V6.1.0 and live in the UD dev branch, incl. in UD_English-GUMReddit, and in GU ANNIS. I can run the same depedit script on EWT, but I'm not sure if someone is editing the EWT dev branch concurrently. 

If someone wants me to do this I can make a PR, just let me know.

**Comment by nschneid** [comment]
@amir-zeldes I pushed some EWT fixes last night but am done now, so have at it!

**Comment by amir-zeldes** [comment]
OK, implemented in #90 

@nschneid Can you review and merge?

**Comment by nschneid** [comment]
@dan-zeman Should `SCONJ` uses of "when", "where", etc. be [`PronType=Int`](https://universaldependencies.org/u/feat/PronType.html#int-interrogative-pronoun-determiner-numeral-or-adverb) or `PronType=Rel`?

**Comment by nschneid** [comment]
Fixed in #90

**Comment by nschneid** [comment]
Reopening this because the current policy produces odd results. First, [interrogative determiners are always WDT and DET](http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=61db1e0ce5e46&clustering=X.upos), not SCONJ. Why should interrogative adverbs be different? The first result from the linked query illustrates this nicely, suggesting the bracketing:

- opinions on [**how**/SCONJ/mark [it happened] and [[**what**/DET/det effect] Chernobyl will have]]

Whereas the structure I would assign is:

- opinions on [[**how**/ADV/advmod it happened] and [[**what**/DET/det effect] Chernobyl will have]]

Second, "how" can modify an adjective `xcomp` rather than the main embedded predicate: "I can't tell you [how ominous] I found Bush's performance". It can even modify an adjective of an embedded object: "it depends on [[how good] a horse] you have". `mark` doesn't attach to the main embedded predicate here, which is counterintuitive to me; `advmod` seems more correct.

**Comment by nschneid** [comment]
Actually after reading up on free relatives I don't think it is one, I think it's an interrogative content clause. But this is a complicated discussion so let's do that in a meeting.

**Comment by amir-zeldes** [comment]
Sure, happy to talk more about it when we meet - FWIW I think a content clause would be acl (the opinion that...), whereas this one conflates two functions, like a "what" free relative (it's short for a separaable "opinions about the way/nmod, how..."). So we prefer the matrix function, and tag "how" as nmod IMO.

**Comment by nschneid** [comment]
Whew, so today we decided to dispense with SCONJ/mark and always use ADV/advmod for "when" and "how". The best argument in my mind is a sentence like

- I wonder **how much money he has**

(interrogative complement clause with predicate "has")—mark(much, how/SCONJ) would be decidedly weird, because the SCONJ usually marks the predicate itself. This brings WH words in complement clauses in line with main clauses (and relative clauses). 

Implementing this change should be pretty straightforward since we are removing a putative distinction, not adding one.

**Comment by amir-zeldes** [comment]
Actually we had kept "how/advmod ADJ" (how much etc.) in GUM even after the shift to mark for the independent WH subordinators, so that doesn't need to change. I do wonder whether we have thought this through though: do we have an exhaustive list of the ones that should be advmod? Like, how about "once" or "while"?

**Comment by nschneid** [comment]
I think we only were talking about WH adverbs. "While" makes sense as SCONJ because it always introduces a clause, right? "Once" can be an adverb (unlike "if", "while", "that") but I'm not sure whether that means we shouldn't call it SCONJ where it introduces a clause.

**Comment by amir-zeldes** [comment]
If "once" is SCONJ when introducing a clause (i.e. stands where 'if' can stand) then I don't really understand why we would want "when" to be advmod... Not that I feel really strongly about any of this (it's automatable and therefore doesn't mean much), but it feels arbitrary to me. If I'm being honest, I don't think there is a syntactic difference between "if we go" and "when we go".

**Comment by nschneid** [comment]
Well, I don't think the ADV vs. SCONJ dichotomy for the words we're discussing is a perfect fit for English, but we're stuck with it. :) I could go either way on "once". I just want all the WH-words to be ADV so that "I wonder how you feel", "I wonder how much money you make", "I wonder where you live", "I wonder when it ends", etc. all end up the same, and match the main clause versions of those subordinate clauses ("How do you feel?", "How much money do you make?", "Where do you live?", "When does it end?").

If we wanted to be very particular we could make an argument that "once" has been grammaticalized from an adverb to a subordinator, so it should be ADV/mark in these constructions. But we haven't gone down that road (yet) for prepositions functioning as subordinators. For now probably best to say "once" is SCONJ/mark.

**Comment by amir-zeldes** [comment]
OK, I can live with that

**Comment by nschneid** [comment]
> BTW, not exactly related but since I'm looking at the (e)deps, did we settle on flip-flopping when/where back to advmod where they were previously mark? If so, do you have an exhaustive list of the items this applies to? I have:
>
> `when|where|whither|whence|while|why`

_Originally posted by @amir-zeldes in https://github.com/UniversalDependencies/UD_English-EWT/issues/346#issuecomment-1205712176_

In at least some cases, yes. _how_, _when_, _Xever_, ...

**Comment by nschneid** [comment]
From above I think we decided "while" is SCONJ.

**Comment by amir-zeldes** [comment]
Mm, so 'while' stays SCONJ/mark (in all contexts), and when|where|whither|whence|why are ADV/advmod?

Is there ever a context in which 'while' is ADV/advmod or one of the others above is SCONJ/mark?

**Comment by nschneid** [comment]
Not that I know of? They are all WH-words except for "while".

**Comment by amir-zeldes** [comment]
OK, I can make this happen in GUM, but looking at EWT dev it's currently not this way. Is this change pending in EWT?

**Comment by nschneid** [comment]
Yes

**Comment by nschneid** [comment]
Docs are now updated: [SCONJ](https://universaldependencies.org/u/pos/SCONJ.html), [ADV](https://universaldependencies.org/u/pos/ADV.html), [advmod](https://universaldependencies.org/u/dep/advmod.html)
