### ISSUE TITLE
"of course": 5 instances attached as discourse, should be advmod?

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-EWT#89]
From UniversalDependencies/docs/issues/474:

> * **of course:** In the English treebank, there are [4 tokens](http://bionlp-www.utu.fi/dep_search/query?search=_%20%3Ediscourse%20%28of%20%3Efixed%20course%29&db=UD_English-v2&case_sensitive=True&hits_per_page=50) where *of course* is attached as `discourse`. I'm guessing at least 2 of them should be `advmod`, which is how most *of course* tokens are handled, as well as all tokens of *however*. For the two sentence fragments where there is no verb, I think `discourse` is reasonable.

I'm now seeing 5 "of course" tokens that are `discourse` and about 15 that are `advmod`. If nobody objects I'll change the 5 to `advmod` for consistency.

**Comment by ethanachi** [comment]
@nschneid, did you end up fixing this?

**Comment by nschneid** [comment]
I don't remember but probably not. Thanks :)

**Comment by amir-zeldes** [comment]
Good catch, I just noticed we had inconsistent cases in GUM too. Will fix in origin dev, will propagate to UD at next release.

**Comment by ethanachi** [comment]
Going to address these five: http://match.grew.fr/?corpus=UD_English-EWT@2.7&custom=5fda747cbfa89
