### ISSUE TITLE
PROPN or NOUN

### ISSUE THREAD

**Issue by jheinecke** [UniversalDependencies/UD_English-EWT#91]
I've just come across a some 14 sentences where the (common noun?) _president_ (except in titles like _president Bush_) is annotated as `PROPN` (_George W. Bush alleged Thursday that John Edwards lacks the experience necessary to be **president**._, `weblog-juancole.com_juancole_20040708181175_ENG_20040708_181175-0001` and others). Similar case for _governor_ (e.g. _Davis spokesman Steve Maviglio said the **governor** felt "betrayed" by the actions of Winter._, `email-enronsent07_01-0031`) 

Others cases where the PROPN tag seems correct, but is spelled in lower case, are (_YES, I am west of **broad**._, reviews-351561-0022). If _broad_ is a PRON, shoud the lemma column at least be capitalized? Cf. also _christmas_ (_**christmas** cake for **christmas** day._, `answers-20111107144339AA0qw5S_ans-0018`).
In _...has appeared in all the **english** Pakistan and India papers._, `weblog-blogspot.com_dakbangla_20050311135387_ENG_20050311_135387-0126` _english_ is a PROPN although used as an adjective. Are language names always tagged as PROPN?

are these erroneous annotations are did I miss something in the guidelines?

**Comment by nschneid** [comment]
The short answer is that the EWT corpus was converted from PTB-style annotation to UD, but the tagging decisions do not always line up perfectly. In the PTB style, for example, adjectives in proper names are tagged as proper nouns, though this is not really ideal per UD guidelines.

I think I agree with all of your suggestions, as long as they can be applied consistently in the corpus (and are not too much of a departure from policies of other corpora). The main reason nobody has tried to clean up all the proper name annotations is that it seems like a lot of work—but if you want to volunteer that would be great!

Related issues:
UniversalDependencies/docs/issues/678
UniversalDependencies/docs/issues/702
UniversalDependencies/docs/issues/562

**Comment by jheinecke** [comment]
Thaks for your reply. I did not want to reignite the discussion on how to annotate named entities. But these are cases where IMHO NOUN should be a better UPOS tag. I could provide a list here of PROPN (and sentences) which I would retag as NOUN (it won't be very long anyway)

**Comment by nschneid** [comment]
If you can submit a pull request for the dev branch we'll take a look!

**Comment by jheinecke** [comment]
No problem! (after the summer break :-)

**Comment by nschneid** [comment]
#164 overhauled the use of PROPN. If there are problems that we missed, let us know.
