### ISSUE TITLE
Lemma of "these"

### ISSUE THREAD

**Issue by amir-zeldes** [UniversalDependencies/UD_English-EWT#98]
I just noticed the lemma of 'these' is 'these' in both EWT and GUM, but I think it should be 'this'. I can change it in GUM, but didn't want to break parity with EWT. Any objections to changing it in both datasets?

**Comment by arademaker** [comment]
I would be interested in the conclusion here. We have a similar discussion for Portuguese. Should we change pronouns and determinants to a single lemma form?

**Comment by nschneid** [comment]
(Same for "those".) I have never quite understood the policy for lemmatizing pronouns/determiners in English. But as number is something that gets normalized for noun lemmas, I think we should do so for pronoun and determiner lemmas.

**Comment by amir-zeldes** [comment]
FWIW it's already done in many languages (these -> this, masc. sg.), including German, Polish, Coptic and Arabic (but oddly not in Hebrew, another one of the unexpected discrepancies esp. between UD Hebrew and Arabic)

**Comment by manning** [comment]
Yeah, I agree. I think there is no reason for this except that our original lemmatizer only did nouns and verbs....

I'll change EWT [dev] right now.

**Comment by manning** [comment]
Thanks for pointing this out. Fixed in d49d270d1a95a090bda5c269e75e7867bd26760a.
